---
permalink: sg6000/replacing-sg6000-cn-controller.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, Replacing, replace, sg6000-cn, controller, remove, removing, removal, install, installing, installation 
summary: 如果SG6000-CN-控制器無法以最佳方式運作、或是發生故障、您可能需要更換該控制器。 
---
= 更換SG6000-CN控制器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果SG6000-CN-控制器無法以最佳方式運作、或是發生故障、您可能需要更換該控制器。

.您需要的是 #8217 ；需要的是什麼
* 您的更換控制器的零件編號與您要更換的控制器相同。
* 您可以使用標籤來識別連接至控制器的每條纜線。
* 您已實際找到要在資料中心更換的控制器。
+
xref:locating-controller-in-data-center.adoc[在資料中心找到控制器]



當您更換SG6000-CN-控制器時、將無法存取應用裝置儲存節點。如果SG6000-CN-控制器運作正常、您可以在本程序開始時執行管制關機。


NOTE: 如果您在安裝StorageGRID 完此程序之前更換控制器、可能StorageGRID 無法在完成此程序後立即存取《產品安裝程式（到此程序）」。雖然StorageGRID 您可以從與應用裝置位於同一子網路的其他主機存取《ENetApp應用裝置安裝程式」、但您無法從其他子網路的主機存取。此情況應在15分鐘內自行解決（當原始控制器的任何ARP快取項目逾時時）、或者您可以從本機路由器或閘道手動清除任何舊的ARP快取項目、以立即清除此狀況。

.步驟
. 如果SG6000-CN-控制器的運作能力足以允許控制關機、請關閉SG6000-CN-控制器。
+
xref:shutting-down-sg6000-cn-controller.adoc[關閉SG6000-CN.控制器]

. 使用兩種方法之一來驗證SG6000-CN-控制器的電源是否已關閉：
+
** 控制器正面的電源指示燈LED熄滅。
** BMC介面的「Power Control（電源控制）」頁面表示控制器已關閉。


. 如果StorageGRID 連接至控制器的靜態網路使用DHCP伺服器、請更新DNS/網路和IP位址設定。
+
.. 找到SG6000-CN-控制器正面的MAC位址標籤、然後判斷管理網路連接埠的MAC位址。
+

NOTE: MAC位址標籤會列出BMC管理連接埠的MAC位址。+若要判斷管理網路連接埠的MAC位址、您必須將* 2 *新增至標籤上的十六進位數字。例如、如果標籤上的MAC位址以* 09 *結尾、則管理連接埠的MAC位址將以* 0B*結尾。如果標籤上的MAC位址以*（_y_）FF*結尾、則管理連接埠的MAC位址將以*（_y_+1*）結尾。您可以在Windows中開啟「計算機」、將其設定為「程式設計師」模式、選取「Hex」、輸入MAC位址、然後輸入*+ 2 =*、輕鬆完成此計算。

.. 請網路管理員將您移除的控制器的DNS/網路和IP位址與更換控制器的MAC位址建立關聯。
+

IMPORTANT: 您必須先確保原始控制器的所有IP位址都已更新、才能將電力套用至更換的控制器。否則、當控制器開機時、就會取得新的DHCP IP位址、而且可能無法重新連線StorageGRID 到故障。此步驟適用於StorageGRID 連接至控制器的所有環節網路。

+

NOTE: 如果原始控制器使用靜態IP位址、新控制器將自動採用您移除的控制器IP位址。



. 移除並更換SG6000-CN-控制器：
+
.. 標記纜線、然後拔下纜線和任何SFP+或SFP28收發器。
+

IMPORTANT: 為避免效能降低、請勿扭轉、摺疊、夾緊或踏上纜線。

.. 從機櫃或機架中取出故障控制器。
.. 將替換控制器安裝到機櫃或機架中。
.. 更換纜線及任何SFP+或SFP28收發器。
.. 開啟控制器電源、並監控控制器LED和開機代碼。


. 確認應用裝置儲存節點出現在Grid Manager中、且未顯示任何警示。
. 從Grid Manager中選取* nodes *、然後驗證節點控制器的BMC IP位址是否正確。
+
如果節點控制器IP位址無效或不在預期範圍內、請依照恢復與維護說明中的說明重新設定IP位址。

+

NOTE: 如果您在原始安裝期間套用其他自訂功能、例如設定SNMP設陷目的地或電子郵件通知、您應該記錄並驗證組態、並視需要重新套用。

+
xref:../maintain/index.adoc[恢復與維護]



xref:sg6000-cn-installing-into-cabinet-or-rack.adoc[SG6000-CN:安裝在機櫃或機架中]

xref:viewing-status-indicators-and-buttons-on-sg6000-cn-controller.adoc[檢視SG6000-CN-控制器上的狀態指示燈和按鈕]

xref:viewing-boot-up-codes-for-sg6000-cn-controller.adoc[檢視SG6000-CN-控制器的開機代碼]
