---
permalink: sg6000/upgrading-santricity-os-on-storage-controllers.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, controller, storage controller, upgrade, upgrading, SANtricity OS, SANtricity 
summary: 為了確保儲存控制器發揮最佳功能、您必須升級SANtricity 至符合StorageGRID 您的不合格產品資格的最新版作業系統維護版本。請參閱NetApp互通性對照表工具（IMT NetApp Interoperability Matrix Tool）（簡稱「參考」）、以判斷您應該使用的版本。如果您需要協助、請聯絡技術支援部門。 
---
= 升級SANtricity 儲存控制器上的作業系統
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
為了確保儲存控制器發揮最佳功能、您必須升級SANtricity 至符合StorageGRID 您的不合格產品資格的最新版作業系統維護版本。請參閱NetApp互通性對照表工具IMT （NetApp Interoperability Matrix Tool、簡稱「參考資訊」）、判斷您應該使用哪個版本。如果您需要協助、請聯絡技術支援部門。

根據SANtricity 目前安裝的版本、使用下列其中一個程序：

* 如果儲存控制器使用SANtricity 的是更新版本的作業系統08.42.20.00（11.42）、請使用Grid Manager執行升級。
+
xref:upgrading-santricity-os-on-storage-controllers-using-grid-manager-sg6000.adoc[使用SANtricity Grid Manager升級儲存控制器上的作業系統]

* 如果儲存控制器使用SANtricity 的是版本早於08.42.20.00（11.42）的更新版、請使用維護模式來執行升級。
+
xref:upgrading-santricity-os-on-storage-controllers-using-maintenance-mode-sg6000.adoc[使用SANtricity 維護模式升級儲存控制器上的作業系統]




IMPORTANT: 升級SANtricity 儲存應用裝置的支援功能時、您必須遵循StorageGRID 本文檔中的說明。如果您使用任何其他指示、您的應用裝置可能無法運作。

https://mysupport.netapp.com/matrix["NetApp 互通性對照表工具"^]

https://mysupport.netapp.com/site/products/all/details/eseries-santricityos/downloads-tab["NetApp下載：SANtricity 支援"^]

xref:../monitor/index.adoc[監控及疑難排解]
