---
permalink: sg6000/verifying-and-upgrading-storagegrid-appliance-installer-version.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, Verifying, verify, upgrading, upgrade, update, updating, Appliance Installer, version, release 
summary: 應用裝置上的《產品安裝程式版本」必須與安裝在您的支援系統上的軟體版本相符、才能確保支援所有的功能。StorageGRID StorageGRID StorageGRID 
---
= 驗StorageGRID 證並升級版本的應用程式
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
應用裝置上的《產品安裝程式版本」必須與安裝在您的支援系統上的軟體版本相符、才能確保支援所有的功能。StorageGRID StorageGRID StorageGRID

.您需要的產品
您已存取StorageGRID 了《應用程式安裝程式：

.關於這項工作
來自原廠預先安裝的不含不含「功能」的應用程式。StorageGRID StorageGRID如果您要將應用裝置新增至最近升級StorageGRID 的更新的版本、可能需要手動升級StorageGRID 該應用裝置的安裝程式、才能將應用裝置安裝為新節點。

當您升級至新版的更新版本時、會自動升級此產品的安裝程式。StorageGRID StorageGRID您不需要在StorageGRID 安裝的應用裝置節點上升級「效益設備安裝程式」。僅當您安裝的應用裝置含有StorageGRID 舊版的《一套》的《一套應用程式》安裝程式時、才需要執行此程序。

.步驟
. 從「VMware應用裝置安裝程式」StorageGRID 中、選取*進階*>*升級韌體*。
. 比較目前的韌體版本與StorageGRID 安裝在您的系統上的軟體版本。（從Grid Manager頂端、選取說明圖示、然後選取*關於*。）
+
兩個版本中的第二個數字應該相符。例如StorageGRID 、如果您的Sf2系統執行的是11.*6*._x_._y_版、StorageGRID 則該版本的《EzAppliance Installer》應該是3.*6*。_z_。

. 如果應用裝置的StorageGRID 版本低於此版本、請前往 https://["NetApp下載：StorageGRID NetApp產品"^]。
+
以您NetApp帳戶的使用者名稱和密碼登入。

. 下載StorageGRID 適當版本的*支援檔案for the Sof the Sof the Sof the Sof the Sof the Sof the Sof the Sof the Sof the Sof
+
支援文件for the Supports檔案是一個「.Zip」檔案、其中包含所有版本的所有版本的更新韌體、以及每種控制器類型的子目錄。StorageGRID StorageGRID

+
下載StorageGRID 完「支援」檔案以取得有關安裝StorageGRID 《支援》應用程式的重要資訊後、請擷取「.zip」檔案、並參閱README檔案。

. 請依照的「升級韌體」頁面上的指示進行 xref:accessing-storagegrid-appliance-installer-sg6000.adoc[應用程式安裝程式StorageGRID] 若要執行下列步驟：
+
.. 上傳適當的支援檔案（韌體映像）以供控制器類型和Checksum檔案使用。
.. 升級非使用中的分割區。
.. 重新開機並切換分割區。
.. 升級第二個（非作用中）分割區。



