---
permalink: audit/audit-message-format.html 
sidebar: sidebar 
keywords: storagegrid, audit, message formats, message format 
summary: 在這個系統內交換的稽核訊息StorageGRID 包括所有訊息通用的標準資訊、以及說明所報告事件或活動的特定內容。 
---
= 稽核訊息格式
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在這個系統內交換的稽核訊息StorageGRID 包括所有訊息通用的標準資訊、以及說明所報告事件或活動的特定內容。

如果「稽核說明」和「稽核摘要」工具所提供的摘要資訊不足、請參閱本節以瞭解所有稽核訊息的一般格式。

以下是稽核記錄檔中可能出現的稽核訊息範例：

[listing]
----
2014-07-17T03:50:47.484627
[AUDT:[RSLT(FC32):VRGN][AVER(UI32):10][ATIM(UI64):1405569047484627][ATYP(FC32):SYSU][ANID(UI32):11627225][AMID(FC32):ARNI][ATID(UI64):9445736326500603516]]
----
每個稽核訊息都包含一串屬性元素。整個字串都以括弧括住（`[]）、字串中的每個屬性元素都具有下列特性：

* 以括弧形式括住
* 由字串「AUDT」引進、表示稽核訊息
* 不含分隔符號（不含逗號或空格）
* 以換行字元"n"終止


每個元素都包含屬性代碼、資料類型及以下列格式報告的值：

[listing]
----
[ATTR(type):value][ATTR(type):value]...
[ATTR(type):value]\n
----
訊息中的屬性元素數目取決於訊息的事件類型。屬性元素不會以任何特定順序列出。

下列清單說明屬性元素：

* 「attr」是所報告屬性的四個字元代碼。有些屬性是所有稽核訊息和其他特定事件的常見屬性。
* 「type」是值的程式設計資料類型（例如UI64、FC32等）的四個字元識別碼。此類型以括弧「（）」括住。
* 「Value」是屬性的內容、通常是數值或文字值。值總是跟在一個分號（「：」）之後。資料類型CStr的值會被雙引號"""括住。


.相關資訊
xref:using-audit-explain-tool.adoc[使用稽核說明工具]

xref:using-audit-sum-tool.adoc[使用稽核加總工具]

xref:audit-messages-main.adoc[稽核訊息]

xref:common-elements-in-audit-messages.adoc[稽核訊息中的一般元素]

xref:data-types.adoc[資料類型]

xref:audit-message-examples.adoc[稽核訊息範例]
