---
settings:
  name: StorageGRID
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
    lipi_enabled: false
  langs: zh-tw,us-en,ja-jp,ko-kr,zh-cn,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: 功能與功能StorageGRID
    url: "/index.html"
  - title: 版本資訊
    url: "/release-notes/index.html"
  - title: 開始使用
    entries:
    - section: primer
    - section: network
  - title: 安裝及維護應用裝置硬體
    entries:
    - section: sg100-1000
    - section: sg6000
    - section: sg5700
    - section: sg5600
  - title: 安裝及升級軟體
    entries:
    - section: upgrade
    - section: rhel
    - section: ubuntu
    - section: vmware
  - title: 執行系統管理
    entries:
    - section: admin
    - section: ilm
    - section: harden
    - section: fabricpool
  - title: 使用StorageGRID
    entries:
    - section: tenant
    - section: s3
    - section: swift
  - title: 監控及維護StorageGRID 功能
    entries:
    - section: monitor
    - section: expand
    - section: maintain
    - section: audit
  - title: 啟用StorageGRID 功能
    url: "/storagegrid-enable.html"
  - title: 其他版本
    url: "/earlier-versions.html"
  - title: 法律聲明
    url: "/legal-notices.html"
product-family:
  name: StorageGRID documentation
  repo: storagegrid-family
