---
permalink: upgrade/estimating-time-to-complete-upgrade.html 
sidebar: sidebar 
keywords: upgrade, time estimate, duration, cassandra upgrade 
summary: 在規劃升級StorageGRID 至更新版時、您必須根據升級所需的時間來考慮何時進行升級。您也必須知道在升級的每個階段中、可以執行哪些作業、也不能執行哪些作業。 
---
= 預估完成升級所需的時間
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在規劃升級StorageGRID 至更新版時、您必須根據升級所需的時間來考慮何時進行升級。您也必須知道在升級的每個階段中、可以執行哪些作業、也不能執行哪些作業。

.關於這項工作
完成升級所需的時間StorageGRID 取決於多種因素、例如用戶端負載和硬體效能。

下表摘要說明主要的升級工作、並列出每項工作所需的大約時間。表格後的步驟提供您可用來預估系統升級時間的指示。

[cols="1a,1a,1a,a"]
|===
| 升級工作 | 說明 | 大約所需時間 | 在此工作期間 


 a| 
啟動升級服務
 a| 
執行升級預先檢查、散佈軟體檔案、並啟動升級服務。
 a| 
每個網格節點3分鐘、除非報告驗證錯誤
 a| 
視需要、您可以在排程的升級維護時間之前手動執行升級預先檢查。



 a| 
升級網格節點（主要管理節點）
 a| 
主管理節點會停止、升級及重新啟動。
 a| 
30分鐘到1小時、SG100和SG1000應用裝置節點最需要時間。
 a| 
您無法存取主要管理節點。系統會報告連線錯誤、您可以忽略這些錯誤。



 a| 
升級網格節點（所有其他節點）
 a| 
所有其他網格節點上的軟體都會依照您核准節點的順序進行升級。系統中的每個節點將每次關閉一個節點數分鐘。
 a| 
每個節點15分鐘到1小時、應用裝置節點最需要時間

*附註：* StorageGRID 針對應用裝置節點、將自動更新至最新版本的《Sfor applianceAppliance Installer》。
 a| 
* 請勿變更網格組態。
* 請勿變更稽核層級組態。
* 請勿更新ILM組態。
* 您無法執行其他維護程序、例如修復程式、取消委任或擴充。
+
*附註：*如果您需要執行恢復、請聯絡技術支援部門。





 a| 
啟用功能
 a| 
新版本的新功能已啟用。
 a| 
不到5分鐘
 a| 
* 請勿變更網格組態。
* 請勿變更稽核層級組態。
* 請勿更新ILM組態。
* 您無法執行其他維護程序。




 a| 
升級資料庫
 a| 
升級程序會檢查每個節點、確認不需要更新Cassandra資料庫。
 a| 
每個節點10秒或整個網格幾分鐘
 a| 
從還原11.5升級StorageGRID 至11.6%不需要Cassandra資料庫升級、不過、Cassandra服務會在每個儲存節點上停止並重新啟動。

對於未來StorageGRID 的版本、Cassandra資料庫更新步驟可能需要幾天的時間才能完成。



 a| 
最終升級步驟
 a| 
移除暫用檔案、並完成新版本的升級。
 a| 
5分鐘
 a| 
當*最終升級步驟*工作完成時、您可以執行所有的維護程序。

|===
.步驟
. 預估升級所有網格節點所需的時間。
+
.. 將您的支援系統中的節點數乘StorageGRID 以1小時/節點。
+
一般而言、應用裝置節點的升級時間比軟體型節點長。

.. 這次增加1小時、以說明下載「.升級」檔案、執行預先檢查驗證、以及完成最終升級步驟所需的時間。


. 如果您有Linux節點、請為每個節點新增15分鐘、以說明下載及安裝RPM或Deb套件所需的時間。
. 新增步驟1和步驟2的結果、計算升級的預估總時間。




== 範例：預估升級StorageGRID 至示例11.6%的時間

假設您的系統有14個網格節點、其中8個是Linux節點。

. 將14乘以1小時/節點。
. 加1小時以說明下載、預先檢查及最終步驟。
+
升級所有節點的預估時間為15小時。

. 將8乘以15分鐘/節點、以計算在Linux節點上安裝RPM或Deb套件的時間。
+
此步驟的預估時間為2小時。

. 將這些值加在一起。
+
您最多應該有17小時的時間完成系統升級StorageGRID 至版本11.6.0。


