---
permalink: upgrade/whats-new.html 
sidebar: sidebar 
keywords: what is new in StorageGRID 11.6 
summary: 本版StorageGRID 的《產品介紹》介紹下列功能。 
---
= 更新功能StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
本版StorageGRID 的《產品介紹》介紹下列功能。



== 使用性增強功能

Grid Manager使用者介面經過大幅重新設計、可改善使用者體驗。

* 新的側欄取代舊使用者介面中的下拉式功能表。
* 已重新組織好幾個功能表、以便將相關選項保持在一起。例如、「*組態*」功能表包含「憑證」、「金鑰管理伺服器」、「Proxy設定」和「不受信任的用戶端網路」選項的新「*安全性*」區段。
* 標頭列中的*搜尋*欄位可讓您快速瀏覽至Grid Manager頁面。
* 「*節點*」頁面上的摘要表提供所有站台和節點的高階資訊、例如使用的物件資料和使用的物件中繼資料、並包含新的搜尋欄位。警示圖示會顯示在任何具有作用中警示的節點旁。
* 新精靈會引導您完成更複雜的組態、例如管理群組、管理使用者、租戶、負載平衡器端點和高可用度（HA）群組的工作流程。
* 所有UI頁面都會以更新的字型、按鈕樣式和表格格式重新設定。
+

NOTE: 除非有功能變更、StorageGRID 否則不會更新《畫面說明文件》網站中的螢幕快照、以反映新的Grid Manager網頁樣式。



請參閱下列內容：

* xref:../admin/index.adoc[管理StorageGRID]
* xref:../monitor/index.adoc[監控及疑難排解]




== 多個VLAN介面

您現在可以為管理節點和閘道節點建立虛擬LAN（VLAN）介面。您可以使用HA群組和負載平衡器端點中的VLAN介面來隔離和分割用戶端流量、以確保安全性、靈活度和效能。

* 全新的*建立VLAN介面*精靈會引導您輸入VLAN ID、並在一個或多個節點上選擇父介面。父介面可以是Grid Network、用戶端網路、或VM或裸機主機的其他主幹介面。請參閱 xref:../admin/configure-vlan-interfaces.html[設定VLAN介面]。
* 您現在可以將額外的主幹或存取介面新增至節點。如果您新增主幹介面、則必須設定VLAN介面。如果新增存取介面、您可以直接將介面新增至HA群組、而不需要設定VLAN介面。請參閱下列內容：
+
** * Linux（安裝節點之前）*：  enhancements
** * Linux（安裝節點之後）*： xref:../maintain/linux-adding-trunk-or-access-interfaces-to-node.adoc[Linux：新增主幹或存取介面至節點]
** * VMware（安裝節點之後）*： xref:../vmware/collecting-information-about-your-deployment-environment.adoc[收集部署環境的相關資訊]






== 可將Azure AD用於身分識別聯盟

您現在可以在設定Grid Manager或租戶管理程式的身分識別聯盟時、選取Azure Active Directory（Azure AD）做為身分識別來源。請參閱 xref:../admin/using-identity-federation.adoc[使用身分識別聯盟]。



== 可將Azure AD和PingFedate用於SSO

您現在可以在為網格設定單一登入（SSO）時、選取Azure AD或PingFedate作為SSO類型。然後、您可以使用沙箱模式來設定及測試Azure AD企業應用程式、或是PingFedate服務供應商（SP）連線至StorageGRID 每個「管理員節點」。請參閱 xref:../admin/configuring-sso.adoc[設定單一登入]。



== 集中式憑證管理

* 新的「憑證」頁面（*組態*>*安全性*>*憑證*）會將所有StorageGRID 的資訊整合到單一位置。您可以StorageGRID 從新頁面管理整個域、網格CA和用戶端憑證、或檢視其他憑證的相關資訊、例如用於負載平衡器端點、租戶和身分識別聯盟的憑證。請參閱 xref:../admin/using-storagegrid-security-certificates.adoc[關於安全性憑證]。
* 在此變更中、下列全域憑證已重新命名：
+
** *管理介面伺服器憑證*現在是*管理介面憑證*。
** *物件儲存API服務端點伺服器憑證*（也稱為儲存API伺服器憑證）現在是* S3和Swift API憑證*。
** *內部CA憑證*、*系統CA憑證*、* CA憑證*及*預設CA憑證*現在都一致稱為*網格CA憑證*。






== 其他Grid Manager增強功能

* *高可用度（HA）群組的更新*。精靈現在會引導您完成建立HA群組的程序。請參閱 xref:../admin/configure-high-availability-group.html[設定高可用度群組]。
+
** 除了選取Grid Network（eth0）或Client Network（eth2）上的介面、您現在還可以選取VLAN介面或新增至節點的任何存取介面。
** 您現在可以指定介面的優先順序。您可以選擇主要介面、並依序排列每個備份介面。
** 如果任何S3、Swift、管理或租戶用戶端將從不同子網路存取HA群組的VIP位址、您現在可以提供閘道的IP位址。


* *更新負載平衡器端點*。新精靈會引導您完成建立負載平衡器端點的程序。請參閱 xref:../admin/configuring-load-balancer-endpoints.adoc[設定負載平衡器端點]。
+
** 您現在可以在第一次建立端點時選取用戶端類型（S3或Swift）、而非在建立端點之後新增此詳細資料。
** 您現在可以將全域* StorageGRID 支援S3和Swift認證*用於負載平衡器端點、而非上傳或產生個別的認證。
+

NOTE: 此全域憑證先前用於連線至過時的CLB服務和儲存節點。如果您想要將全域憑證用於負載平衡器端點、則必須在S3和Swift API憑證頁面上傳自訂憑證。







== 全新租戶管理程式功能

* *新的實驗性S3主控台*。全新的實驗性S3主控台可從租戶管理程式的「資源庫」頁面連結取得、讓S3租戶使用者檢視及管理其資源庫中的物件。請參閱 xref:../tenant/use-s3-console.adoc[使用實驗性S3主控台]。



IMPORTANT: 實驗性S3主控台尚未經過完整測試、不適用於大量管理物件或用於正式作業環境。租戶只有在執行少數物件的功能或使用概念驗證或非正式作業網格時、才應使用S3主控台。

* *可以刪除多個S3儲存區*。租戶使用者現在可以一次刪除多個S3儲存區。您要刪除的每個儲存區都必須是空白的。請參閱 xref:../tenant/deleting-s3-bucket.adoc[刪除S3儲存區]。
* *租戶帳戶權限更新*。屬於具有租戶帳戶權限之群組的管理員使用者、現在可以檢視現有的流量分類原則。之前、使用者必須擁有root存取權限才能檢視這些指標。




== 全新升級與修補程式程序

* *《*版升級*》頁面重新設計（*維護*>*系統*>*軟體更新*>*版升級*）StorageGRID StorageGRID 。
* 升級StorageGRID 到完SESH11.6,您可以使用Grid Manager升級至未來版本,並同時套用該版本的修補程式。此更新頁面會顯示建議的升級途徑、並直接連結至正確的下載頁面。StorageGRID
* 更新*檢查軟體更新*核取方塊AutoSupport （*支援*>*工具*>* AutoSupport 還原*）可讓您控制此功能。如果您的系統無法存取WAN、您可以停用檢查可用的軟體更新。請參閱 xref:../admin/configure-autosupport-grid-manager.adoc#disable-checks-for-software-updates[設定AutoSupport 更新檢查；停用軟體更新檢查]。
+

NOTE: 若要升級StorageGRID 至Suse 11.6,您可以選擇使用指令碼來同時升級及套用修補程式。請參閱 https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_run_combined_major_upgrade_and_hotfix_script_for_StorageGRID["NetApp知識庫：如何執行StorageGRID 針對效益的重大升級與修補程式指令碼組合"^]。

* 如果SANtricity 您需要稍後再完成升級、現在可以暫停更新作業系統、並跳過升級部分節點。請參閱儲存應用裝置的說明：
+
** xref:../sg5600/upgrading-santricity-os-on-storage-controllers-using-grid-manager-sg5600.adoc[使用SANtricity Grid Manager升級儲存控制器上的作業系統（SG5600）]
** xref:../sg5700/upgrading-santricity-os-on-storage-controllers-using-grid-manager-sg5700.adoc[使用SANtricity Grid Manager（SG5700）升級儲存控制器上的作業系統]
** xref:../sg6000/upgrading-santricity-os-on-storage-controllers-using-grid-manager-sg6000.adoc[使用SANtricity Grid Manager升級儲存控制器上的作業系統（SG6000）]






== 外部syslog伺服器支援

* 如果您想StorageGRID 要遠端儲存及管理稽核訊息及部分的靜態記錄（*組態*>*監控*>*稽核與系統記錄伺服器*）、現在您可以設定外部系統記錄伺服器。設定外部syslog伺服器之後、您可以將稽核訊息和特定記錄檔儲存在本機、遠端或兩者。藉由設定稽核資訊的目的地、您可以減少管理節點上的網路流量。請參閱 xref:../monitor/configure-audit-messages.adoc[設定稽核訊息和記錄目的地]。
* 與此功能相關、「記錄」頁面上的新核取方塊（*支援*>*工具*>*記錄*）可讓您指定要收集的記錄類型、例如特定的應用程式記錄、稽核記錄、用於網路偵錯的記錄、以及Prometheus資料庫記錄。請參閱 xref:../monitor/collecting-log-files-and-system-data.adoc[收集記錄檔和系統資料]。




== S3 Select

您現在可以選擇性地允許S3租戶向個別物件發出SelectObjectContent要求。S3 Select提供一種有效率的方法來搜尋大量資料、而不需要部署資料庫和相關資源來啟用搜尋。它也能降低擷取資料的成本與延遲。請參閱 xref:../admin/manage-s3-select-for-tenant-accounts.adoc[管理用戶帳戶的S3 Select] 和 xref:../s3/use-s3-select.adoc[使用S3 Select]。

也新增S3 Select作業的Grafana圖表。請參閱 xref:../monitor/reviewing-support-metrics.adoc[檢視支援指標]。



== S3物件鎖定預設儲存區保留期間

使用S3物件鎖定時、您現在可以指定儲存區的預設保留期間。預設保留期間會套用至新增至儲存貯體但沒有其本身保留設定的任何物件。請參閱 xref:../s3/using-s3-object-lock.adoc[使用S3物件鎖定]。



== Google Cloud Platform支援

您現在可以使用Google Cloud Platform（GCP）作為Cloud Storage Pool和CloudMirror平台服務的端點。請參閱 xref:../tenant/specifying-urn-for-platform-services-endpoint.adoc[指定平台服務端點的URN] 和 xref:../ilm/creating-cloud-storage-pool.adoc[建立雲端儲存資源池]。



== AWS C2S支援

您現在可以使用AWS商業雲端服務（C2S）端點進行CloudMirror複寫。請參閱 xref:../tenant/creating-platform-services-endpoint.adoc[建立平台服務端點]。



== 其他S3變更

* *取得多部份物件的物件和物件支援*。先前StorageGRID 、在「Get Object（取得物件）」或「head Object（物件要求）」中、不支援「partNumber（零件編號）」要求參數。您現在可以發出Get和head要求、以擷取多個部分物件的特定部分。Get and head Object也支援「x-amz-mp-s成分 數」回應元素、以指出物件有多少個部分。
* *變更為「可用」一致性控制*。「可用」一致性控制現在的運作方式與「新寫入後讀取」一致性層級相同、但最終可提供一致的標頭和取得作業。如果儲存節點無法使用、「可用」一致性控制功能可為一般使用者提供更高的可用度、並使作業比「讀取後新寫入」更順利。不同於Amazon S3一致性保證、可確保使用者執行作業。
+
xref:../s3/index.adoc[使用S3]





== 效能增強

* *儲存節點可支援20億個物件*。儲存節點的基礎目錄結構經過最佳化、可提供更好的擴充性與效能。儲存節點現在使用額外的子目錄來儲存多達20億個複寫物件、並將效能最大化。節點子目錄會在您升級StorageGRID 至Eshot 11.6s時修改、但現有物件不會重新分配至新目錄。
* * ILM驅動的刪除效能提升、適用於高效能應用裝置*。執行ILM刪除作業所需的資源和處理量、現在可隨StorageGRID 每個ESIDE節點的大小和功能而調整。對於SG5600應用裝置、處理量與StorageGRID 針對S11的速度相同。對於SG5700應用裝置、ILM刪除效能已有小幅改善。對於擁有更多RAM和CPU的SG6000應用裝置、ILM刪除的處理速度現在更快。在All Flash SGF6024應用裝置上、這項改善尤其顯著。
* *儲存Volume浮點最佳化*。在先前的版本中、三個儲存Volume浮點的設定會套用至每個儲存節點上的每個儲存Volume。現在、根據儲存節點的大小和磁碟區的相對容量、可將這些浮點最佳化至每個儲存磁碟區。StorageGRID請參閱 xref:../admin/what-storage-volume-watermarks-are.adoc[什麼是儲存Volume浮點]。
+
最佳化的浮水印會自動套用至所有全新且升級最多StorageGRID 的更新版的更新版的還原11.6Systems。最佳化的浮水印將大於先前的預設設定。

+
如果您使用自訂浮點、則升級後可能會觸發*低唯讀浮點置換*警示。此警示可讓您知道自訂浮水印設定是否太小。請參閱 xref:../monitor/troubleshoot-low-watermark-alert.adoc[疑難排解低唯讀浮水印會覆寫警示]。

+
在此變更中、我們新增了兩項Prometheus指標：

+
** 「toragegRid_Storage_volume最小值_最佳化_軟體_readonly浮水印」
** 「toragegRid_Storage_Volume最大值_imized_soft_readonly浮水印」


* *允許的中繼資料空間上限增加*。儲存節點允許的最大中繼資料空間已增加至3.96 TB（從2.64 TB）、適用於容量較大的節點、這些節點是實際保留空間用於4 TB以上中繼資料的節點。這項新值可在特定儲存節點上儲存更多物件中繼資料、StorageGRID 並可將支援的中繼資料容量增加50%。
+

NOTE: 如果您尚未這麼做、而且儲存節點有足夠的RAM和磁碟區0的足夠空間、您可以這麼做 xref:../upgrade/increasing-metadata-reserved-space-setting.adoc[安裝或升級後、手動將中繼資料保留空間設定增加至8 TB]。

+
** xref:../admin/managing-object-metadata-storage.adoc#allowed-metadata-space[管理物件中繼資料儲存區>允許的中繼資料空間]
** xref:../upgrade/increasing-metadata-reserved-space-setting.adoc[增加中繼資料保留空間設定]






== 維護程序與支援工具的增強功能

* *可以變更節點主控台密碼*。您現在可以使用Grid Manager來變更節點主控台密碼（*組態*>*存取控制*>*網格密碼*）。這些密碼用於使用SSH以「admin」身分登入節點、或是以VM/實體主控台連線的root使用者身分登入。請參閱 xref:../admin/change-node-console-password.adoc[變更節點主控台密碼]。
* *新物件存在檢查精靈*。您現在可以使用易於使用的物件存在檢查精靈（*維護*>*工作*>*物件存在檢查*）來驗證物件完整性、以取代前景驗證程序。新程序需要三分之一或更少的時間才能完成、並可同時驗證多個節點。請參閱 xref:../monitor/verifying-object-integrity.html[驗證物件完整性]。
* * EC重新平衡與EC修復工作的「預估完成時間」圖表*。您現在可以檢視目前EC重新平衡或EC修復工作的預估完成時間和完成百分比。
* *複寫資料修復的預估完成百分比*。您現在可以將「如何複寫修復狀態」選項新增至「重複配對資料」命令、以查看複寫修復的預估完成百分比。
+

IMPORTANT: 「如何複製修復狀態」選項可在StorageGRID 畫面上進行技術預覽。此功能正在開發中、傳回的值可能不正確或延遲。若要判斷修復是否完成、請繼續使用*「等待-全部*」、*「嘗試的維修」（XRPA *）和*「掃描期間—預估（XSCM）」*、如恢復程序所述。

* 診斷頁上的結果（* Support *>* Tools *>*診斷*）現在依嚴重性排序、然後依字母順序排列。
* Prometheus和Grafana已更新為更新版本、並已修改介面和圖表。隨著這項變更、部分指標中的標籤也有所變更。
+
** 如果您有使用「node_network_up」標籤的自訂查詢、您現在應該改用「node_network_info」標籤。
** 如果您也使用任何「node_network」指標的標籤名稱「interface」、現在您應該改用「device」標籤。


* 過去、Prometheus指標儲存在管理節點上31天。現在、在保留給Prometheus資料的空間已滿之前、將會儲存指標、這會大幅增加歷史指標的可用時間。
+
當/var/local/mysql_ibdata/'磁碟區達到容量時、最舊的度量會先刪除。





== 安裝增強功能

* 現在您可以在安裝Red Hat Enterprise Linux時、選擇使用Podman作為容器。先前StorageGRID 、僅支援Docker Container。
* 目前、StorageGRID RedHat Enterprise Linux/CentOS、Ubuntu / DEBIAN,和VMware平台的安裝歸檔中已包含API架構。擷取歸檔之後、您可以在「/Extras / API-Schemas」資料夾中找到架構。
* 用於裸機部署的節點組態檔中的「block_device_RANGEDB」金鑰現在應包含三位數、而非兩位數。也就是、您應該指定「block_device_RANGEDB_Nn」、而非「block_device_RANGEDB_Nnn」。
+
為了與現有部署相容、升級的節點仍支援兩位數金鑰。

* 您可以選擇性地將新的「連接埠」金鑰的一或多個執行個體新增至裸機部署的節點組態檔。每個金鑰都會提供裸機主機上實體介面的名稱和說明、這些介面會顯示在「VLAN介面」頁面和「HA群組」頁面上。
+
** xref:../rhel/creating-node-configuration-files.adoc[為Red Hat Enterprise Linux或CentOS部署建立節點組態檔案]
** xref:../ubuntu/creating-node-configuration-files.adoc[為Ubuntu或Debian部署建立節點組態檔案]






== 新警示

針對下列功能新增警示StorageGRID ：

* 稽核記錄正在新增至記憶體內的佇列
* Cassandra表格毀損
* EC重新平衡故障
* EC修復失敗
* EC修復停止
* S3和Swift API的全域伺服器憑證過期
* 外部syslog CA憑證過期
* 外部syslog用戶端憑證過期
* 外部syslog伺服器憑證過期
* 外部syslog伺服器轉送錯誤
* 租戶的身分識別聯盟同步處理失敗
* 偵測到舊版CLB負載平衡器活動
* 正在將記錄新增至磁碟上佇列
* 低唯讀浮水印會置換
* 低溫度目錄可用空間
* 物件存在檢查失敗
* 物件存在檢查停止
* S3將物件大小設得太大


請參閱 xref:../monitor/alerts-reference.adoc[警示參考資料]。



== 稽核訊息的變更

* ORLM：符合物件規則稽核訊息中新增了一個* BUID*欄位。「* BUID*」欄位會顯示用於內部作業的庫位ID。只有訊息狀態為PRGD時、才會顯示新欄位。
* 下列稽核訊息中新增了一個* SGRP *欄位。只有當物件被刪除的站台與擷取的站台不同時、才會顯示「* SGRP *」欄位。
+
** 表意：ILM啟動刪除
** OW寫入：物件覆寫
** SDEL：S3刪除
** WDEL：Swift刪除




請參閱 xref:../audit/index.adoc[檢閱稽核記錄]。



== 文件變更StorageGRID

更新版的《外觀與風格StorageGRID 》（外觀與風格）文件網站已經修改、現在使用GitHub做為基礎平台。

NetApp對內容的意見反應十分讚賞、並鼓勵使用者善用產品文件每一頁的全新「申請文件變更」功能。文件平台也為GitHub使用者提供內嵌內容貢獻功能。

請看一下、並對本文件做出貢獻。您可以編輯、申請變更、或只是傳送意見反應。
