---
permalink: ubuntu/planning-and-preparation.html 
sidebar: sidebar 
keywords: how to prepare for ubuntu or debian installation 
summary: 在部署網格節點及設定StorageGRID 資訊網格之前、您必須先熟悉完成程序的步驟和要求。 
---
= 安裝前（Ubuntu或DEBIAN1）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在部署網格節點及設定StorageGRID 資訊網格之前、您必須先熟悉完成程序的步驟和要求。

此功能的部署和組態程序假設您熟悉了整個過程的架構和操作。StorageGRID StorageGRID

您可以一次部署單一站台或多個站台、但是所有站台都必須符合至少三個儲存節點的最低需求。

在開始StorageGRID 執行安裝程序之前、您必須：

* 瞭解StorageGRID的運算需求、包括每個節點的最低CPU和RAM需求。
* 瞭解StorageGRID 為什麼支援多個網路來隔離流量、安全性和管理便利性、並規劃要連接到每StorageGRID 個節點的網路。
+
請參閱StorageGRID 《關於連網的指南》。

* 瞭解每種網格節點的儲存與效能需求。
* 識別一組伺服器（實體、虛擬或兩者）、這些伺服器集合在一起、提供足夠的資源來支援StorageGRID 您計畫部署的各個節點數量和類型。
* 如果您想在不中斷任何服務的情況下、於實體主機上執行排程維護、請瞭解節點移轉的需求。
* 事先收集所有網路資訊。除非您使用DHCP、否則請收集要指派給每個網格節點的IP位址、以及要使用的網域名稱系統（DNS）和網路時間傳輸協定（NTP）伺服器的IP位址。
* 安裝、連接及設定所有必要的硬體StorageGRID 、包括任何不符合規格的產品。
+

NOTE: 硬體專屬的安裝與整合說明並未包含在StorageGRID 安裝程序中。如需瞭StorageGRID 解如何安裝資訊設備、請參閱產品的安裝與維護說明。

* 決定您要使用哪些可用的部署和組態工具。


xref:../network/index.adoc[網路準則]

xref:../sg100-1000/index.adoc[SG100與SG1000服務應用裝置]

xref:../sg6000/index.adoc[SG6000儲存設備]

xref:../sg5700/index.adoc[SG5700儲存設備]

xref:../sg5600/index.adoc[SG5600儲存設備]

xref:node-container-migration-requirements.adoc[節點容器移轉需求]
