---
permalink: harden/other-hardening-guidelines.html 
sidebar: sidebar 
keywords: Hardening guidelines, security 
summary: 除了遵循StorageGRID 有關「不二網」和「節點」的強化準則、您還應遵循StorageGRID 「不二網」系統其他區域的強化準則。 
---
= 其他強化準則
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
除了遵循StorageGRID 有關「不二網」和「節點」的強化準則、您還應遵循StorageGRID 「不二網」系統其他區域的強化準則。



== 記錄與稽核訊息

請務必StorageGRID 以安全的方式保護不間斷記錄和稽核訊息輸出。從支援和系統可用度的觀點來看、支援記錄和稽核訊息可提供寶貴的資訊。StorageGRID此外StorageGRID 、包含在「資訊記錄」和「稽核訊息」輸出中的資訊和詳細資料、通常屬於敏感性質。

設定StorageGRID 將安全事件傳送至外部syslog伺服器。如果使用syslog匯出、請選取TLS和RELP/TLS做為傳輸傳輸傳輸傳輸傳輸傳輸協定。

如需StorageGRID 更多有關資訊、請參閱監控和疑難排解的指示。請參閱稽核訊息的指示、以取得StorageGRID 更多有關不景稽核訊息的資訊。



== NetApp AutoSupport

利用支援功能、您可以主動監控系統的健全狀況、並自動將訊息和詳細資料傳送給NetApp技術支援、貴組織的內部支援團隊或支援合作夥伴。AutoSupport StorageGRID根據預設、AutoSupport 第一次設定使用者支援時、會啟用向NetApp技術支援發出的功能性訊息StorageGRID 。

可停用此功能。AutoSupport不過、NetApp建議您啟用此功能、因為AutoSupport 當StorageGRID 您的作業系統發生問題時、支援使用支援功能來加速問題識別與解決。

支援HTTPS、HTTP和SMTP傳輸傳輸傳輸傳輸傳輸協定。AutoSupport由於資訊內容敏感、NetApp強烈建議使用HTTPS作為預設傳輸傳輸傳輸傳輸傳輸傳輸傳輸傳輸傳輸傳輸傳輸傳輸傳輸協定、以將資訊傳送給NetApp支援部門。AutoSupport AutoSupport

或者、您可以設定管理Proxy、以便更有效地控制AutoSupport 從管理節點到NetApp技術支援之間的各種通訊。如需管理StorageGRID 功能的說明、請參閱建立管理Proxy的步驟。



== 跨來源資源共享（CORS）

如果您想要讓其他網域中的Web應用程式能夠存取S3儲存區中的儲存區和物件、可以設定S3儲存區的跨來源資源共享（CORS）。一般而言、除非需要、否則請勿啟用CORS。如果需要CORS、請將其限制在信任的來源。

請參閱使用租戶帳戶說明中的「設定跨來源資源共用（CORS）的步驟」。



== 外部安全裝置

完整的強化解決方案必須能解決StorageGRID 不屬於其他功能的安全機制問題。使用額外的基礎架構裝置來篩選及限制StorageGRID 存取功能、是建立及維持嚴苛安全態勢的有效方法。這些外部安全裝置包括防火牆、入侵防禦系統（IPS）和其他安全裝置。

不受信任的用戶端流量建議使用協力廠商負載平衡器。第三方負載平衡可提供更多控制能力、並提供額外的層級保護、防止攻擊。

xref:../monitor/index.adoc[監控及疑難排解]

xref:../audit/index.adoc[檢閱稽核記錄]

xref:../tenant/index.adoc[使用租戶帳戶]

xref:../admin/index.adoc[管理StorageGRID]
