---
permalink: swift/get-container-consistency-request.html 
sidebar: sidebar 
keywords: get container consistency request 
summary: 一致性層級可在物件的可用度與不同儲存節點和站台之間的物件一致性之間進行權衡。「Get Container一致性」要求可讓您判斷要套用至特定容器的一致性層級。 
---
= 取得Container一致性要求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
一致性層級可在物件的可用度與不同儲存節點和站台之間的物件一致性之間進行權衡。「Get Container一致性」要求可讓您判斷要套用至特定容器的一致性層級。



== 申請

|===
| 要求HTTP標頭 | 說明 


 a| 
「X-AUTH-Token」
 a| 
指定要用於要求的帳戶Swift驗證權杖。



 a| 
《X-ntot-sg-consistency》
 a| 
指定要求類型、其中「true」=取得容器一致性、「false」= Get Container。



 a| 
「主機」
 a| 
要求導向的主機名稱。

|===


== 申請範例

[listing]
----
GET /v1/28544923908243208806/Swift container
X-Auth-Token: SGRD_3a877009a2d24cb1801587bfa9050f29
x-ntap-sg-consistency: true
Host: test.com
----


== 回應

|===
| 回應HTTP標頭 | 說明 


 a| 
'日期'
 a| 
回應的日期和時間。



 a| 
「連線」
 a| 
是否開啟或關閉與伺服器的連線。



 a| 
「X-trans-ID」
 a| 
要求的唯一交易識別碼。



 a| 
《內容長度》
 a| 
回應本文的長度。



 a| 
《X-ntot-sg-consistency》
 a| 
套用至容器的一致性控制層級。支援下列值：

* *全部*：所有節點都會立即接收資料、否則要求將會失敗。
* *強式全域*：保證所有站台所有用戶端要求的寫入後讀取一致性。
* * Strong站台*：保證站台內所有用戶端要求的寫入後讀取一致性。
* *新寫入後讀取*：提供新物件的寫入後讀取一致性、以及物件更新的最終一致性。提供高可用度與資料保護保證。
+
*附註*：如果您的應用程式在不存在的物件上使用標頭要求、如果一個或多個儲存節點無法使用、您可能會收到大量500個內部伺服器錯誤。若要避免這些錯誤、請使用「可用」層級。

* *可用*（最終的頭端作業一致性）：行為與「全新寫入後的讀取」一致性層級相同、但最終只能提供頭端作業的一致性。如果儲存節點無法使用、則頭端作業的可用度比「全新寫入後的準備」高。


|===


== 回應範例

[listing]
----
HTTP/1.1 204 No Content
Date: Sat, 29 Nov 2015 01:02:18 GMT
Connection: CLOSE
X-Trans-Id: 1936575373
Content-Length: 0
x-ntap-sg-consistency: strong-site
----
xref:../tenant/index.adoc[使用租戶帳戶]
