---
permalink: swift/object-operations.html 
sidebar: sidebar 
keywords: swift object operations 
summary: 下列Swift API作業會在物件上執行。 
---
= 物件作業
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
下列Swift API作業會在物件上執行。



== 刪除物件

此作業會從StorageGRID 作業系統刪除物件的內容和中繼資料。

需要下列要求參數：

* 「帳戶」
* 《Container》
* 「物件」


需要下列要求標頭：

* 「X-AUTH-Token」


成功執行會傳回下列回應標頭、並顯示「HTTP / 1.1 204無內容」回應：

* 《內容長度》
* 「內容類型」
* '日期'
* 「X-trans-ID」


處理刪除物件要求時StorageGRID 、功能區會嘗試立即從所有儲存位置移除物件的所有複本。如果成功、StorageGRID 則會立即將回應傳回給用戶端。如果無法在30秒內移除所有複本（例如、因為某個位置暫時無法使用）、StorageGRID 則將複本排入佇列以供移除、然後向用戶端指出成功。

如需如何刪除物件的詳細資訊、請參閱使用資訊生命週期管理來管理物件的指示。



== Get物件

此作業會擷取物件內容、並從StorageGRID 一套系統取得物件中繼資料。

需要下列要求參數：

* 「帳戶」
* 《Container》
* 「物件」


需要下列要求標頭：

* 「X-AUTH-Token」


以下是選用的要求標頭：

* 「Accept-編碼」
* 「如果符合」
* 「If-Modified、自...」
* 「如果-無-比對」
* 《如果沒有修改過的自此》
* 《範圍》


成功執行會傳回下列標頭、並顯示「HTTP / 1.1 200 OK」回應：

* 「Accept-Range-」
* 只有在設定「內容處理」中繼資料後、才會傳回「內容處理」
* 只有在設定了「內容編碼」中繼資料之後、才會傳回「內容編碼」
* 《內容長度》
* 「內容類型」
* '日期'
* 《ETag》
* 「上次修改日期」
* 「X-Timestamp'」
* 「X-trans-ID」




== 標頭物件

此作業會從StorageGRID 作業系統擷取擷取物件的中繼資料和屬性。

需要下列要求參數：

* 「帳戶」
* 《Container》
* 「物件」


需要下列要求標頭：

* 「X-AUTH-Token」


成功執行會傳回下列標頭、並顯示「HTTP / 1.1 200 OK」回應：

* 「Accept-Range-」
* 只有在設定「內容處理」中繼資料後、才會傳回「內容處理」
* 只有在設定了「內容編碼」中繼資料之後、才會傳回「內容編碼」
* 《內容長度》
* 「內容類型」
* '日期'
* 《ETag》
* 「上次修改日期」
* 「X-Timestamp'」
* 「X-trans-ID」




== 放置物件

此作業會以資料和中繼資料建立新物件、或以StorageGRID 資料和中繼資料取代現有物件。

支援最多5 TiB（5、497、558、13880位元組）的物件。StorageGRID


IMPORTANT: 衝突的用戶端要求（例如兩個寫入同一個金鑰的用戶端）會以「最新致勝」的方式解決。「最新致勝」評估的時間取決於StorageGRID VMware系統何時完成指定的要求、而非Swift用戶端何時開始作業。

需要下列要求參數：

* 「帳戶」
* 《Container》
* 「物件」


需要下列要求標頭：

* 「X-AUTH-Token」


以下是選用的要求標頭：

* 「內容處理」
* 「內容編碼」
+
如果適用於物件的ILM規則會根據大小來篩選物件、並在擷取時使用同步放置（擷取行為的平衡或嚴格選項）、請勿使用chunked「Content-Encoding」（內容編碼）。

* 「傳輸編碼」
+
如果適用於物件的ILM規則會根據大小來篩選物件、並在擷取時使用同步放置（擷取行為的平衡或嚴格選項）、則請勿使用壓縮或解開的「Transfer-Encoding」（傳輸編碼）。

* 《內容長度》
+
如果ILM規則會根據大小篩選物件、並在擷取時使用同步位置、則必須指定「Content-Length」（內容長度）。

+

NOTE: 如果您不遵守這些「內容編碼」、「傳輸編碼」和「內容長度」準則、StorageGRID 那麼在物件判斷物件大小並套用ILM規則之前、必須先儲存物件。換句話說StorageGRID 、在擷取時、必須預設使用功能來建立物件的過渡複本。也就是StorageGRID 、對於內嵌行為、必須使用雙重認可選項。

+
如需同步放置和ILM規則的詳細資訊、請參閱使用資訊生命週期管理來管理物件的指示。

* 「內容類型」
* 《ETag》
* 「X-Object-Meta-<name\>'（物件相關中繼資料）
+
如果您要使用*使用者定義的建立時間*選項做為ILM規則的參考時間、您必須將該值儲存在名為「X-Object-Meta-creation-Time」的使用者定義標頭中。例如：

+
[listing]
----
X-Object-Meta-Creation-Time: 1443399726
----
+
此欄位自1970年1月1日起計算為秒數。

* 「X-Storage-Class：縮減冗餘」
+
如果符合擷取物件的ILM規則指定「雙重認可」或「平衡」的擷取行為、則此標頭會影響StorageGRID 到所建立的物件複本數量。

+
** *雙重提交*：如果ILM規則指定擷取行為的雙重提交選項、StorageGRID 則會在擷取物件時建立單一的過渡複本（單一提交）。
** *平衡*：如果ILM規則指定平衡選項、StorageGRID 則僅當系統無法立即製作規則中指定的所有複本時、才能製作單一的過渡複本。如果能夠執行同步放置、則此標頭不會有任何影響。StorageGRID
+
當符合物件的ILM規則建立單一複寫複本時、最適合使用「已儲存的備援」標頭。在這種情況下、使用「reduced_dere通用」可免除每次擷取作業不必要地建立和刪除額外的物件複本。

+
在其他情況下、不建議使用「已儲存的備援」標頭、因為它會增加擷取期間物件資料遺失的風險。例如、如果單一複本一開始儲存在無法進行ILM評估的儲存節點上、則可能會遺失資料。

+

IMPORTANT: 在任何時間段只複寫一個複本、會使資料面臨永久遺失的風險。如果只有一個物件複寫複本存在、則當儲存節點故障或發生重大錯誤時、該物件就會遺失。在升級等維護程序期間、您也會暫時失去物件的存取權。



+
請注意、指定「已儲存的備援」僅會影響第一次擷取物件時所建立的複本數量。當物件由作用中的ILM原則評估時、不會影響物件的複本份數、也不會導致資料儲存在StorageGRID 較低層級的資料冗餘環境中。



成功執行會傳回下列標頭、並顯示「已建立的HTTP/1.1 201」回應：

* 《內容長度》
* 「內容類型」
* '日期'
* 《ETag》
* 「上次修改日期」
* 「X-trans-ID」


xref:../ilm/index.adoc[使用ILM管理物件]

xref:monitoring-and-auditing-operations.adoc[監控與稽核作業]
