---
permalink: network/index.html 
sidebar: sidebar 
keywords: storagegrid, network, networking, ethernet, subnet, routing 
summary: 請使用這些準則來瞭StorageGRID 解有關架構和網路拓撲的資訊、並瞭解網路組態和資源配置的需求。 
---
= 網路指南：概述
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
請使用這些準則來瞭StorageGRID 解有關架構和網路拓撲的資訊、並瞭解網路組態和資源配置的需求。



== 關於這些指示

這些準則提供您在StorageGRID 部署和設定StorageGRID 節點之前、可用來建立「資訊」網路基礎架構的資訊。使用這些準則有助於確保網格中的所有節點之間、網格與外部用戶端和服務之間都能進行通訊。

外部用戶端和外部服務需要連線StorageGRID 至無法分享的網路、才能執行下列功能：

* 儲存及擷取物件資料
* 接收電子郵件通知
* 存取StorageGRID 功能完善的管理介面（Grid Manager與Tenant Manager）
* 存取稽核共用區（選用）
* 提供下列服務：
+
** 網路時間傳輸協定（NTP）
** 網域名稱系統（DNS）
** 金鑰管理伺服器（KMS）




必須適當設定以處理這些功能及其他功能的流量。StorageGRID



== 開始之前

若要設定StorageGRID 適用於某個效能不穩定系統的網路功能、需要具備乙太網路交換、TCP/IP網路、子網路、網路路由和防火牆等豐富經驗。

在您設定網路之前、請先熟悉StorageGRID 中所述的功能 xref:../primer/index.adoc[網格入門指南]。

在您決定StorageGRID 要使用哪些靜態網路、以及如何設定這些網路之後、StorageGRID 您可以依照適當的指示來安裝和設定這些節點。

.安裝軟體型節點
* xref:../rhel/index.adoc[安裝Red Hat Enterprise Linux或CentOS]
* xref:../ubuntu/index.adoc[安裝Ubuntu或DEBIAN]
* xref:../vmware/index.adoc[安裝VMware]


.安裝應用裝置節點
* xref:../sg100-1000/index.adoc[SG100與SG1000服務應用裝置]
* xref:../sg6000/index.adoc[SG6000儲存設備]
* xref:../sg5700/index.adoc[SG5700儲存設備]
* xref:../sg5600/index.adoc[SG5600儲存設備]


.設定及管理StorageGRID 功能
* xref:../admin/index.adoc[管理StorageGRID]
* xref:../release-notes/index.adoc[版本資訊]

