---
permalink: network/network-specific-requirements.html 
sidebar: sidebar 
keywords: network-specific requirements, network specific requirements, network requirements 
summary: 請遵循StorageGRID 每種類型的需求。 
---
= 網路特定需求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
請遵循StorageGRID 每種類型的需求。



== 網路閘道和路由器

* 如果已設定、則指定網路的閘道必須位於特定網路的子網路內。
* 如果使用靜態定址設定介面、則必須指定0.00.0以外的閘道位址。
* 如果您沒有閘道、最佳做法是將閘道位址設定為網路介面的IP位址。




== 子網路


IMPORTANT: 每個網路都必須連線至自己的子網路、而不會與節點上的任何其他網路重疊。

下列限制會在部署期間由Grid Manager強制執行。此處提供這些工具、可協助您進行部署前的網路規劃。

* 任何網路IP位址的子網路遮罩不可為255．255．255或255．255．255（CIDR表示法為/31或/32）。
* 網路介面IP位址和子網路遮罩（CIDR）所定義的子網路、不能與同一個節點上所設定的任何其他介面的子網路重疊。
* 每個節點的Grid Network子網路必須包含在GNSL中。
* 管理網路子網路不能與Grid Network子網路、用戶端網路子網路或GNSL中的任何子網路重疊。
* Aesl中的子網路不能與GNSL中的任何子網路重疊。
* 用戶端網路子網路不能與Grid Network子網路、管理網路子網路、GNSL中的任何子網路或Aesl中的任何子網路重疊。




== 網格網路

* 在部署時、每個網格節點都必須附加至網格網路、而且必須能夠使用部署節點時指定的網路組態與主要管理節點通訊。
* 在正常的網格作業期間、每個網格節點都必須能夠透過網格網路與所有其他網格節點通訊。
+

NOTE: Grid Network必須在每個節點之間直接路由傳送。不支援節點之間的網路位址轉譯（NAT）。

* 如果網格網路由多個子網路組成、請將其新增至網格網路子網路清單（GNSL）。會在GNSL中的每個子網路的所有節點上建立靜態路由。
* 如果網格網路介面設定為主幹以支援VLAN介面、主幹原生VLAN必須是用於網格網路流量的VLAN。所有網格節點都必須透過主幹原生VLAN存取。




== 管理網路

管理網路為選用網路。如果您計畫設定管理網路、請遵循下列要求與準則。

管理網路的一般用途包括管理連線、AutoSupport 功能完善、KMS、連線至關鍵伺服器、例如NTP、DNS和LDAP、如果這些連線並非透過Grid Network或Client Network提供。


NOTE: 只要能夠連線所需的網路服務和用戶端、每個節點都可以使用管理網路和Aesl。


NOTE: 您必須在管理網路上定義至少一個子網路、才能啟用來自外部子網路的傳入連線。在Aesl的每個子網路中、會自動在每個節點上產生靜態路由。



== 用戶端網路

用戶端網路為選用項目。如果您打算設定用戶端網路、請注意下列考量事項。

* 用戶端網路的設計可支援來自S3和Swift用戶端的流量。如果已設定、用戶端網路閘道會成為節點的預設閘道。
* 如果您使用用戶端網路、StorageGRID 只有在明確設定的負載平衡器端點上接受傳入用戶端流量、才能保護不受惡意攻擊的可靠性。請參閱 xref:../admin/configuring-load-balancer-endpoints.adoc[設定負載平衡器端點]。
* 如果用戶端網路介面設定為主幹以支援VLAN介面、請考慮是否需要設定用戶端網路介面（eth2）。如果已設定、用戶端網路流量將會透過主幹原生VLAN（如交換器所設定）傳輸。

