---
permalink: sg5600/index.html 
sidebar: sidebar 
keywords: storagegrid, sg5600, storage node, storage appliance, overview, models, features 
summary: SSG5600應用裝置是整合式儲存與運算平台、StorageGRID 可在StorageGRID 整個網格中作為儲存節點運作。 
---
= SG5600應用裝置：總覽
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SSG5600應用裝置是整合式儲存與運算平台、StorageGRID 可在StorageGRID 整個網格中作為儲存節點運作。

此產品包含下列元件：StorageGRID

|===
| 元件 | 說明 


 a| 
E5600SG控制器
 a| 
運算伺服器E5600SG控制器可執行Linux作業系統和StorageGRID 支援功能的軟體。

此控制器連接至下列項目：

* 適用於整個系統的管理、網格和用戶端網路StorageGRID
* E2700控制器使用雙SAS路徑（主動/主動）、E5600SG控制器以啟動器的形式運作




 a| 
E2700控制器
 a| 
儲存控制器E2700控制器以單工模式作為標準E系列儲存陣列運作、並執行SANtricity 作業系統（控制器韌體）。

此控制器連接至下列項目：

* 安裝了NetApp Storage Manager的管理網路SANtricity
* E5600SG控制器、使用雙SAS路徑（主動/主動）、以E2700控制器作為目標運作


|===
SG5600應用裝置也包含下列元件、視機型而定：

|===
| 元件 | 型號SG5612 | 型號SG5660 


 a| 
磁碟機
 a| 
12個NL-SAS磁碟機
 a| 
60個NL-SAS磁碟機



 a| 
機箱
 a| 
DE1600機箱、兩個機架單元（2U）機箱、可容納磁碟機和控制器
 a| 
DE6600機箱、四個機架單元（4U）機箱、可容納磁碟機和控制器



 a| 
電源供應器與風扇
 a| 
兩個電源風扇迴廊
 a| 
兩個電源供應器和兩個風扇

|===

NOTE: E5600SG控制器經過高度客製化、可用於StorageGRID 整個產品。所有其他元件的運作方式如E系列文件所述、但本說明中所述者除外。

根據StorageGRID 應用裝置機型和組態、每個應用程式儲存節點上可用的最大原始儲存容量均已固定。您無法透過新增含有額外磁碟機的機櫃來擴充可用的儲存設備。
