= 
:allow-uri-read: 


[role="tabbed-block"]
====
.複寫資料
--
* 若要判斷維修是否完成：
+
.. 選擇*節點*>*要修復的儲存節點*>* ILM *。
.. 檢閱「評估」區段中的屬性。當修復完成時、「*等待-全部*」屬性會指出0個物件。


* 若要更詳細地監控維修：
+
.. 選取*支援*>*工具*>*網格拓撲*。
.. 選擇*網格_*>*要修復的儲存節點_*>* LdR*>*資料儲存*。
.. 請使用下列屬性組合來判斷複寫的修復是否完成、以及可能的情況。
+

NOTE: Cassandra可能存在不一致之處、而且無法追蹤失敗的修復。

+
*** *嘗試的維修（XRPA）*：使用此屬性來追蹤複寫的維修進度。每次儲存節點嘗試修復高風險物件時、此屬性都會增加。如果此屬性的增加時間不超過目前掃描期間（由*掃描期間-預估*屬性提供）、表示ILM掃描未發現任何需要在任何節點上修復的高風險物件。
+

NOTE: 高風險物件是可能完全遺失的物件。這不包括不符合ILM組態的物件。

*** *掃描期間-預估（XSCM）*：使用此屬性來預估原則變更何時會套用至先前擷取的物件。如果*已嘗試的維修*屬性在一段時間內沒有增加、則可能是因為複寫的維修已經完成。請注意、掃描期間可能會變更。「*掃描期間-預估（XSCM）*」屬性適用於整個網格、是所有節點掃描期間的上限。您可以查詢網格的*掃描期間-預估*屬性歷程記錄、以判斷適當的時間範圍。




* 或者、若要預估完成複寫修復的百分比、請在repair資料命令中新增「show複寫修復狀態」選項。
+
「重配對資料顯示複製的修復狀態」

+

IMPORTANT: 「如何複製修復狀態」選項可在StorageGRID 畫面上進行技術預覽。此功能正在開發中、傳回的值可能不正確或延遲。若要判斷修復是否完成、請使用*「等待–全部*」、*「嘗試的維修」（XRPA）*、以及*「掃描期間」-「預估（XSCM）」*、如所述 xref:..//maintain/restoring-object-data-to-storage-volume-where-system-drive-is-intact.adoc[監控維修]。



--
.銷毀編碼（EC）資料
--
若要監控銷毀編碼資料的修復、然後重試任何可能失敗的要求：

. 判斷銷毀編碼資料修復的狀態：
+
** 選取* support*>* Tools *>* Metrics *以檢視目前工作的預估完成時間和完成百分比。然後在Grafana區段中選取* EC Overview *。請參閱* Grid EC工作預估完成時間*和* Grid EC工作百分比已完成*儀表板。
** 使用此命令查看特定「資料配對」作業的狀態：
+
「成對資料顯示- EC-repair狀態-修復ID」

** 使用此命令列出所有修復：
+
「資料配對顯示- EC-repair狀態」

+
輸出會列出所有先前和目前執行中修復的資訊、包括「資源配對ID」。



. 如果輸出顯示修復作業失敗、請使用「-repair id」選項重試修復。
+
此命令會使用修復ID 6949309319275667690、重試失敗的節點修復：

+
「重新配對資料start-ec-node-repair --repair id 6949309319275667690」

+
此命令會使用修復ID 6949309319275667690重試失敗的Volume修復：

+
「重新配對資料啟動- EC-volume修復-修復ID 6949309319275667690」



--
====