= 尋找儲存節點的主機名稱
:allow-uri-read: 




== 尋找儲存節點的主機名稱

. 登入主要管理節點：
+
.. 輸入下列命令：「sh admin@_primary管理節點IP」
.. 輸入「passwords.txt」檔案中所列的密碼。
.. 輸入下列命令以切換至root：「u -」
.. 輸入「passwords.txt」檔案中所列的密碼。
+
以root登入時、提示會從「$」變更為「#」。



. 使用「/etc/hosts」檔案尋找還原儲存磁碟區的儲存節點主機名稱。若要查看網格中所有節點的清單、請輸入下列命令：「cat /etc/hosts」。




== 如果所有磁碟區都失敗、請修復資料

如果所有儲存磁碟區都發生故障、請修復整個節點。根據您使用的是複寫資料、銷毀編碼（EC）資料、或兩者、請遵循*複寫資料*、*銷毀編碼（EC）資料*的指示。

如果只有部分磁碟區發生故障、請前往 <<如果只有部分磁碟區發生故障、請修復資料>>。


IMPORTANT: 您無法同時對多個節點執行「重配對資料」作業。若要恢復多個節點、請聯絡技術支援部門。

[role="tabbed-block"]
====
.複寫資料
--
如果網格包含複寫資料、請使用「重新配對資料啟動複寫節點修復」命令搭配「節點」選項來修復整個儲存節點。

此命令可修復名為SG-DC-SN3之儲存節點上的複寫資料：

「重新配對資料開始複寫節點修復-節點SG-DC-SN3」


NOTE: 還原物件資料時、StorageGRID 如果無法找到複製的物件資料、就會觸發*物件遺失*警示。警示可能會在整個系統的儲存節點上觸發。您應該判斷遺失原因、以及是否有可能恢復。請參閱 xref:../monitor/index.adoc[監控及疑難排解]。

--
.銷毀編碼（EC）資料
--
如果您的網格含有銷毀編碼資料、請使用「重新配對資料start-ec-node-repair」命令搭配「-nodes」選項來修復整個儲存節點。

此命令可修復名為SG-DC-SN3之儲存節點上的銷毀編碼資料：

「重新配對資料啟動- EC-node-repair -節點SG-DC-SN3」

該作業會傳回唯一的「重新配對ID」、以識別此「重新配對資料」作業。使用此「配對ID」來追蹤「配對資料」作業的進度和結果。恢復程序完成時、不會傳回其他意見反應。


NOTE: 在某些儲存節點離線時、可以開始修復以銷毀編碼的資料。所有節點都可用後、修復作業即告完成。

--
====


== 如果只有部分磁碟區發生故障、請修復資料

如果只有部分磁碟區發生故障、請修復受影響的磁碟區。根據您使用的是複寫資料、銷毀編碼（EC）資料、或兩者、請遵循*複寫資料*、*銷毀編碼（EC）資料*的指示。

如果所有磁碟區都失敗、請前往 <<如果所有磁碟區都失敗、請修復資料>>。

以十六進位格式輸入Volume ID。例如、「0000」是第一個Volume、而「000F」是第16個Volume。您可以指定一個磁碟區、一個磁碟區範圍或多個未依序排列的磁碟區。

所有磁碟區都必須位於同一個儲存節點上。如果您需要還原多個儲存節點的磁碟區、請聯絡技術支援部門。

[role="tabbed-block"]
====
.複寫資料
--
如果網格包含複製的資料、請使用「Start（開始）- repl複 製- Volume（磁碟區）修復」命令搭配「-nodes（節點）」選項來識別節點。然後新增「-volume」或「-volume -range」選項、如下列範例所示。

*單一磁碟區*：此命令可將複寫的資料還原至名為SG-DC-SN3的儲存節點上的磁碟區「0002」：

「重新配對資料開始複寫磁碟區修復」-節點SG-DC-SN3 -磁碟區0002

*磁碟區範圍*：此命令可將複寫的資料還原至儲存節點SG-DC-SN3上「0003」到「0009」範圍內的所有磁碟區：

`repair-data start-replicated-volume-repair --nodes SG-DC-SN3 --volume-range 0003,0009`

*多個磁碟區未依序*：此命令可將複寫的資料還原至名為SG-DC-SN3的儲存節點上的磁碟區「0001」、「0005」和「0008」：

「重新配對資料開始複寫磁碟區修復」-節點SG-DC-SN3 -磁碟區0001、0005、0008


NOTE: 還原物件資料時、StorageGRID 如果無法找到複製的物件資料、就會觸發*物件遺失*警示。警示可能會在整個系統的儲存節點上觸發。您應該判斷遺失原因、以及是否有可能恢復。請參閱「監控StorageGRID 及疑難排解指令」。

--
.銷毀編碼（EC）資料
--
如果您的網格含有銷毀編碼資料、請使用「Start（開始）-EC-volume（磁碟區）修復」命令搭配「-nodes（節點）」選項來識別節點。然後新增「-volume」或「-volume -range」選項、如下列範例所示。

*單一磁碟區*：此命令可將銷毀編碼的資料還原至名為SG-DC-SN3的儲存節點上的Volume「0007」：

「重新配對資料啟動- EC-volume修復-節點SG-DC-SN3 - Volume 0007」

*磁碟區範圍*：此命令可將銷毀編碼資料還原至儲存節點SG-DC-SN3上「0004」至「0006」範圍內的所有磁碟區：

`repair-data start-ec-volume-repair --nodes SG-DC-SN3 --volume-range 0004,0006`

*多個磁碟區未依序*：此命令可將刪除編碼的資料還原至名為SG-DC-SN3的儲存節點上的磁碟區「000A」、「000C」和「000E」：

「重新配對資料啟動- EC-volume修復-節點SG-DC-SN3 - Volume 000A、000C、000E」

「重新配對資料」作業會傳回唯一的「重新配對ID」、以識別此「重新配對資料」作業。使用此「配對ID」來追蹤「配對資料」作業的進度和結果。恢復程序完成時、不會傳回其他意見反應。


NOTE: 在某些儲存節點離線時、可以開始修復以銷毀編碼的資料。所有節點都可用後、修復作業即告完成。

--
====