---
permalink: tenant/changing-consistency-level.html 
sidebar: sidebar 
keywords: how to change tenant consistency level, read after new write, read-after-new-write, strong site, strong-site, strong global, strong-global 
summary: 如果您使用的是S3租戶、則可以使用租戶管理程式或租戶管理API來變更在S3貯體中物件上執行的作業一致性控制。 
---
= 變更一致性層級
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您使用的是S3租戶、則可以使用租戶管理程式或租戶管理API來變更在S3貯體中物件上執行的作業一致性控制。

.您需要的產品
* 您必須使用登入租戶管理程式 xref:../admin/web-browser-requirements.adoc[支援的網頁瀏覽器]。
* 您必須屬於具有「管理所有庫位」或「根存取」權限的使用者群組。這些權限會覆寫群組或儲存區原則中的權限設定。請參閱 xref:tenant-management-permissions.adoc[租戶管理權限]。


.關於這項工作
一致性層級可在物件的可用度與這些物件在不同儲存節點和站台之間的一致性之間取得平衡。一般而言、您應該使用庫存箱的*新寫入後讀取*一致性層級。

如果*新寫入後讀取*一致性層級不符合用戶端應用程式的需求、您可以設定儲存區一致性層級或使用來變更一致性層級 `Consistency-Control` 標頭。。 `Consistency-Control` 標頭會覆寫貯體一致性層級。


NOTE: 當您變更桶的一致性層級時、只有變更後擷取的物件才保證符合修訂的層級。

.步驟
. 選擇*儲存設備（S3）*>*桶*。
. 從清單中選取儲存貯體名稱。
+
此時會顯示「庫位詳細資料」頁面。

. 選擇*庫位選項*>*一致性層級*。
. 針對此儲存區中的物件執行的作業、選取一致性層級。
+
** * 全部 * ：提供最高等級的一致性。所有節點都會立即接收資料、否則要求將會失敗。
** *Strong-globall* ：保證所有網站上所有用戶端要求的寫入後讀取一致性。
** *Strong-site* ：保證網站內所有用戶端要求的寫入後讀取一致性。
** * 新寫入後讀取 * （預設）：提供新物件的寫入後讀取一致性、以及物件更新的最終一致性。提供高可用度與資料保護保證。建議大多數情況下使用。
** * 可用 * ：提供新物件和物件更新的最終一致性。對於 S3 貯體、請僅視需要使用（例如、包含很少讀取的記錄值之貯體、或用於對不存在的金鑰執行 HEAD 或 GET 作業）。S3 FabricPool 儲存區不支援。


. 選取*儲存變更*。

