---
permalink: tenant/changing-consistency-level.html 
sidebar: sidebar 
keywords: how to change tenant consistency level, read after new write, read-after-new-write, strong site, strong-site, strong global, strong-global 
summary: 如果您使用的是S3租戶、則可以使用租戶管理程式或租戶管理API來變更在S3貯體中物件上執行的作業一致性控制。 
---
= 變更一致性層級
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您使用的是S3租戶、則可以使用租戶管理程式或租戶管理API來變更在S3貯體中物件上執行的作業一致性控制。

.您需要的產品
* 您必須使用登入租戶管理程式 xref:../admin/web-browser-requirements.adoc[支援的網頁瀏覽器]。
* 您必須屬於具有「管理所有庫位」或「根存取」權限的使用者群組。這些權限會覆寫群組或儲存區原則中的權限設定。請參閱 xref:tenant-management-permissions.adoc[租戶管理權限]。


.關於這項工作
一致性層級可在物件的可用度與不同儲存節點和站台之間的物件一致性之間進行權衡。一般而言、您應該使用庫存箱的*新寫入後讀取*一致性層級。如果*新寫入後讀取*一致性層級不符合用戶端應用程式的需求、您可以設定儲存庫一致性層級、或使用「一致性控制」標頭來變更一致性層級。「一致性控制」標頭會取代庫位一致性層級。


NOTE: 當您變更桶的一致性層級時、只有變更後擷取的物件才保證符合修訂的層級。

.步驟
. 選擇*儲存設備（S3）*>*桶*。
. 從清單中選取儲存貯體名稱。
+
此時會顯示「庫位詳細資料」頁面。

. 選擇*庫位選項*>*一致性層級*。
. 針對此儲存區中的物件執行的作業、選取一致性層級。
+
[cols="1a,3a"]
|===
| 一致性層級 | 說明 


 a| 
全部
 a| 
所有節點都會立即接收資料、否則要求將會失敗。



 a| 
強大的全球化技術
 a| 
保證所有站台所有用戶端要求的寫入後讀取一致性。



 a| 
強式網站
 a| 
保證站台內所有用戶端要求的寫入後讀取一致性。



 a| 
讀取後新寫入（預設）
 a| 
為新物件提供寫入後讀取一致性、並最終確保物件更新一致。提供高可用度與資料保護保證。最符合Amazon S3一致性保證。

*附註：*如果您的應用程式嘗試針對不存在的金鑰執行作業、請將一致性層級設為*可用*、除非您需要Amazon S3一致性保證。否則、如果一個或多個儲存節點無法使用、可能會導致500個內部伺服器錯誤。



 a| 
可用（最終一致的主管或Get作業）
 a| 
其行為與*新寫入後讀取*一致性層級相同、但最終可提供一致的標頭與取得作業。如果儲存節點無法使用、則可提供比*讀取後新寫入*更高的標頭可用度及取得作業。不同於Amazon S3一致性保證、可確保使用者執行作業。

|===
. 選取*儲存變更*。

