---
permalink: tenant/managing-groups.html 
sidebar: sidebar 
keywords: how to manage groups 
summary: 您可以指派權限給使用者群組、以控制租戶使用者可以執行的工作。您可以從身分識別來源（例如Active Directory或OpenLDAP）匯入聯盟群組、也可以建立本機群組。 
---
= 管理群組
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以指派權限給使用者群組、以控制租戶使用者可以執行的工作。您可以從身分識別來源（例如Active Directory或OpenLDAP）匯入聯盟群組、也可以建立本機群組。


IMPORTANT: 如果StorageGRID 您的系統啟用單一登入（SSO）、則本機使用者將無法登入租戶管理程式、不過他們可以根據群組權限來存取S3和Swift資源。



== 租戶管理權限

建立租戶群組之前、請先考量您要指派給該群組的權限。租戶管理權限可決定使用者可以使用租戶管理程式或租戶管理API執行哪些工作。使用者可以屬於一或多個群組。如果使用者屬於多個群組、則權限是累積性的。

若要登入租戶管理程式或使用租戶管理API、使用者必須屬於至少擁有一項權限的群組。所有可以登入的使用者都可以執行下列工作：

* 檢視儀表板
* 變更自己的密碼（適用於本機使用者）


對於所有權限、群組的存取模式設定會決定使用者是否可以變更設定及執行作業、或是只能檢視相關設定和功能。


NOTE: 如果使用者屬於多個群組、且任何群組設定為唯讀、則使用者將擁有所有選取設定和功能的唯讀存取權。

您可以將下列權限指派給群組。請注意、S3租戶和Swift租戶擁有不同的群組權限。由於快取、變更可能需要15分鐘才能生效。

[cols="1a,3a"]
|===
| 權限 | 說明 


 a| 
root存取權
 a| 
提供租戶管理程式和租戶管理API的完整存取權限。

*附註：* Swift使用者必須擁有root存取權限、才能登入租戶帳戶。



 a| 
系統管理員
 a| 
僅限Swift租戶。提供此租戶帳戶的Swift容器和物件的完整存取權

*附註：* Swift使用者必須擁有Swift管理員權限、才能使用Swift REST API執行任何作業。



 a| 
管理您自己的S3認證
 a| 
僅限S3租戶。可讓使用者建立及移除自己的S3存取金鑰。沒有此權限的使用者不會看到*儲存設備（S3）*>*我的S3存取金鑰*功能表選項。



 a| 
管理所有的儲存區
 a| 
* S3租戶：可讓使用者使用租戶管理程式和租戶管理API來建立及刪除S3桶、並管理租戶帳戶中所有S3桶的設定、無論S3桶或群組原則為何。
+
沒有此權限的使用者將不會看到「*桶*」功能表選項。

* Swift租戶：可讓Swift使用者使用租戶管理API來控制Swift Container的一致性層級。


*附註：*您只能從租戶管理API將「管理所有桶」權限指派給Swift群組。您無法使用租戶管理程式將此權限指派給Swift群組。



 a| 
管理端點
 a| 
僅限S3租戶。可讓使用者使用租戶管理程式或租戶管理API來建立或編輯端點、這些端點是StorageGRID 用作支援不整平台服務的目的地。

沒有此權限的使用者不會看到*平台服務端點*功能表選項。

|===
xref:../s3/index.adoc[使用S3]

xref:../swift/index.adoc[使用Swift]
