---
permalink: tenant/what-platform-services-are.html 
sidebar: sidebar 
keywords: what are platform services 
summary: 支援各種平台服務、協助您實作混合雲策略。StorageGRID 
---
= 什麼是平台服務？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
支援各種平台服務、協助您實作混合雲策略。StorageGRID

如果您的租戶帳戶允許使用平台服務、您可以針對任何S3儲存區設定下列服務：

* * CloudMirror複寫* xref:understanding-cloudmirror-replication-service.adoc[CloudMirror複寫服務StorageGRID] 用於將特定物件從StorageGRID 靜止庫鏡射到指定的外部目的地。
+
例如、您可以使用CloudMirror複寫將特定的客戶記錄鏡射到Amazon S3、然後利用AWS服務對資料執行分析。

+

NOTE: 如果來源儲存區已啟用S3物件鎖定、則不支援CloudMirror複寫。

* *通知*： xref:understanding-notifications-for-buckets.adoc[每桶活動通知] 用於將物件執行特定動作的通知傳送至指定的外部Amazon Simple Notification Service™（SNS）。
+
例如、您可以設定要傳送警示給系統管理員、以通知新增至儲存區的每個物件、其中物件代表與重大系統事件相關的記錄檔。

+

NOTE: 雖然事件通知可在已啟用S3物件鎖定的儲存區上設定、但通知訊息中不會包含物件的S3物件鎖定中繼資料（包括「保留直到日期」和「法定保留」狀態）。

* *搜尋整合服務* xref:understanding-search-integration-service.adoc[搜尋整合服務] 用於將S3物件中繼資料傳送至指定的Elasticsearch索引、以便使用外部服務搜尋或分析中繼資料。
+
例如、您可以設定儲存區、將S3物件中繼資料傳送至遠端Elasticsearch服務。然後您可以使用Elasticsearch來執行跨儲存區的搜尋、並對物件中繼資料中的模式進行精密分析。

+

NOTE: 雖然可在啟用S3物件鎖定的儲存區上設定Elasticsearch整合、但通知訊息中不會包含物件的S3物件鎖定中繼資料（包括「保留直到日期」和「法定保留」狀態）。



由於平台服務的目標位置通常是StorageGRID 不受您的支援、因此平台服務可讓您靈活運用外部儲存資源、通知服務、以及搜尋或分析資料服務。

任何平台服務組合都可設定為單一S3儲存區。例如、您可以在StorageGRID S3儲存區上設定CloudMirror服務和通知、以便將特定物件鏡射至Amazon Simple Storage Service、同時將每個物件的通知傳送至協力廠商監控應用程式、以協助您追蹤AWS費用。


IMPORTANT: 每個租戶帳戶必須由StorageGRID 使用Grid Manager或Grid Management API的管理員啟用平台服務的使用。



== 平台服務的設定方式

平台服務會與您使用租戶管理程式或租戶管理API設定的外部端點通訊。每個端點都代表一個外部目的地、例如StorageGRID 一個不支援的S3儲存區、一個Amazon Web Services儲存區、一個簡單通知服務（SNS）主題、或是在本機、AWS或其他地方代管的Elasticsearch叢集。

建立端點之後、您可以將XML組態新增至儲存區、為儲存區啟用平台服務。XML組態可識別儲存區應執行的物件、儲存區應採取的動作、以及儲存區應用於服務的端點。

您必須為每個要設定的平台服務新增個別的XML組態。例如：

. 如果您想要將金鑰以「/images/映 像」開頭的所有物件複寫到Amazon S3儲存區、則必須將複寫組態新增至來源儲存區。
. 如果您也想要在這些物件儲存至儲存區時傳送通知、則必須新增通知組態。
. 最後、如果您要為這些物件的中繼資料建立索引、則必須新增用於實作搜尋整合的中繼資料通知組態。


組態XML的格式受用於實作StorageGRID 支援功能的S3 REST API所規範：

[cols="1a,2a"]
|===
| 平台服務 | S3 REST API 


 a| 
CloudMirror複寫
 a| 
* 取得庫位複寫
* 放入資源桶複寫




 a| 
通知
 a| 
* 取得庫存箱通知
* 放置時段通知




 a| 
搜尋整合
 a| 
* 取得Bucket中繼資料通知組態
* 放置時段中繼資料通知組態


這些作業是根據StorageGRID 需求量身打造的。

|===
請參閱實作S3用戶端應用程式的指示、以取得StorageGRID 有關如何實作這些API的詳細資訊。

.相關資訊
xref:considerations-for-using-platform-services.adoc[使用平台服務的考量]

xref:../s3/index.adoc[使用S3]
