---
permalink: vmware/troubleshooting-installation-issues.html 
sidebar: sidebar 
keywords: how to troubleshoot installation issues 
summary: 如果在安裝StorageGRID 您的作業系統時發生任何問題、您可以存取安裝記錄檔。 
---
= 疑難排解安裝問題
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果在安裝StorageGRID 您的作業系統時發生任何問題、您可以存取安裝記錄檔。

以下是主要的安裝記錄檔、可能需要技術支援才能解決問題。

* /var/local/log/install.log（可在所有網格節點上找到）
* /var/local/log/gdu-server.log（位於主管理節點上）


若要瞭解如何存取記錄檔、請參閱 xref:../monitor/index.adoc[監控及疑難排解StorageGRID 的說明]。如需疑難排解應用裝置安裝問題的說明、請參閱應用裝置的安裝與維護說明。如果您需要其他協助、請聯絡技術支援部門。

xref:../sg100-1000/index.adoc[SG100與SG1000服務應用裝置]

xref:../sg6000/index.adoc[SG6000儲存設備]

xref:../sg5700/index.adoc[SG5700儲存設備]

xref:../sg5600/index.adoc[SG5600儲存設備]

https://mysupport.netapp.com/site/global/dashboard["NetApp支援"^]



== 虛擬機器資源保留需要調整

OVF檔案包含一項資源保留、旨在確保每個網格節點都有足夠的RAM和CPU、以有效運作。如果您在VMware上部署這些OVF檔案來建立虛擬機器、且預先定義的資源數量無法使用、則虛擬機器將不會啟動。

如果您確定VM主機有足夠的資源可用於每個網格節點、請手動調整每個虛擬機器的資源配置、然後嘗試啟動虛擬機器。

.步驟
. 在VMware vSphere Hypervisor用戶端樹狀結構中、選取尚未啟動的虛擬機器。
. 以滑鼠右鍵按一下虛擬機器、然後選取*編輯設定*。
. 從Virtual Machines Properties（虛擬機屬性）窗口中，選擇* Resources（資源）*選項卡。
. 調整分配給虛擬機器的資源：
+
.. 選取「* CPU*」、然後使用「保留」滑桿來調整保留給此虛擬機器的MHz。
.. 選取*記憶體*、然後使用保留滑桿調整此虛擬機器保留的MB。


. 按一下「*確定*」。
. 視需要重複相同VM主機上裝載的其他虛擬機器。

