---
permalink: admin/configuring-client-connections.html 
sidebar: sidebar 
keywords: s3 connection, swift connection, connect to storagegrid 
summary: 身為網格管理員、您可以管理組態選項、以控制S3和Swift租戶如何將用戶端應用程式連線至StorageGRID 您的作業系統、以儲存和擷取資料。有許多不同的選項可滿足不同的用戶端和租戶需求。 
---
= 關於S3和Swift用戶端連線
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
身為網格管理員、您可以管理組態選項、以控制S3和Swift租戶如何將用戶端應用程式連線至StorageGRID 您的作業系統、以儲存和擷取資料。有許多不同的選項可滿足不同的用戶端和租戶需求。

用戶端應用程式可連線至下列任一項目、以儲存或擷取物件：

* 管理節點或閘道節點上的負載平衡器服務、或是管理節點或閘道節點之高可用度（HA）群組的虛擬IP位址（可選）
* 閘道節點上的CLB服務、或是閘道節點高可用度群組的虛擬IP位址（可選）
+

NOTE: CLB服務已過時。在發佈版推出之前設定的用戶端StorageGRID 、可以繼續在閘道節點上使用CLB服務。所有其他仰賴StorageGRID 以提供負載平衡的用戶端應用程式、都應該使用負載平衡器服務進行連線。

* 儲存節點、無論是否有外部負載平衡器


您可以選擇在StorageGRID 您的作業系統上設定下列功能：

* * VLAN介面*：您可以在管理節點和閘道節點上建立虛擬LAN（VLAN）介面、以隔離及分割用戶端和租戶流量、以確保安全性、靈活度和效能。建立VLAN介面之後、您可以將其新增至高可用度（HA）群組。
* *高可用度群組*：您可以為閘道節點或管理節點建立介面的HA群組、以建立主動備份組態、也可以使用循環DNS或協力廠商負載平衡器及多個HA群組、來達成主動-主動式組態。用戶端連線是使用HA群組的虛擬IP位址進行。
* *負載平衡器服務*：您可以建立用戶端連線的負載平衡器端點、讓用戶端使用負載平衡器服務。建立負載平衡器端點時、請指定連接埠編號、端點是否接受HTTP或HTTPS連線、使用端點的用戶端類型（S3或Swift）、以及用於HTTPS連線的憑證（若適用）。
* *不受信任的用戶端網路*：您可以將用戶端網路設定為不受信任、使其更安全。當用戶端網路不受信任時、用戶端只能使用負載平衡器端點進行連線。


您也可以針對直接連線StorageGRID 至儲存節點或使用CLB服務（已過時）的用戶端、啟用HTTP、並可為S3用戶端設定S3 API端點網域名稱。
