---
permalink: admin/creating-and-activating-domain-policy.html 
sidebar: sidebar 
keywords: domain policy for tsm, tivoli storage manager policy 
summary: 您必須建立網域原則、然後啟動該原則、以設定TSM伺服器來儲存從歸檔節點傳送的資料。 
---
= 建立及啟動網域原則
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必須建立網域原則、然後啟動該原則、以設定TSM伺服器來儲存從歸檔節點傳送的資料。

.步驟
. 建立網域原則。
+
「複製網域標準TSM網域」

. 如果您不使用現有的管理類別、請輸入下列其中一項：
+
「定義政策集TSM網域標準」

+
「定義mgmtClass TSM網域標準_預設_」

+
缺省管理級別是部署的缺省管理級別。

. 建立複本群組至適當的儲存資源池。輸入（一行）：
+
"Define copygroup TSM網域標準_default_type=archive ditation=SGWSDiskPool retinit=Event retmin=0（定義複本群組TSM網域標準_預設_類型=歸檔目的地= SGWSDiskPool retinit=0）"

+
缺省管理類是歸檔節點的缺省管理類。選擇了"retinit"、"retmin"和"retver"等值、以反映歸檔節點目前使用的保留行為

+

NOTE: 請勿將「重複」設為「重複=建立」。由於保留事件是用來從TSM伺服器移除內容、因此設定「retinit =create」會封鎖歸檔節點刪除內容。

. 將管理類別指派為預設類別。
+
「指派defmgmtClass _tsm-domain_標準_default_'

. 將新原則集設為作用中。
+
「啟動policySet TSM網域標準」

+
請忽略輸入activate命令時出現的「no copy group」警告。

. 註冊節點以使用TSM伺服器上的新原則集。在TSM伺服器上、輸入（一行）：
+
「移除節點arcus-user arc-passwordpassexp = 0 domain=TSM-DOMAXnucm=number-of工作階段」

+
ARC-使用者和ARC-密碼與您在歸檔節點上定義的用戶端節點名稱和密碼相同、MAXNUMMP的值設定為保留給歸檔節點儲存工作階段的磁帶機數量。

+

NOTE: 根據預設、登錄節點會建立用戶端擁有者授權的管理使用者ID、並為節點定義密碼。


