---
permalink: admin/defining-tsm-tape-and-disk-storage-pools.html 
sidebar: sidebar 
keywords: archive node, tsm, tape storage pool, tivoli storage manager 
summary: 歸檔節點會寫入磁碟儲存池。若要將內容歸檔至磁帶、您必須設定磁碟儲存資源池、將內容移至磁帶儲存資源池。 
---
= 定義TSM磁帶與磁碟儲存資源池
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
歸檔節點會寫入磁碟儲存池。若要將內容歸檔至磁帶、您必須設定磁碟儲存資源池、將內容移至磁帶儲存資源池。

對於TSM伺服器、您必須在Tivoli Storage Manager中定義磁帶儲存資源池和磁碟儲存資源池。定義磁碟集區之後、請建立磁碟磁碟區並將其指派給磁碟集區。如果TSM伺服器使用純磁碟儲存設備、則不需要磁帶集區。

您必須在TSM伺服器上完成許多步驟、才能建立磁帶儲存池。（在磁帶庫中建立磁帶庫和至少一個磁碟機。定義從伺服器到程式庫、從伺服器到磁碟機的路徑、然後定義磁碟機的裝置類別。） 這些步驟的詳細資料可能會因站台的硬體組態和儲存需求而有所不同。如需詳細資訊、請參閱TSM文件。

下列一組指示說明此程序。您應該注意、站台的需求可能會因部署需求而異。如需組態詳細資料和說明、請參閱TSM文件。


NOTE: 您必須以系統管理權限登入伺服器、然後使用dsmadmc工具執行下列命令。

.步驟
. 建立磁帶庫。
+
"Define庫_Tapelibstite_libtype=_scsi_"

+
其中，"_tapelibinity_"是磁帶庫的任意名稱，而"libtype"的值則視磁帶庫類型而定。

. 定義從伺服器到磁帶庫的路徑。
+
"Define path _servername Tapelibstation_ srctype=server desttype=libraryDEVICE =_lib-devicName_"

+
** 「伺服器名稱」是TSM伺服器的名稱
** 「_tapeliiliinfort_」是您定義的磁帶庫名稱
** 「_lib-devicenam__」是磁帶庫的裝置名稱


. 定義程式庫的磁碟機。
+
「磁碟機_磁帶庫_磁碟機名稱_」

+
** "_drivename_"是您要為磁碟機指定的名稱
** 「_tapeliiliinfort_」是您定義的磁帶庫名稱
+
視硬體組態而定、您可能需要設定其他磁碟機。（例如、如果TSM伺服器連接至光纖通道交換器、且該交換器具有磁帶庫的兩個輸入、您可能會想要為每個輸入定義一個磁碟機。）



. 定義從伺服器到所定義磁碟機的路徑。
+
"Define path _servernames_ drivename srcty=server desttype=drive library=_tapeliablestation_設備=_drive-dname_"

+
** 「_drive-dname_」是磁碟機的裝置名稱
** 「_tapeliiliinfort_」是您定義的磁帶庫名稱
+
對您為磁帶庫定義的每個磁碟機重複上述步驟、每個磁碟機都使用單獨的「_drivename__」和「_drive-dname_」。



. 定義磁碟機的裝置類別。
+
"Define devClass _Device類Name_ devtype=_lto庫=_tapeliationstation_ format =_tapetype_"

+
** 「_Device類別名稱」是裝置類別的名稱
** 「_lto」是連接至伺服器的磁碟機類型
** 「_tapeliiliinfort_」是您定義的磁帶庫名稱
** 「_tapetype_」是磁帶類型、例如ultum3


. 將磁帶磁碟區新增至磁帶庫的庫存。
+
"簽 入libvolume _tapelibsta_"

+
「_tapeliiliinfort_」是您定義的磁帶庫名稱。

. 建立主要磁帶儲存資源池。
+
"Define stgpool _SGWSTapepool__Device類Name_ description___collocat=filespace_ mastScature=_XX_"

+
** 「_SGWSTapePool」是歸檔節點的磁帶儲存池名稱。您可以為磁帶儲存資源池選取任何名稱（只要名稱使用TSM伺服器所預期的語法慣例）。
** 「_Device Class Name_」是磁帶庫的裝置類別名稱。
** 「_description_」是使用「query stgpool」命令顯示在TSM伺服器上的儲存資源池說明。例如：「適用於歸檔節點的磁帶儲存池。」
** "_collocat=filspace_"指定TSM伺服器應將相同檔案空間的物件寫入單一磁帶。
** 「XX」是下列其中一項：
+
*** 磁帶庫中的空白磁帶數（如果歸檔節點是唯一使用磁帶庫的應用程式）。
*** 分配給StorageGRID 由該系統使用的磁帶數量（在共享磁帶庫的情況下）。




. 在TSM伺服器上、建立磁碟儲存資源池。在TSM伺服器的管理主控台輸入
+
"Define stgpool _SGWSDiskPool_ disk description=_description_最大大小=_Maximum_file_size nextstgpool = SGWSTapepool_ highmig=_center_high__ Lowmig=_center_Low_"

+
** 「SGWSDiskPool」是歸檔節點的磁碟集區名稱。您可以為磁碟儲存資源池選取任何名稱（只要名稱使用TSM預期的語法慣例）。
** 「_description_」是使用「query stgpool」命令顯示在TSM伺服器上的儲存資源池說明。例如、「為歸檔節點建立儲存資源池」。
** 「_imize_file_Size_」會強制將大於此大小的物件直接寫入磁帶、而非快取到磁碟集區。建議將「_imize_file_Size_」設為10 GB。
** nextstgPool=SGWSTapePool_'是指磁碟儲存資源池與為歸檔節點定義的磁帶儲存資源池。
** 「_同 百分比_high」設定磁碟集區開始將其內容移轉到磁帶集區的值。建議將「_百分_high」設為0、以便立即開始資料移轉
** 「_同 百分比_low」會設定移轉至磁帶集區的停止值。建議將「_同 百分比_low」設為0以清除磁碟集區。


. 在TSM伺服器上、建立磁碟磁碟區（或磁碟區）並將其指派給磁碟集區。
+
"Define volume _SGWSDiskPool _ Volume名稱_ format Size=_Size_（磁碟區大小_）"

+
** 「SGWSDiskPool」是磁碟集區名稱。
** 「Volume名稱」是TSM伺服器上磁碟區位置的完整路徑（例如、「/var/local/ars/stage6.DSM」）、其會寫入磁碟集區的內容、以準備傳輸至磁帶。
** 「_Size_」是磁碟區的大小（以MB為單位）。
+
例如、若要建立單一磁碟區、使磁碟集區的內容填滿單一磁帶、請在磁帶磁碟區的容量為200 GB時、將大小值設為200000。

+
不過、可能需要建立大小較小的多個磁碟區、因為TSM伺服器可以寫入磁碟集區中的每個磁碟區。例如、如果磁帶大小為250 GB、請建立25個磁碟區、每個磁碟區大小為10 GB（10000）。

+
TSM伺服器會預先配置磁碟區目錄中的空間。這可能需要一段時間才能完成（200 GB磁碟區的時間超過三小時）。




