---
permalink: admin/grid-management-api-operations.html 
sidebar: sidebar 
keywords: Grid Management API,  API operations 
summary: Grid Management API會將可用的API作業組織到下列各節。 
---
= 網格管理API作業
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Grid Management API會將可用的作業組織到下列各節中。


NOTE: 此清單僅包含公用API中可用的作業。

* *帳戶*：管理儲存租戶帳戶的作業、包括建立新帳戶及擷取特定帳戶的儲存使用量。
* *警示*：列出目前警示（舊系統）的作業、並傳回有關網格健全狀況的資訊、包括目前警示和節點連線狀態摘要。
* *警示歷史記錄*-已解決警示的作業。
* *警示接收器*-警示通知接收器（電子郵件）上的作業。
* *警示規則*-警示規則上的作業。
* *警示靜音*-警示靜音作業。
* *警示*：警示操作。
* *稽核*-列出及更新稽核組態的作業。
* *驗證*：執行使用者工作階段驗證的作業。
+
Grid Management API支援承載權杖驗證方案。若要登入、您必須在驗證要求的Json實體中提供使用者名稱和密碼（也就是「POST /API/v3/授權」）。如果使用者已成功驗證、則會傳回安全性權杖。此權杖必須在後續API要求的標頭中提供（「授權：bear_tokon_」）。

+

NOTE: 如果StorageGRID 啟用了單一登入功能、您必須執行不同的驗證步驟。請參閱「若啟用單一登入、則驗證API」。

+
請參閱「防範跨網站要求偽造」、以取得改善驗證安全性的資訊。

* *用戶端-憑證*-作業設定用戶端憑證、以便StorageGRID 使用外部監控工具安全存取。
* *組態*-與Grid Management API產品版本相關的作業。您可以列出該版本所支援的產品版本和Grid Management API主要版本、也可以停用已過時的API版本。
* *停用功能*-檢視可能已停用之功能的作業。
* * DNS伺服器*：列出及變更已設定外部DNS伺服器的作業。
* *端點-網域名稱*-列出及變更端點網域名稱的作業。
* *銷毀編碼*-刪除編碼設定檔的作業。
* *擴充*：擴充作業（程序層級）。
* *擴充節點*-擴充作業（節點層級）。
* *擴充站台*-擴充作業（站台層級）。
* *網格網路*-列出及變更網格網路清單的作業。
* *網格密碼*-網格密碼管理作業。
* *群組*：管理本機Grid系統管理員群組的作業、以及從外部LDAP伺服器擷取聯盟Grid系統管理員群組。
* *身分識別來源*-作業：設定外部身分識別來源、以及手動同步處理聯盟群組與使用者資訊。
* * ILM *-資訊生命週期管理（ILM）的營運。
* *授權*-擷取StorageGRID 及更新此功能的作業。
* *記錄*：收集及下載記錄檔的作業。
* *指標*：StorageGRID 針對包括即時度量查詢在單一時間點進行的運算、以及在一段時間內進行的範圍度量查詢。Grid Management API使用Prometheus系統監控工具作為後端資料來源。如需建構Prometheus查詢的相關資訊、請參閱Prometheus網站。
+

NOTE: 名稱中包含「_Private」的指標僅供內部使用。這些指標可能會在StorageGRID 不另行通知的情況下於各個版本之間變更。

* *節點詳細資料*-節點詳細資料上的作業。
* *節點健全狀況*-節點健全狀況狀態的作業。
* * ntp伺服器*-列出或更新外部網路時間傳輸協定（NTP）伺服器的作業。
* *物件*-物件和物件中繼資料的作業。
* *恢復*-恢復程序的作業。
* *恢復套件*-下載恢復套件的作業。
* *地區*-檢視及建立區域的作業。
* * S3物件鎖定*-全域S3物件鎖定設定的作業。
* *伺服器認證*-檢視及更新Grid Manager伺服器認證的作業。
* * SNMP *-目前SNMP組態上的作業。
* *流量類別*-流量分類原則的作業。
* *不受信任的用戶端網路*：不受信任的用戶端網路組態上的作業。
* *使用者*-檢視及管理Grid Manager使用者的作業。

