---
permalink: admin/how-load-balancing-works-load-balancer-service.html 
sidebar: sidebar 
keywords: load balancer service, how load balancing works 
summary: 負載平衡器服務會將傳入的網路連線從用戶端應用程式分散到儲存節點。若要啟用負載平衡、您必須使用Grid Manager來設定負載平衡器端點。 
---
= 負載平衡的運作方式-負載平衡器服務
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
負載平衡器服務會將傳入的網路連線從用戶端應用程式分散到儲存節點。若要啟用負載平衡、您必須使用Grid Manager來設定負載平衡器端點。

您只能為管理節點或閘道節點設定負載平衡器端點、因為這些節點類型包含負載平衡器服務。您無法設定儲存節點或歸檔節點的端點。

每個負載平衡器端點都會指定連接埠、網路傳輸協定（HTTP或HTTPS）、用戶端類型（S3或Swift）和繫結模式。HTTPS端點需要伺服器憑證。連結模式可讓您將端點連接埠的存取限制為：

* 特定高可用度（HA）群組的虛擬IP位址（VIP）
* 特定管理和閘道節點的特定網路介面




== 連接埠考量

用戶端可以存取您在任何執行負載平衡器服務的節點上設定的任何端點、但有兩個例外：管理節點上保留連接埠80和443、因此這些連接埠上設定的端點僅支援閘道節點上的負載平衡作業。

如果您已重新對應任何連接埠、則無法使用相同的連接埠來設定負載平衡器端點。您可以使用重新對應的連接埠來建立端點、但這些端點會重新對應至原始CLB連接埠和服務、而非負載平衡器服務。請依照中的步驟進行 xref:../maintain/removing-port-remaps.adoc[移除連接埠重新對應]。


NOTE: CLB服務已過時。



== CPU可用度

將S3或Swift流量轉送至儲存節點時、每個管理節點和閘道節點上的負載平衡器服務都會獨立運作。透過加權程序、負載平衡器服務會將更多要求路由傳送至CPU可用度較高的儲存節點。節點CPU負載資訊會每隔幾分鐘更新一次、但加權可能會更頻繁地更新。所有儲存節點都會被指派最低的基本權重值、即使節點回報100%使用率或無法報告使用率亦然。

在某些情況下、CPU可用度的相關資訊僅限於負載平衡器服務所在的站台。
