---
permalink: admin/managing-traffic-classification-policies.html 
sidebar: sidebar 
keywords: qos, quality of service, traffic classification, best practices, limit traffic, monitor traffic 
summary: 若要提升服務品質（QoS）產品、您可以建立流量分類原則、以識別及監控不同類型的網路流量。這些原則可協助限制流量及監控。 
---
= 管理流量分類原則
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
為了強化服務品質（QoS）產品、您可以建立流量分類原則、以識別及監控不同類型的網路流量。這些原則可協助限制流量及監控。

流量分類原則會套用至StorageGRID 閘道節點和管理節點的「動態負載平衡器」服務上的端點。若要建立流量分類原則、您必須已經建立負載平衡器端點。



== 符合規則和選用限制

每個流量分類原則都包含一或多個相符的規則、用以識別與下列一或多個實體相關的網路流量：

* 桶
* 租戶
* 子網路（包含用戶端的IPv4子網路）
* 端點（負載平衡器端點）


此功能可根據規則的目標、監控符合原則中任何規則的流量。StorageGRID符合原則任何規則的任何流量都會由該原則處理。相反地、您可以設定規則以符合指定實體以外的所有流量。

您也可以根據下列參數、為原則設定限制：

* 中的Aggregate頻寬
* Aggregate Bandwidth Out
* 並行讀取要求
* 並行寫入要求
* 中的每個要求頻寬
* 每個要求頻寬輸出
* 讀取要求率
* 寫入要求率



NOTE: 您可以建立原則來限制Aggregate頻寬或限制每個要求的頻寬。不過StorageGRID 、不能同時限制這兩種頻寬類型。Aggregate頻寬限制可能會對不受限制的流量造成額外的次要效能影響。



== 流量限制

建立流量分類原則之後、流量可能會根據您設定的規則類型和限制而受到限制。針對Aggregate或每個要求頻寬限制、要求會以您設定的速率傳入或傳出。由於支援的速度只能達到一種、因此根據matcher類型、最符合的原則就是強制執行的速度。StorageGRID對於所有其他限制類型、用戶端要求會延遲250毫秒、並針對超過任何相符原則限制的要求、收到503個慢速回應。

在Grid Manager中、您可以檢視交通路況圖表、並驗證原則是否強制實施您預期的流量限制。



== 將流量分類原則與SLA搭配使用

您可以將流量分類原則與容量限制和資料保護搭配使用、以強制執行服務層級協議（SLA）、以提供容量、資料保護和效能的詳細資訊。

每個負載平衡器都會實作流量分類限制。如果流量同時分散於多個負載平衡器、則總最大傳輸率是您指定的速率限制的倍數。

以下範例顯示SLA的三層。您可以建立流量分類原則、以達成每個SLA層級的效能目標。

[cols="1a,1a,1a,1a,1a"]
|===
| 服務層級 | 容量 | 資料保護 | 效能 | 成本 


 a| 
金級
 a| 
允許1 PB儲存容量
 a| 
3複製ILM規則
 a| 
每秒25 K個要求

每秒5 GB（40 Gbps）頻寬
 a| 
每月$$



 a| 
銀級
 a| 
允許250 TB儲存容量
 a| 
2複製ILM規則
 a| 
每秒10 K個要求

1.25 GB/秒（10 Gbps）頻寬
 a| 
每月$



 a| 
銅級
 a| 
允許100 TB儲存容量
 a| 
2複製ILM規則
 a| 
每秒5 K個要求

每秒1 GB（8 Gbps）頻寬
 a| 
每月$

|===