---
permalink: admin/managing-tenants.html 
sidebar: sidebar 
keywords: manage tenants, tenant account, what is a tenant 
summary: 身為網格管理員、您可以建立及管理S3和Swift用戶端用來儲存及擷取物件、監控儲存使用量、以及管理用戶端使用StorageGRID 您的作業系統所能執行的動作的租戶帳戶。 
---
= 管理租戶
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
身為網格管理員、您可以建立及管理S3和Swift用戶端用來儲存及擷取物件、監控儲存使用量、以及管理用戶端使用StorageGRID 您的作業系統所能執行的動作的租戶帳戶。



== 什麼是租戶帳戶？

租戶帳戶可讓使用簡易儲存服務（S3）REST API或Swift REST API的用戶端應用程式、將物件儲存及擷取StorageGRID 到無法使用的物件上。

每個租戶帳戶都支援使用單一傳輸協定、您可以在建立帳戶時指定。若要使用StorageGRID 這兩種通訊協定將物件儲存並擷取至某個支援系統、您必須建立兩個租戶帳戶：一個用於S3儲存區和物件、另一個用於Swift容器和物件。每個租戶帳戶都有自己的帳戶ID、授權群組和使用者、儲存區或容器、以及物件。

或者、如果您想要將儲存在系統上的物件依不同實體分隔、您也可以建立其他租戶帳戶。例如、您可以在下列任一使用案例中設定多個租戶帳戶：

* *企業使用案例：*如果您是在StorageGRID 企業應用程式中管理一套功能完善的系統、您可能會想要將網格的物件儲存區由組織中的不同部門加以隔離。在此案例中、您可以為行銷部門、客戶支援部門、人力資源部門等建立租戶帳戶。
+

NOTE: 如果您使用S3用戶端傳輸協定、只要使用S3儲存區和儲存區原則、即可在企業的各部門之間隔離物件。您不需要使用租戶帳戶。如需詳細資訊、請參閱實作S3用戶端應用程式的指示。

* *服務供應商使用案例：*如果您以StorageGRID 服務供應商的身份管理一個支援系統、則可以將網格的物件儲存區、由將儲存設備租賃至網格的不同實體來分隔。在這種情況下、您會為公司A、公司B、公司C等建立租戶帳戶。




== 建立及設定租戶帳戶

建立租戶帳戶時、請指定下列資訊：

* 顯示租戶帳戶的名稱。
* 租戶帳戶（S3或Swift）將使用哪種用戶端傳輸協定。
* 對於S3租戶帳戶：租戶帳戶是否有權使用S3時段的平台服務。如果您允許租戶帳戶使用平台服務、則必須確保網格已設定為支援其使用。請參閱「老舊平台服務」。
* 或者、租戶帳戶的儲存配額、也就是租戶物件可用的GB、TB或PB上限。如果超過配額、租戶就無法建立新物件。
+

NOTE: 租戶的儲存配額代表邏輯容量（物件大小）、而非實體容量（磁碟大小）。

* 如果啟用StorageGRID 身分識別聯盟以供支援整個系統、則哪個聯盟群組具有root存取權限、可設定租戶帳戶。
* 如果StorageGRID 不使用單一登入（SSO）進行支援、則租戶帳戶是使用自己的身分識別來源、還是共用網格的身分識別來源、以及租戶本機root使用者的初始密碼。


建立租戶帳戶之後、您可以執行下列工作：

* *管理網格平台服務*：如果您為租戶帳戶啟用平台服務、請確保您瞭解平台服務訊息的傳遞方式、以及StorageGRID 使用平台服務在您的支援範圍內的網路需求。
* *監控租戶帳戶的儲存使用量*：租戶開始使用其帳戶之後、您可以使用Grid Manager來監控每個租戶使用的儲存量。
+

NOTE: 如果節點與網格中的其他節點隔離、則租戶的儲存使用量值可能會過期。當網路連線恢復時、總計將會更新。

+
如果您已為租戶設定配額、您可以啟用*租戶配額使用量高*警示、以判斷租戶是否正在使用配額。如果啟用、當租戶使用90%的配額時、就會觸發此警示。如需詳細資訊、請參閱監控StorageGRID 和疑難排解功能的說明中的警示參考資料。

* *設定用戶端作業*：您可以設定是否禁止某些類型的用戶端作業。




== 設定S3租戶

建立S3租戶帳戶之後、租戶使用者就能存取租戶管理程式來執行下列工作：

* 設定身分識別聯盟（除非身分識別來源與網格共用）、並建立本機群組和使用者
* 管理S3存取金鑰
* 建立及管理S3儲存區
* 監控儲存使用量
* 使用平台服務（若已啟用）



IMPORTANT: S3租戶使用者可以使用租戶管理程式來建立及管理S3存取金鑰和儲存區、但必須使用S3用戶端應用程式來擷取和管理物件。



== 設定Swift租戶

建立Swift租戶帳戶之後、租戶的root使用者就能存取租戶管理程式來執行下列工作：

* 設定身分識別聯盟（除非身分識別來源與網格共用）、以及建立本機群組和使用者
* 監控儲存使用量



IMPORTANT: Swift使用者必須擁有root存取權限、才能存取租戶管理程式。不過、「根」存取權限不允許使用者驗證Swift REST API、以建立容器和擷取物件。使用者必須具有Swift Administrator權限、才能驗證到Swift REST API。

.相關資訊
xref:../tenant/index.adoc[使用租戶帳戶]
