---
permalink: admin/summary-ip-addresses-and-ports-for-client-connections.html 
sidebar: sidebar 
keywords: ip addresses for client, how to connect to storagegrid, ports, vip 
summary: 用戶端應用程式可以StorageGRID 使用網格節點的IP位址和該節點上服務的連接埠號碼來連線至功能區。如果已設定高可用度（HA）群組、用戶端應用程式就可以使用HA群組的虛擬IP位址進行連線。 
---
= 摘要：用於用戶端連線的IP位址和連接埠
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
用戶端應用程式可以StorageGRID 使用網格節點的IP位址和該節點上服務的連接埠號碼來連線至功能區。如果已設定高可用度（HA）群組、用戶端應用程式就可以使用HA群組的虛擬IP位址進行連線。

下表摘要說明用戶端連線StorageGRID 至靜態的不同方式、以及每種連線類型所使用的IP位址和連接埠。本指示說明如何在已設定負載平衡器端點和高可用度（HA）群組的情況下、於Grid Manager中找到此資訊。

[cols="1a,1a,1a,1a"]
|===
| 連線位置 | 用戶端連線的服務 | IP 位址 | 連接埠 


 a| 
HA群組
 a| 
負載平衡器
 a| 
HA群組的虛擬IP位址
 a| 
* 負載平衡器端點連接埠




 a| 
HA群組
 a| 
CLB

*附註：* CLB服務已過時。
 a| 
HA群組的虛擬IP位址
 a| 
預設S3連接埠：

* HTTPS：8082
* HTTP：8084


預設Swift連接埠：

* HTTPS：8083
* HTTP：8085




 a| 
管理節點
 a| 
負載平衡器
 a| 
管理節點的IP位址
 a| 
* 負載平衡器端點連接埠




 a| 
閘道節點
 a| 
負載平衡器
 a| 
閘道節點的IP位址
 a| 
* 負載平衡器端點連接埠




 a| 
閘道節點
 a| 
CLB

*附註：* CLB服務已過時。
 a| 
閘道節點的IP位址

*附註：*根據預設、不會啟用CLB和LDR的HTTP連接埠。
 a| 
預設S3連接埠：

* HTTPS：8082
* HTTP：8084


預設Swift連接埠：

* HTTPS：8083
* HTTP：8085




 a| 
儲存節點
 a| 
LdR
 a| 
儲存節點的IP位址
 a| 
預設S3連接埠：

* HTTPS：18082
* HTTP：18084


預設Swift連接埠：

* HTTPS：18083
* HTTP：18085


|===
若要將S3用戶端連線至閘道節點HA群組的負載平衡器端點、請使用結構如下所示的URL：

* https://_VIP-of-HA-group:LB-endpoint-port_`


例如、如果HA群組的虛擬IP位址為192.0.2.5、而S3負載平衡器端點的連接埠號碼為10443、則S3用戶端可以使用下列URL連線StorageGRID 到SESH:

* https://192.0.2.5:10443`


若要將Swift用戶端連線至閘道節點HA群組的負載平衡器端點、請使用結構如下所示的URL：

* https://_VIP-of-HA-group:LB-endpoint-port_`


例如、如果HA群組的虛擬IP位址為192.0.2.6、而Swift負載平衡器端點的連接埠號碼為104444、則Swift用戶端可使用下列URL連線StorageGRID 到Sender:

* https://192.0.2.6:10444`


您可以為用戶端用來連線StorageGRID 到靜態的IP位址設定DNS名稱。請聯絡您的本機網路管理員。

.步驟
. 使用登入Grid Manager xref:../admin/web-browser-requirements.adoc[支援的網頁瀏覽器]。
. 若要尋找網格節點的IP位址：
+
.. 選擇*節點*。
.. 選取您要連線的管理節點、閘道節點或儲存節點。
.. 選擇* Overview（概述）*選項卡。
.. 在「節點資訊」區段中、記下節點的IP位址。
.. 選取*顯示更多*以檢視IPv6位址和介面對應。
+
您可以從用戶端應用程式建立連線至清單中的任何IP位址：

+
*** * eth0：* Grid Network
*** * eth1：*管理網路（選用）
*** * eth2：*用戶端網路（選用）
+

NOTE: 如果您正在檢視管理節點或閘道節點、且該節點是高可用度群組中的作用中節點、則HA群組的虛擬IP位址會顯示在eth2上。





. 若要尋找高可用度群組的虛擬IP位址：
+
.. 選擇*組態*>*網路*>*高可用度群組*。
.. 在表中、記下HA群組的虛擬IP位址。


. 若要尋找負載平衡器端點的連接埠號碼：
+
.. 選擇*組態*>*網路*>*負載平衡器端點*。
+
此時會出現「負載平衡器端點」頁面、顯示已設定的端點清單。

.. 選取端點、然後選取*編輯端點*。
+
「編輯端點」視窗隨即開啟、並顯示端點的其他詳細資料。

.. 確認您選取的端點已設定為使用正確的傳輸協定（S3或Swift）、然後選取*取消*。
.. 記下您要用於用戶端連線的端點連接埠號碼。
+

NOTE: 如果連接埠號碼為80或443、則端點只會在閘道節點上設定、因為這些連接埠會保留在管理節點上。所有其他連接埠都在閘道節點和管理節點上設定。




