---
permalink: s3/changes-to-s3-rest-api-support.html 
sidebar: sidebar 
keywords: s3 rest api support changes 
summary: 您應該注意StorageGRID 到支援S3 REST API的功能有所變更。 
---
= S3 REST API支援變更
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您應該注意StorageGRID 到支援S3 REST API的功能有所變更。

[cols="1a,4a"]
|===
| 版本 | 註解 


 a| 
11.6%
 a| 
* 新增了使用「零件編號」要求參數的支援、可在「Get Object」（取得物件）和「head Object Request」（標頭物件要求）中使用。
* 新增S3物件鎖定的預設保留模式支援、以及儲存區層級的預設保留期間。
* 新增對「3：物件鎖定剩餘保留天數」原則條件金鑰的支援、以設定物件的允許保留期間範圍。
* 單一放置物件作業的最大_Recommended大小現在為5 GiB（5、368、709、120位元組）。如果您的物件大於5 GiB、請改用多部份上傳。



IMPORTANT: 在S2011.6中StorageGRID 、單一放置物件作業的最大_supported大小仍為5 TiB（5、497、558、13880位元組）。但是、如果您嘗試上傳超過5 GiB的物件、則會觸發* S3「Pure Object size too large *（將物件大小設為太大*）」警示。



 a| 
11.5
 a| 
* 新增對管理儲存區加密的支援。
* 新增了對S3物件鎖定和過時舊版規範要求的支援。
* 新增使用刪除版本型儲存區上的多個物件的支援。
* 現在已正確支援「Content-MD5」要求標頭。




 a| 
11.4
 a| 
* 新增刪除庫位標記、取得庫位標記及置入庫位標記的支援。不支援成本分攤標記。
* 對於StorageGRID 在VMware 11.4中建立的儲存區、不再需要限制物件金鑰名稱以符合效能最佳實務做法。
* 增加了對「3：ObjectRestore：Post」事件類型的儲存區通知支援。
* 現在已強制多部分零件的AWS大小限制。多部分上傳中的每個部分必須介於5個mib和5 GiB之間。最後一個部分可能小於5個mib。
* 新增對TLS 1.3的支援、以及支援的TLS加密套件更新清單。
* CLB服務已過時。




 a| 
11.3
 a| 
* 新增支援使用客戶提供的金鑰（SSE-C）進行物件資料的伺服器端加密。
* 新增刪除、取得及置放資源庫生命週期作業（僅限到期行動）和「x-amz-expiration」回應標頭的支援。
* 更新的「放置物件」、「放置物件」-「複製」和「多重成分上傳」、說明ILM規則在擷取時使用同步放置的影響。
* 更新支援的TLS加密套件清單。不再支援TLS 1.1密碼。




 a| 
11.2
 a| 
新增後物件還原支援、可搭配雲端儲存資源池使用。新增了使用AWS語法的支援、可用於ARN、原則條件金鑰、以及群組和儲存區原則中的原則變數。我們StorageGRID 將繼續支援使用此功能的現有群組和儲存區原則。

*附註：*在其他組態JSON/XML中使用ARN/URN StorageGRID （包括用於自訂的版本功能）並未變更。



 a| 
11.1.
 a| 
新增跨來源資源共享（CORS）支援、S3用戶端連線至網格節點的HTTP、以及儲存區的法規遵循設定。



 a| 
11.0
 a| 
新增支援、可設定適用於儲存區的平台服務（CloudMirror複寫、通知及Elasticsearch整合）。此外、也新增了對儲存區物件標記位置限制的支援、以及可用的一致性控制設定。



 a| 
10.4
 a| 
新增對ILM掃描版本設定、端點網域名稱頁面更新、原則、原則範例及PuttoverwriteObject權限中的條件和變數的支援。



 a| 
10.3.1
 a| 
新增版本管理支援。



 a| 
10.2
 a| 
新增對群組和庫位存取原則的支援、以及多部份複本（上傳零件-複本）的支援。



 a| 
10.1
 a| 
新增多部分上傳、虛擬託管樣式要求及v4驗證的支援。



 a| 
10.0%
 a| 
由整個系統初始支援S3 REST API StorageGRID 。目前支援的_Simple Storage Service API Reference版本為2009-03-01。

|===