---
permalink: s3/complete-multipart-upload.html 
sidebar: sidebar 
keywords: multipart upload, object, object size 
summary: 完整的「多重零件上傳」作業會透過組裝先前上傳的零件、完成物件的多重部分上傳。 
---
= 完成多部份上傳
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
完整的「多重零件上傳」作業會透過組裝先前上傳的零件、完成物件的多重部分上傳。



== 解決衝突

衝突的用戶端要求（例如兩個寫入同一個金鑰的用戶端）會以「最新致勝」的方式解決。「最新致勝」評估的時間取決於StorageGRID 何時由VMware系統完成指定的要求、而非S3用戶端開始作業的時間。



== 要求標頭

支援「x-amz-Storage-Class」要求標頭、如果StorageGRID 相符的ILM規則指定「雙重認可」或「平衡」的擷取行為、則會影響到所建立的物件複本數量。

* 《標準》
+
（預設）當ILM規則使用雙重提交選項、或平衡選項回到建立臨時複本時、指定雙重提交擷取作業。

* "educed_deete"
+
當ILM規則使用雙重提交選項、或平衡選項回到建立過渡複本時、指定單一提交擷取作業。

+

NOTE: 如果在啟用S3物件鎖定的情況下、將物件放入儲存區、則會忽略「已儲存的備援」選項。如果您將物件放入符合舊規範的儲存區、則「educed_de隊」選項會傳回錯誤。執行「雙重承諾」的程序時、務必確保符合法規遵循要求。StorageGRID




IMPORTANT: 如果多部分上傳未在15天內完成、則該作業會標示為非作用中、且所有相關資料都會從系統中刪除。


NOTE: 傳回的「ETag」值不是資料的一組MD5總和、而是在Amazon S3 API實作多部份物件的「ETag」值之後。



== 版本管理

此作業會完成多部份上傳。如果已針對某個儲存區啟用版本管理、則會在完成多重部分上傳時建立物件版本。

如果已針對儲存區啟用版本管理、系統會針對儲存的物件版本自動產生唯一的「版本ID」。此「版本ID」也會在回應中使用「x-amz-version -id」回應標頭傳回。

如果版本控制暫停、則物件版本會以null「VrionId」儲存、如果null版本已經存在、則會覆寫該版本。


NOTE: 當某個儲存區啟用版本管理時、完成多部份上傳會一律建立新版本、即使在同一個物件金鑰上同時完成多部份上傳也一樣。如果未針對某個儲存區啟用版本管理、則可以啟動多重部分上傳、然後在同一個物件金鑰上啟動並完成另一個多重部分上傳。在非版本的儲存區上、完成最後一次的多部分上傳優先。



== 複寫失敗、通知或中繼資料通知

如果平台服務已設定多重零件上傳的儲存區、即使相關的複寫或通知動作失敗、多重零件上傳仍會成功。

如果發生這種情況、則會在Grid Manager中針對Total事件（SMT）發出警示。最後一個事件訊息會針對通知失敗的最後一個物件、顯示「無法發佈Bucket名稱物件金鑰的通知」。（要查看此訊息、請選取*節點*>*儲存節點_*>*事件*。檢視表格頂端的最後一個事件。） 事件訊息也會列在「/var/local/log/bycast-err.log」中。

租戶可透過更新物件的中繼資料或標記來觸發失敗的複寫或通知。租戶可以重新提交現有的值、以避免進行不必要的變更。

.相關資訊
xref:../ilm/index.adoc[使用ILM管理物件]
