---
permalink: s3/deprecated-get-bucket-compliance-request.html 
sidebar: sidebar 
keywords: S3 REST API, S3 operations, deprecated GET compliance requests 
summary: Get Bucket法規遵循要求已過時。不過、您可以繼續使用此要求來判斷現有舊版相容儲存區目前有效的法規遵循設定。 
---
= 已過時：Get Bucket Compliance要求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Get Bucket法規遵循要求已過時。不過、您可以繼續使用此要求來判斷現有舊版相容儲存區目前有效的法規遵循設定。


IMPORTANT: 先前版本的不支援《支援不符合要求》功能、現已由S3物件鎖定取代。StorageGRID StorageGRID

xref:using-s3-object-lock.adoc[使用S3物件鎖定]

xref:../ilm/index.adoc[使用ILM管理物件]

https://["NetApp知識庫：如何管理StorageGRID 支援老舊的知識庫、請參閱《知識庫文章"^]

您有S3：GetBucketCompliance權限、或是帳戶root、可以完成此作業。



== 申請範例

此範例要求可讓您決定名為「mybucket」的儲存貯體的法規遵循設定。

[source, subs="specialcharacters,quotes"]
----
GET /mybucket/?x-ntap-sg-compliance HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_
----


== 回應範例

在回應XML中、「<SGCompliance >」會列出此儲存區的有效法規遵循設定。此回應範例顯示儲存區的法規遵循設定、其中每個物件將保留一年（525600分鐘）、從物件擷取到網格開始算起。此庫位目前沒有合法持有。每個物件將在一年後自動刪除。

[source, subs="specialcharacters,quotes"]
----
HTTP/1.1 200 OK
Date: _date_
Connection: _connection_
Server: StorageGRID/11.1.0
x-amz-request-id: _request ID_
Content-Length: _length_
Content-Type: application/xml

<SGCompliance>
  <RetentionPeriodMinutes>525600</RetentionPeriodMinutes>
  <LegalHold>false</LegalHold>
  <AutoDelete>true</AutoDelete>
</SGCompliance>
----
|===
| 名稱 | 說明 


 a| 
RetentionPeriodMinutes
 a| 
新增至此儲存區之物件的保留期間長度（以分鐘為單位）。保留期間是從物件擷取至網格時開始。



 a| 
LegalHold
 a| 
* 是：此儲存庫目前處於合法持有狀態。在取消合法持有之前、即使保留期間已過期、也無法刪除此儲存區中的物件。
* 假：此庫位目前未合法持有。此儲存區中的物件可在保留期間到期時刪除。




 a| 
自動刪除
 a| 
* 是：此儲存區中的物件會在保留期間到期時自動刪除、除非儲存區處於合法持有狀態。
* 否：保留期間到期時、此儲存區中的物件不會自動刪除。如果需要刪除這些物件、您必須手動刪除這些物件。


|===


== 錯誤回應

如果儲存區的建立不符合法規要求、回應的HTTP狀態代碼為「找不到404」、S3錯誤代碼為「XNoSuchBucketCompliance」（XNoSuchBucketCompliance）。

.相關資訊
xref:../ilm/index.adoc[使用ILM管理物件]

xref:../tenant/index.adoc[使用租戶帳戶]
