---
permalink: s3/deprecated-put-bucket-compliance-request.html 
sidebar: sidebar 
keywords: S3 REST API, S3 operations, PUT deprecated compliance requests 
summary: 「放入時段」法規遵循要求已過時。不過、您可以繼續使用此要求來修改現有舊版相容桶的法規遵循設定。 
---
= 已過時：提出資源桶法規遵循要求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「放入時段」法規遵循要求已過時。不過、您可以繼續使用此要求來修改現有舊版相容桶的法規遵循設定。例如、您可以將現有的貯體置於合法持有狀態、或是延長保留期間。


IMPORTANT: 先前版本的不支援《支援不符合要求》功能、現已由S3物件鎖定取代。StorageGRID StorageGRID

xref:using-s3-object-lock.adoc[使用S3物件鎖定]

xref:../ilm/index.adoc[使用ILM管理物件]

https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_manage_legacy_Compliant_buckets_in_StorageGRID_11.5["NetApp知識庫：如何管理StorageGRID 支援老舊的知識庫、請參閱《知識庫文章"^]

您有S3：PuttBucketCompliance權限、或是帳戶root、才能完成此作業。

在發出「放入庫位」法規遵循要求時、您必須為法規遵循設定的每個欄位指定一個值。



== 申請範例

此範例要求會修改名為「mybucket」之儲存區的法規遵循設定。在此範例中、「mybucket」中的物件現在將保留兩年（1、051、200分鐘）、而非一年、從物件進入網格開始。此庫位沒有合法持有。每個物件將在兩年後自動刪除。

[source, subs="specialcharacters,quotes"]
----
PUT /mybucket/?x-ntap-sg-compliance HTTP/1.1
Date: _date_
Authorization: _authorization name_
Host: _host_
Content-Length: 152

<SGCompliance>
  <RetentionPeriodMinutes>1051200</RetentionPeriodMinutes>
  <LegalHold>false</LegalHold>
  <AutoDelete>true</AutoDelete>
</SGCompliance>
----
|===
| 名稱 | 說明 


 a| 
RetentionPeriodMinutes
 a| 
新增至此儲存區之物件的保留期間長度（以分鐘為單位）。保留期間是從物件擷取至網格時開始。

*注意：*當為RetentionPeriodMinute指定新值時、您必須指定等於或大於該儲存格目前保留期間的值。在桶的保留期間設定完成之後、您就無法減少該值、只能增加該值。



 a| 
LegalHold
 a| 
* 是：此儲存庫目前處於合法持有狀態。在取消合法持有之前、即使保留期間已過期、也無法刪除此儲存區中的物件。
* 假：此庫位目前未合法持有。此儲存區中的物件可在保留期間到期時刪除。




 a| 
自動刪除
 a| 
* 是：此儲存區中的物件會在保留期間到期時自動刪除、除非儲存區處於合法持有狀態。
* 否：保留期間到期時、此儲存區中的物件不會自動刪除。如果需要刪除這些物件、您必須手動刪除這些物件。


|===


== 法規遵循設定的一致性層級

當您更新S3儲存區的法規遵循設定、並提出「置放儲存區法規遵循」要求時StorageGRID 、即可嘗試更新整個網格的儲存區中繼資料。根據預設、StorageGRID 支援使用*強式全域*一致性層級、以保證所有資料中心站台及包含儲存庫中繼資料的所有儲存節點、在變更的法規遵循設定中、具有寫入後讀取一致性。

如果StorageGRID 由於某個站台的資料中心站台或多個儲存節點無法使用、導致無法達到*強式全域*一致性等級、則回應的HTTP狀態代碼為「503服務無法使用」

如果您收到此回應、則必須聯絡網格管理員、以確保所需的儲存服務能夠儘快提供。如果網格管理員無法在每個站台上提供足夠的儲存節點、技術支援可能會強制*強站台*一致性層級、引導您重試失敗的要求。


IMPORTANT: 除非您是技術支援人員的指示、而且您不瞭解使用此層級可能造成的後果、否則請勿強迫*強站台*一致性層級以符合放置桶規範。

當一致性層級降至*強站台*時StorageGRID 、更新的法規遵循設定只有在站台內的用戶端要求才具有寫入後讀取一致性。這表示StorageGRID 在所有站台和儲存節點都可用之前、此儲存區的設定可能會暫時有多個不一致的設定。不一致的設定可能會導致非預期和非預期的行為。例如、如果您將儲存庫置於合法持有之下、而強制降低一致性層級、則儲存庫先前的法規遵循設定（即合法暫停）可能會繼續在某些資料中心站台上生效。因此、您認為合法保留的物件、可能會在保留期間到期時遭到刪除、使用者或自動刪除（如果已啟用）。

若要強制使用*強站台*一致性層級、請重新發出PPUT Bucket法規遵循要求、並加入「一致性控制」HTTP要求標頭、如下所示：

[listing]
----
PUT /mybucket/?x-ntap-sg-compliance HTTP/1.1
Consistency-Control: strong-site
----


== 錯誤回應

* 如果儲存區的建立不符合法規要求、回應的HTTP狀態代碼為「找不到404」。
* 如果申請中的「RetentionPeriodMinutes」低於庫位目前的保留期間、則HTTP狀態代碼為「400 Bad Request」（400錯誤要求）。


xref:deprecated-put-bucket-request-modifications-for-compliance.adoc[已過時：將資源桶要求修改以符合法規要求]

xref:../tenant/index.adoc[使用租戶帳戶]

xref:../ilm/index.adoc[使用ILM管理物件]
