---
permalink: s3/get-object.html 
sidebar: sidebar 
keywords: get object 
summary: 您可以使用S3取得物件要求、從S3儲存區擷取物件。 
---
= 取得物件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用S3取得物件要求、從S3儲存區擷取物件。



== 取得物件和多個部分物件

您可以使用「partNumber」要求參數來擷取多個部分或分段物件的特定部分。「x-amz-mp-零 件數」回應元素會指出物件有多少個部分。

您可以將分段/多部份物件和非分段/非多部份物件的「partNumber」設為1、但是「x-amz-mp-part-count」回應元素只會針對分段或多部份物件傳回。



== 使用客戶提供的加密金鑰（SSE-C）要求伺服器端加密標頭

如果物件是以您提供的唯一金鑰加密、請使用所有三個標頭。

* 「X-amz-server端加密客戶演算法」：指定「AES256」。
* 「X-amz-server端加密客戶金鑰」：指定物件的加密金鑰。
* 「X-amz-server端加密- customer-key-md5」：指定物件加密金鑰的md5摘要。



IMPORTANT: 您提供的加密金鑰永遠不會儲存。如果您遺失加密金鑰、就會遺失對應的物件。在使用客戶提供的金鑰來保護物件資料之前、請先檢閱「使用伺服器端加密」中的考量事項。



== 使用者中繼資料中的UTF-8字元

在使用者定義的中繼資料中、無法剖析或解譯轉義的utf-8字元。StorageGRID如果金鑰名稱或值包含不可列印的字元、則在使用者定義的中繼資料中、取得內含轉義式utf-8字元的物件要求時、不會傳回「x-amz-missing中繼資料」標頭。



== 不支援的要求標頭

不支援下列要求標頭、並傳回「XNotImplemed」：

* 「X-amz-website - redirect-location」




== 版本管理

如果未指定「版本ID」子資源、則作業會擷取版本控制儲存區中的物件最新版本。如果物件的目前版本是刪除標記、則會傳回「找不到」狀態、並將「x-amz-delete-marker'回應標頭設為「true」。



== 取得雲端儲存池物件的行為

如果物件已儲存在Cloud Storage Pool中（請參閱管理物件的指示、並進行資訊生命週期管理）、則Get物件要求的行為取決於物件的狀態。如需詳細資訊、請參閱「標頭物件」。


NOTE: 如果物件儲存在雲端儲存資源池中、而且網格上也有一個或多個物件複本、則「Get Object（取得物件）」要求會先嘗試從網格擷取資料、然後再從雲端儲存資源池擷取資料。

|===
| 物件狀態 | Get物件的行為 


 a| 
物件擷取到StorageGRID 不經ILM評估、或儲存在傳統儲存資源池中的物件、或使用銷毀編碼
 a| 
「200 OK」

系統會擷取物件複本。



 a| 
Cloud Storage Pool中的物件、但尚未轉換為無法擷取的狀態
 a| 
「200 OK」

系統會擷取物件複本。



 a| 
物件移轉至無法擷取的狀態
 a| 
"403 Forbidbid"、"InvalidObjectState"

使用POST物件還原要求、將物件還原至可擷取的狀態。



 a| 
正在從無法擷取的狀態還原的物件
 a| 
"403 Forbidbid"、"InvalidObjectState"

等待POST物件還原要求完成。



 a| 
物件已完全還原至雲端儲存資源池
 a| 
「200 OK」

系統會擷取物件複本。

|===


== 雲端儲存資源池中的多部份或分段物件

如果您上傳了多個部分的物件、或StorageGRID 是將一個大型物件分割成多個區段、StorageGRID 則透過取樣物件的一部分或區段、決定該物件是否可在Cloud Storage Pool中使用。在某些情況下、當物件的某些部分已轉換為無法擷取的狀態、或物件的某些部分尚未還原時、「Get物件」要求可能會錯誤傳回「200 OK」。

在這些情況下：

* Get Object要求可能會傳回部分資料、但會在傳輸中途停止。
* 隨後的Get Object要求可能會傳回「403 Forbidbid禁 用」。


xref:using-server-side-encryption.adoc[使用伺服器端加密]

xref:../ilm/index.adoc[使用ILM管理物件]

xref:post-object-restore.adoc[POST物件還原]

xref:s3-operations-tracked-in-audit-logs.adoc[在稽核記錄中追蹤S3作業]
