---
permalink: s3/head-object.html 
sidebar: sidebar 
keywords: head object 
summary: 您可以使用S3頭物件要求從物件擷取中繼資料、而不傳回物件本身。 
---
= 標頭物件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用S3頭物件要求從物件擷取中繼資料、而不傳回物件本身。如果物件儲存在Cloud Storage Pool中、您可以使用「標頭物件」來判斷物件的轉換狀態。



== 標頭物件和多個部分物件

您可以使用「partNumber」要求參數來擷取多個部分或分段物件特定部分的中繼資料。「x-amz-mp-零 件數」回應元素會指出物件有多少個部分。

您可以將分段/多部份物件和非分段/非多部份物件的「partNumber」設為1、但是「x-amz-mp-part-count」回應元素只會針對分段或多部份物件傳回。



== 使用客戶提供的加密金鑰（SSE-C）要求伺服器端加密標頭

如果物件使用您提供的唯一金鑰加密、請使用這三個標頭。

* 「X-amz-server端加密客戶演算法」：指定「AES256」。
* 「X-amz-server端加密客戶金鑰」：指定物件的加密金鑰。
* 「X-amz-server端加密- customer-key-md5」：指定物件加密金鑰的md5摘要。



IMPORTANT: 您提供的加密金鑰永遠不會儲存。如果您遺失加密金鑰、就會遺失對應的物件。在使用客戶提供的金鑰來保護物件資料之前、請先檢閱「使用伺服器端加密」中的考量事項。



== 使用者中繼資料中的UTF-8字元

在使用者定義的中繼資料中、無法剖析或解譯轉義的utf-8字元。StorageGRID如果金鑰名稱或值包含不可列印的字元、則使用者定義中繼資料中轉義的UTF-8字元物件的標頭要求不會傳回「x-amz-missing中繼資料」標頭。



== 不支援的要求標頭

不支援下列要求標頭、並傳回「XNotImplemed」：

* 「X-amz-website - redirect-location」




== Cloud Storage Pool物件的回應標頭

如果物件儲存在Cloud Storage Pool中（請參閱使用資訊生命週期管理來管理物件的指示）、則會傳回下列回應標頭：

* 《X-amz-storage等級：Glacier》（《X-amz-storage等級：Glacier》）
* 「X-amz-restore」


回應標頭會提供物件移至雲端儲存集區時的狀態資訊、並選擇性地移轉至無法擷取的狀態、然後還原。

|===
| 物件狀態 | 回應標頭物件 


 a| 
物件擷取到StorageGRID 不經ILM評估、或儲存在傳統儲存資源池中的物件、或使用銷毀編碼
 a| 
「200 OK」（未傳回特殊回應標頭）。



 a| 
Cloud Storage Pool中的物件、但尚未轉換為無法擷取的狀態
 a| 
「200 OK」

《X-amz-storage等級：Glacier》（《X-amz-storage等級：Glacier》）

「X-amz-restore：展中要求=「假」、過期日期=「週六、7月23日2030：00：00 GMT"

在物件轉換為無法擷取的狀態之前、「過期日期」的值會設定為未來的某個時間。確切的轉換時間不受StorageGRID 此功能的控制。



 a| 
物件已轉換為無法擷取的狀態、但網格上至少也有一個複本
 a| 
「200 OK」

《X-amz-storage等級：Glacier》（《X-amz-storage等級：Glacier》）

「X-amz-restore：展中要求=「假」、過期日期=「週六、7月23日2030：00：00 GMT"

「過期日」的值會設定為未來的某段時間。

*附註*：如果網格上的複本無法使用（例如、儲存節點當機）、您必須發出物件後還原要求、以便從雲端儲存池還原複本、才能成功擷取物件。



 a| 
物件移轉至無法擷取的狀態、而且網格上不存在複本
 a| 
「200 OK」

《X-amz-storage等級：Glacier》（《X-amz-storage等級：Glacier》）



 a| 
正在從無法擷取的狀態還原的物件
 a| 
「200 OK」

《X-amz-storage等級：Glacier》（《X-amz-storage等級：Glacier》）

「x-amz-restore：持續要求=「true」



 a| 
物件已完全還原至雲端儲存資源池
 a| 
「200 OK」

《X-amz-storage等級：Glacier》（《X-amz-storage等級：Glacier》）

「X-amz-restore：展中要求=「假」、過期日期=「2018年7月23日星期六00：00：00 GMT」

「過期日」表示Cloud Storage Pool中的物件何時會恢復為無法擷取的狀態。

|===


== Cloud Storage Pool中的多部份或分段物件

如果您上傳了多個部分的物件、或StorageGRID 是將一個大型物件分割成多個區段、StorageGRID 則透過取樣物件的一部分或區段、決定該物件是否可在Cloud Storage Pool中使用。在某些情況下、當物件的某些部分已轉換為無法擷取的狀態、或物件的某些部分尚未還原時、物件要求可能會錯誤地傳回「x-amz-restore: onale-request ="false"（x-amz-restore:持續要求=「假」）。



== 版本管理

如果未指定「版本ID」子資源、則作業會擷取版本控制儲存區中的物件最新版本。如果物件的目前版本是刪除標記、則會傳回「找不到」狀態、並將「x-amz-delete-marker'回應標頭設為「true」。

.相關資訊
xref:using-server-side-encryption.adoc[使用伺服器端加密]

xref:../ilm/index.adoc[使用ILM管理物件]

xref:post-object-restore.adoc[POST物件還原]

xref:s3-operations-tracked-in-audit-logs.adoc[在稽核記錄中追蹤S3作業]
