---
permalink: s3/how-storagegrid-ilm-rules-manage-objects.html 
sidebar: sidebar 
keywords: ilm manage object rules 
summary: 網格管理員會建立資訊生命週期管理（ILM）規則、以管理StorageGRID 從S3 REST API用戶端應用程式擷取到整個系統的物件資料。然後將這些規則新增至ILM原則、以決定物件資料的儲存方式和位置。 
---
= 如何利用ILM規則來管理物件StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
網格管理員會建立資訊生命週期管理（ILM）規則、以管理StorageGRID 從S3 REST API用戶端應用程式擷取到整個系統的物件資料。然後將這些規則新增至ILM原則、以決定物件資料的儲存方式和位置。

ILM設定決定物件的下列層面：

* *地理*
+
物件資料的位置、無論是StorageGRID 在更新系統（儲存資源池）或雲端儲存資源池中。

* *儲存等級*
+
用於儲存物件資料的儲存類型：例如Flash或旋轉式磁碟。

* *損失保護*
+
製作了多少份複本、以及建立的複本類型：複寫、銷毀編碼或兩者。

* *保留*
+
物件資料的管理方式、儲存位置、以及保護資料不受遺失的方式、都會隨時間而改變。

* *擷取期間的保護*
+
用於在擷取期間保護物件資料的方法：同步放置（使用擷取行為的平衡或嚴格選項）、或製作過渡複本（使用雙重提交選項）。



ILM規則可篩選及選取物件。對於使用S3擷取的物件、ILM規則可根據下列中繼資料來篩選物件：

* 租戶帳戶
* 儲存區名稱
* 擷取時間
* 金鑰
* 上次存取時間
+

NOTE: 根據預設、所有S3儲存區的上次存取時間更新都會停用。如果StorageGRID 您的支援系統包含使用「上次存取時間」選項的ILM規則、則必須針對該規則中指定的S3儲存區、啟用更新以達到上次存取時間。您可以使用租戶管理程式中的「放置時段上次存取時間」要求、「* S3 *>* Bucket *>*設定上次存取時間*」核取方塊、或使用租戶管理API來啟用上次存取時間更新。啟用上次存取時間更新時、請注意StorageGRID 、可能會降低不佳效能、尤其是在使用小型物件的系統中。

* 位置限制
* 物件大小
* 使用者中繼資料
* 物件標記


如需ILM的詳細資訊、請參閱資訊生命週期管理的物件管理說明。

xref:../tenant/index.adoc[使用租戶帳戶]

xref:../ilm/index.adoc[使用ILM管理物件]

xref:put-bucket-last-access-time-request.adoc[將時段放入上次存取時間要求]
