---
permalink: s3/initiate-multipart-upload.html 
sidebar: sidebar 
keywords: initiate multipart upload, uploads 
summary: 「初始化多部份上傳」作業會針對物件啟動多部份上傳、並傳回上傳ID。 
---
= 啟動多部份上傳
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「初始化多部份上傳」作業會針對物件啟動多部份上傳、並傳回上傳ID。

支援「x-amz-storage -Class」要求標頭。提交給「x-amz-Storage-Class」的值、會影響StorageGRID 到在擷取期間、如何保護物件資料、以及StorageGRID 不需要將物件的持續複本儲存在包含在ILM系統中的數量。

如果符合擷取物件的ILM規則使用擷取行為的嚴格選項、則「x-amz-Storage-Class」標頭不會有任何影響。

下列值可用於「x-amz-storage類別」：

* 「標準」（預設）
+
** *雙重提交*：如果ILM規則指定「內嵌行為」的「雙重提交」選項、則只要物件擷取到另一個物件複本、就會建立該物件的第二個複本、並將其分散到不同的儲存節點（雙重提交）。評估ILM時、StorageGRID會判斷這些初始過渡複本是否符合規則中的放置指示。如果沒有、可能需要在不同位置建立新的物件複本、而且可能需要刪除初始的過渡複本。
** *平衡*：如果ILM規則指定平衡選項、StorageGRID 且無法立即製作規則中指定的所有複本、StorageGRID 則在不同的儲存節點上製作兩份臨時複本。
+
如果能夠立即建立ILM規則（同步放置）中指定的所有物件複本、「x-amz-Storage-Class」標頭就不會有任何影響。StorageGRID



* "educed_deete"
+
** *雙重提交*：如果ILM規則指定擷取行為的雙重提交選項、StorageGRID 則會在擷取物件時建立單一的過渡複本（單一提交）。
** *平衡*：如果ILM規則指定平衡選項、StorageGRID 則僅當系統無法立即製作規則中指定的所有複本時、才能製作單一的過渡複本。如果能夠執行同步放置、則此標頭不會有任何影響。StorageGRID當符合物件的ILM規則建立單一複寫複本時、最適合使用「已儲存的備援」選項。在這種情況下、使用「reduced_dere通用」可免除每次擷取作業不必要地建立和刪除額外的物件複本。


+
在其他情況下、不建議使用「已儲存的備援」選項。「已導入的備援」會增加擷取期間物件資料遺失的風險。例如、如果單一複本一開始儲存在無法進行ILM評估的儲存節點上、則可能會遺失資料。



*注意*：在任何時間段內只有一個複寫複本、會使資料面臨永久遺失的風險。如果只有一個物件複寫複本存在、則當儲存節點故障或發生重大錯誤時、該物件就會遺失。在升級等維護程序期間、您也會暫時失去物件的存取權。

指定「已儲存的備援」僅會影響第一次擷取物件時所建立的複本數量。它不會影響使用中ILM原則評估物件時所製作的物件複本數量、也不會導致資料儲存在StorageGRID 較低層級的資料冗餘環境中。

*附註*：如果您在啟用S3物件鎖定的情況下、將物件放入儲存區、則會忽略「已傳入的備援」選項。如果您將物件放入符合舊規範的儲存區、則「educed_de隊」選項會傳回錯誤。執行「雙重承諾」的程序時、務必確保符合法規遵循要求。StorageGRID

支援下列要求標頭：

* 「內容類型」
* 「x-amz-meta-」、接著是包含使用者定義中繼資料的名稱值配對
+
為使用者定義的中繼資料指定名稱值配對時、請使用以下一般格式：

+
[listing]
----
x-amz-meta-_name_: `value`
----
+
如果您要使用*使用者定義的建立時間*選項做為ILM規則的參考時間、則必須使用「建立時間」做為建立物件時記錄的中繼資料名稱。例如：

+
[listing]
----
x-amz-meta-creation-time: 1443399726
----
+
自70年1月1日起、「創造時間」的值會以秒計算。

+

NOTE: 如果您要將物件新增至已啟用舊版法規遵循的儲存區、則不允許將「creation - Time」新增為使用者定義的中繼資料。將傳回錯誤。

* S3物件鎖定要求標頭：
+
** 「X-amz-object-lock-mode」
** 《X-amz-object-lock-Retain直到日期》
** 「X-amz-object-lock-legal hold」
+
如果提出的要求沒有這些標頭、則會使用儲存庫預設保留設定來計算物件版本的保留日期。

+
xref:using-s3-object-lock.adoc[使用S3物件鎖定]



* SSe要求標頭：
+
** 「X-amz-server端點加密」
** 「X-amz-server端加密- customer-key-md5」
** 「X-amz-server端加密客戶金鑰」
** 「X-amz-server端加密- customer-演算 法」
+
 headers for server-side encryption



+

NOTE: 如需StorageGRID 瞭解如何處理UTF-8字元的資訊、請參閱「放置物件」的文件。





== 要求伺服器端加密的標頭

您可以使用下列要求標頭、以伺服器端加密來加密多部份物件。「SSE」和「SSE-C」選項互不相關。

* * SSE-*：如果您想要使用StorageGRID 由支援的唯一金鑰來加密物件、請在「初始化多部份上傳」要求中使用下列標頭。請勿在任何上傳零件要求中指定此標頭。
+
** 「X-amz-server端點加密」


* * SSE-C*：如果您想要使用您提供及管理的唯一金鑰來加密物件、請在「初始化多部份上傳」要求（以及後續的每個「上傳零件」要求）中使用這三個標頭。
+
** 「X-amz-server端加密客戶演算法」：指定「AES256」。
** 「X-amz-server端加密客戶金鑰」：指定新物件的加密金鑰。
** 「X-amz-server端加密- customer-key-md5」：指定新物件加密金鑰的md5摘要。




*注意：*您提供的加密金鑰永遠不會儲存。如果您遺失加密金鑰、就會遺失對應的物件。在使用客戶提供的金鑰來保護物件資料之前、請先檢閱「使用伺服器端加密」中的考量事項。



== 不支援的要求標頭

不支援下列要求標頭、並傳回「XNotImplemed」

* 「X-amz-website - redirect-location」




== 版本管理

多部分上傳包含不同的作業、可用於初始化上傳、列出上傳內容、上傳零件、組裝上傳的零件、以及完成上傳。執行完整的「多重組件上傳」作業時、會建立物件（並在適用情況下建立版本）。

xref:../ilm/index.adoc[使用ILM管理物件]

xref:using-server-side-encryption.adoc[使用伺服器端加密]

xref:put-object.adoc[放置物件]
