---
permalink: s3/operations-on-buckets.html 
sidebar: sidebar 
keywords: bucket, buckets, operations on buckets 
summary: 這個系統最多可為每個S3租戶帳戶支援1、000個貯體。StorageGRID 
---
= 在貯體上作業
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
這個系統最多可為每個S3租戶帳戶支援1、000個貯體。StorageGRID

儲存區名稱限制遵循AWS US Standard地區限制、但您應該進一步限制它們使用DNS命名慣例、以支援S3虛擬託管型要求。

https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html["Amazon Web Services（AWS）文件：儲存區限制與限制"^]

xref:../admin/configuring-s3-api-endpoint-domain-names.adoc[設定S3 API端點網域名稱]

Get Bucket（列出物件）和Get Bucket版本作業支援StorageGRID 一致性控管。

您可以檢查是否為個別的儲存區啟用或停用上次存取時間的更新。

下表說明StorageGRID 了為什麼由Ss哪些 人執行S3 REST API貯體作業。若要執行上述任何作業、必須為帳戶提供必要的存取認證資料。

[cols="1a,3a"]
|===
| 營運 | 實作 


 a| 
刪除時段
 a| 
以所有Amazon S3 REST API行為來實作。



 a| 
刪除庫位檢查
 a| 
此作業會刪除儲存區的CORS組態。



 a| 
刪除時段加密
 a| 
此作業會從儲存區刪除預設加密。現有的加密物件仍會保持加密狀態、但新增至儲存區的任何新物件都不會加密。



 a| 
刪除時段生命週期
 a| 
此作業會從儲存庫中刪除生命週期組態。



 a| 
刪除庫位原則
 a| 
此作業會刪除附加至儲存貯體的原則。



 a| 
刪除時段複寫
 a| 
此作業會刪除附加至儲存區的複寫組態。



 a| 
刪除庫位標記
 a| 
此作業使用「標記」子資源來移除貯體中的所有標記。



 a| 
Get Bucket（列出物件）、版本1和版本2
 a| 
此作業會傳回某個儲存區中的部分或全部（最多1、000個）物件。物件的儲存類別可以有兩個值之一、即使物件是使用「已儲存的備援」儲存類別選項擷取的：

* 「標準」、表示物件儲存在儲存節點所組成的儲存資源池中。
* 「Glacier」、表示物件已移至Cloud Storage Pool指定的外部儲存桶。


如果儲存區包含大量具有相同前置碼的刪除金鑰、回應可能會包含一些不含金鑰的「CommonPrechs」。



 a| 
取得Bucket ACL
 a| 
此作業會傳回正面回應、並傳回貯體擁有者的ID、顯示名稱和權限、表示擁有者對該貯體具有完整存取權。



 a| 
獲取庫位檢查器
 a| 
此操作會傳回該鏟斗的「cors」組態。



 a| 
取得Bucket加密
 a| 
此作業會傳回儲存區的預設加密組態。



 a| 
取得生命週期
 a| 
此作業會傳回該儲存庫的生命週期組態。



 a| 
取得理想位置
 a| 
此作業會傳回使用PUT Bucket要求中的「LocationConstraint」元素所設定的區域。如果桶區為「us-east-1」、則會傳回該區域的空白字串。



 a| 
取得庫存箱通知
 a| 
此作業會傳回附加至儲存貯體的通知組態。



 a| 
取得Bucket物件版本
 a| 
此作業可透過儲存區的讀取存取權限、以「版本」子資源列出儲存區中所有物件版本的中繼資料。



 a| 
取得庫存管理政策
 a| 
此作業會傳回附加至庫位的原則。



 a| 
取得庫位複寫
 a| 
此作業會傳回附加至儲存區的複寫組態。



 a| 
取得庫位標記
 a| 
此作業使用「標記」子資源來傳回某個儲存區的所有標記。



 a| 
取得版本管理
 a| 
此實作會使用「資料夾」子資源來傳回儲存庫的版本管理狀態。

* _blank_：從未啟用版本管理（儲存庫為「未版本管理」）
* 已啟用：已啟用版本管理
* 已暫停：先前已啟用版本管理、並已暫停




 a| 
取得物件鎖定組態
 a| 
此作業會傳回儲存區預設保留模式和預設保留期間（若已設定）。

請參閱 xref:../s3/use-s3-object-lock-default-bucket-retention.adoc#get-object-lock-configuration[取得物件鎖定組態] 以取得詳細資訊。



 a| 
鏟斗
 a| 
此作業會判斷儲存區是否存在、且您是否有權存取它。

此作業會傳回：

* 「X-nTap sg-bucke-id」：UUID格式的儲存區UUID。
* 「X-ntap-sg-scale-id」：相關要求的唯一追蹤ID。




 a| 
放入鏟斗
 a| 
此作業會建立新的儲存桶。建立貯體後、您就成為了貯體的擁有者。

* 庫位名稱必須符合下列規則：
+
** 必須在各個StorageGRID 方面都是獨一無二的（不只是租戶帳戶內的獨特功能）。
** 必須符合DNS規範。
** 必須包含至少3個字元、且不得超過63個字元。
** 可以是一或多個標籤的系列、相鄰的標籤以句點分隔。每個標籤都必須以英文字母或數字開頭和結尾、而且只能使用英文字母、數字和連字號。
** 不得看起來像是文字格式的IP位址。
** 不應在虛擬託管樣式要求中使用期間。期間會導致伺服器萬用字元憑證驗證發生問題。


* 根據預設、會在「us-east-1」區域建立貯體、不過您可以在要求主體中使用「LocationConstraint」要求元素來指定不同的區域。使用「LocationConstraint」元素時、您必須指定已使用Grid Manager或Grid Management API定義的確切區域名稱。如果您不知道應該使用的地區名稱、請聯絡系統管理員。
+
*附註*：如果您的Pet Bucket要求使用StorageGRID 未在功能區中定義的區域、就會發生錯誤。

* 您可以加入「X-amz-Bucket物件鎖定」要求標頭、以建立啟用S3物件鎖定的儲存區。請參閱 xref:../s3/using-s3-object-lock.adoc[使用S3物件鎖定]。
+
建立儲存區時、您必須啟用S3物件鎖定。建立儲存區之後、您無法新增或停用S3物件鎖定。S3物件鎖定需要儲存區版本管理、這會在您建立儲存區時自動啟用。





 a| 
放入庫位
 a| 
此作業會設定儲存區的CORS組態、以便儲存區能夠處理跨來源要求。跨來源資源共用（CORS）是一種安全機制、可讓單一網域中的用戶端Web應用程式存取不同網域中的資源。例如、假設您使用名為「imag像」的S3儲存區來儲存圖形。設定「映像」儲存區的CORS組態、即可讓該儲存區中的映像顯示在網站上。+http://www.example.com+`



 a| 
使用資源桶加密
 a| 
此作業會設定現有儲存區的預設加密狀態。啟用桶層級加密時、任何新增至桶的新物件都會加密。StorageGRID支援使用StorageGRID管理的金鑰進行伺服器端加密。指定伺服器端加密組態規則時、請將「SEAlgorithm」參數設為「AES256」、而不要使用「KMSmsterKeyID」參數。

如果物件上傳要求已指定加密（亦即、如果要求包含「x-amz-server端加密-*」要求標頭）、則會忽略儲存區預設加密組態。



 a| 
放入鏟斗生命週期
 a| 
此作業會為儲存庫建立新的生命週期組態、或取代現有的生命週期組態。在生命週期組態中、支援多達1、000個生命週期規則。StorageGRID每個規則可包含下列XML元素：

* 到期日（天數、日期）
* 非目前版本過期（非目前日期）
* 篩選器（前置、標記）
* 狀態
* ID


不支援下列動作：StorageGRID

* AbortIncompleteMultiPart上 傳
* ExpiredObjectDelete標記
* 移轉


若要瞭解儲存庫生命週期中的到期行動如何與ILM放置指示互動、請參閱資訊生命週期管理物件說明中的「ILM在物件生命週期內的運作方式」。

*附註*：鏟斗生命週期組態可搭配已啟用S3物件鎖定的鏟斗使用、但舊型符合標準的鏟斗不支援鏟斗生命週期組態。



 a| 
放置時段通知
 a| 
此作業會使用要求內文所含的通知組態XML來設定儲存區的通知。您應該瞭解下列實作詳細資料：

* 支援簡單通知服務（SNS）主題作為目的地。StorageGRID不支援簡單佇列服務（SQS）或Amazon Lambda端點。
* 通知的目的地必須指定為StorageGRID 一個端點的URN。端點可以使用租戶管理程式或租戶管理API來建立。
+
端點必須存在、通知組態才能成功。如果端點不存在、則會傳回「400 Bad Request」錯誤、並顯示「InvalidArgument」代碼。

* 您無法設定下列事件類型的通知。這些事件類型*不支援*。
+
** 'S 3：ReducedRedundancyLostObject'
** 「s 3：ObjectRestore：completed」


* 從Suse傳送的事件通知StorageGRID 會使用標準Json格式、但不包含某些金鑰、而且會針對其他金鑰使用特定值、如下列清單所示：
* *事件來源*
+
"gws:s3"

* * awsRegion *
+
不含

* * X-amz-id-2*
+
不含

* * arn*
+
「urn:sgws:s3：：bucket_name」





 a| 
資源桶政策
 a| 
此作業會設定附加至庫位的原則。



 a| 
放入資源桶複寫
 a| 
此作業會使用StorageGRID 要求本文中提供的複寫組態XML、為儲存區設定「CloudMirror複寫」。對於CloudMirror複寫、您應該瞭解下列實作詳細資料：

* 僅支援複寫組態的V1。StorageGRID這表示StorageGRID 、由於不支援使用「Filter」元素來執行規則、因此遵循V1慣例來刪除物件版本。如需詳細資訊、請參閱 https://docs.aws.amazon.com/AmazonS3/latest/userguide/replication-add-config.html["有關複寫組態的Amazon S3文件"^]。
* 儲存區複寫可在版本控制或未版本控制的儲存區上進行設定。
* 您可以在複寫組態XML的每個規則中指定不同的目的地儲存區。來源儲存區可複寫至多個目的地儲存區。
* 目的地貯體必須指定為StorageGRID 租戶管理程式或租戶管理API中指定的非功能性端點的URN。
+
複寫組態必須存在端點才能成功。如果端點不存在、則要求會以「400個不良要求」的形式失敗。錯誤訊息顯示：「無法儲存複寫原則。指定的端點URN不存在：_URN_.'

* 您不需要在組態XML中指定「角色」。此值不供StorageGRID Some使用、如果提交、將會忽略此值。
* 如果您從組態XML中省略儲存類別、StorageGRID 則根據預設、功能不一定會使用「標準」儲存類別。
* 如果您從來源儲存區刪除物件、或是刪除來源儲存區本身、跨區域複寫行為如下：
+
** 如果您在複寫物件或儲存區之前先將其刪除、則不會複寫物件/儲存區、也不會通知您。
** 如果您在複寫物件或儲存區之後將其刪除、StorageGRID 則針對跨區域複寫的V1、執行標準Amazon S3刪除行為。






 a| 
置入庫位標記
 a| 
此作業使用「標記」子資源來新增或更新一組桶的標記。新增庫位標記時、請注意下列限制：

* 支援每個儲存區最多50個標籤的支援功能包括：StorageGRID
* 與庫位關聯的標記必須具有唯一的標記金鑰。標籤金鑰長度最多可達128個UNICODE字元。
* 標記值長度最多可達256個UNICODE字元。
* 金鑰和值區分大小寫。




 a| 
放入資源桶版本管理
 a| 
此實作會使用「資料夾」子資源來設定現有儲存區的版本管理狀態。您可以使用下列其中一個值來設定版本設定狀態：

* 已啟用：啟用儲存區中物件的版本管理。新增至儲存庫的所有物件都會收到唯一的版本ID。
* 暫停：停用儲存區中物件的版本設定。所有新增至儲存庫的物件都會收到版本ID「null」。




 a| 
放置物件鎖定組態
 a| 
此作業會設定或移除庫位預設保留模式和預設保留期間。

如果修改了預設保留期間、現有物件版本的保留截止日期將維持不變、且不會使用新的預設保留期間重新計算。

請參閱 xref:../s3/use-s3-object-lock-default-bucket-retention.adoc#put-object-lock-configuration[放置物件鎖定組態] 以取得詳細資訊。

|===
xref:consistency-controls.adoc[一致性控管]

xref:get-bucket-last-access-time-request.adoc[取得時段上次存取時間要求]

xref:bucket-and-group-access-policies.adoc[儲存庫和群組存取原則]

xref:s3-operations-tracked-in-audit-logs.adoc[在稽核記錄中追蹤S3作業]

xref:../ilm/index.adoc[使用ILM管理物件]

xref:../tenant/index.adoc[使用租戶帳戶]
