---
permalink: s3/operations-for-multipart-uploads.html 
sidebar: sidebar 
keywords: operations, multipart uploads, uploads, rest API 
summary: 本節說明StorageGRID 此功能如何支援多部份上傳作業。 
---
= 多部份上傳作業
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
本節說明StorageGRID 此功能如何支援多部份上傳作業。

下列條件與附註適用於所有多重部分上傳作業：

* 您不應超過1、000次同時將多個部分上傳至單一儲存庫、因為針對該儲存庫列出多個部分上傳查詢的結果可能會傳回不完整的結果。
* 針對多個零件執行AWS大小限制。StorageGRIDS3用戶端必須遵循下列準則：
+
** 多部份上傳的每個部分必須介於5個mib（5、242,880位元組）和5 GiB（5、368,709,120位元組）之間。
** 最後一部分可小於5個mib（5、242,880位元組）。
** 一般而言、零件尺寸應盡量大。例如、對於100 GiB物件使用5 GiB的零件大小。由於每個零件都被視為獨特的物件、因此使用大尺寸的零件可減少StorageGRID 元資料負荷。
** 對於小於5 GiB的物件、請考慮改用非多部份上傳。


* 如果ILM規則使用嚴格或平衡的擷取行為、則會針對多部分物件的每個部分進行ILM評估、並在多部分上傳完成時、針對整個物件進行ILM評估。您應該瞭解這會如何影響物件和零件放置：
+
** 如果在S3多部份上傳進行期間ILM發生變更、則當多部份上傳完成物件的部分時、可能無法符合目前的ILM需求。未正確放置的任何零件都會排入ILM重新評估佇列、稍後會移至正確位置。
** 評估零件的ILM時StorageGRID 、會根據零件大小而非物件大小來篩選。這表示物件的部分可儲存在不符合整個物件ILM需求的位置。例如、如果規則指定所有10 GB或更大的物件都儲存在DC1、而所有較小的物件則儲存在DC2、則在10部分多部分上傳的每1 GB擷取部分、都會儲存在DC2。當針對整個物件評估ILM時、物件的所有部分都會移至DC1。


* 所有的多部份上傳作業都支援StorageGRID 不一致的控管功能。
* 視需要、您可以使用伺服器端加密來上傳多個部分。若要使用SSe（使用StorageGRID管理金鑰的伺服器端加密）、您只能在「初始化多重部分上傳」要求中加入「x-amz-server端加密」要求標頭。若要使用SSE-C（使用客戶提供的金鑰進行伺服器端加密）、您可以在「初始化多部份上傳」要求和後續每個「上傳零件」要求中、指定相同的三個加密金鑰要求標頭。


|===
| 營運 | 實作 


 a| 
列出多個部分上傳
 a| 
請參閱 xref:list-multipart-uploads.adoc[列出多個部分上傳]



 a| 
啟動多部份上傳
 a| 
請參閱 xref:initiate-multipart-upload.adoc[啟動多部份上傳]



 a| 
上傳零件
 a| 
請參閱 xref:upload-part.adoc[上傳零件]



 a| 
上傳零件-複製
 a| 
請參閱 xref:upload-part-copy.adoc[上傳零件-複製]



 a| 
完成多部份上傳
 a| 
請參閱 xref:complete-multipart-upload.adoc[完成多部份上傳]



 a| 
中止多部份上傳
 a| 
以所有Amazon S3 REST API行為來實作



 a| 
列出零件
 a| 
以所有Amazon S3 REST API行為來實作

|===
.相關資訊
* xref:consistency-controls.adoc[一致性控管]
* xref:using-server-side-encryption.adoc[使用伺服器端加密]

