---
permalink: s3/put-object.html 
sidebar: sidebar 
keywords: object, add object, put, put object request 
summary: 您可以使用S3放置物件要求、將物件新增至儲存區。 
---
= 放置物件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用S3放置物件要求、將物件新增至儲存區。



== 解決衝突

衝突的用戶端要求（例如兩個寫入同一個金鑰的用戶端）會以「最新致勝」的方式解決。「最新致勝」評估的時間取決於StorageGRID 何時由VMware系統完成指定的要求、而非S3用戶端開始作業的時間。



== 物件大小

單一放置物件作業的最大_Recommended大小為5 GiB（5、368、709、120位元組）。如果您的物件大於5 GiB、請改用多部份上傳。


IMPORTANT: 在S2011.6中StorageGRID 、單一放置物件作業的最大_supported大小為5 TiB（5、497、558、13880位元組）。但是、如果您嘗試上傳超過5 GiB的物件、則會觸發* S3「Pure Object size too large *（將物件大小設為太大*）」警示。



== 使用者中繼資料大小

Amazon S3會將每個PUT要求標頭內使用者定義的中繼資料大小限制為2 KB。支援範圍將使用者中繼資料限制為24 KiB。StorageGRID使用者定義的中繼資料大小是以每個金鑰和值的utf-8編碼方式、計算出位元組數的總和。



== 使用者中繼資料中的UTF-8字元

如果要求在使用者定義的中繼資料金鑰名稱或值中包含（未轉義）utf-8值、StorageGRID 則無法定義任何不正常的行為。

不剖析或解譯使用者定義之中繼資料的金鑰名稱或值中包含的轉義式utf-8字元。StorageGRID轉義的UTF-8字元會視為Ascii字元：

* 如果使用者定義的中繼資料包含轉義的UTF-8字元、則放置、放置物件複製、取得和標頭要求都會成功。
* 如果關鍵字名稱或值的解譯值包含不可列印的字元、則不傳回「x-amz-misse-meta」標頭。StorageGRID




== 物件標籤限制

您可以在上傳新物件時新增標記、也可以將標記新增至現有物件。每個物件最多可支援10個標記的支援功能。StorageGRID與物件相關聯的標記必須具有唯一的標記金鑰。標籤金鑰長度最多可達128個UNICODE字元、標籤值長度最多可達256個UNICODE字元。金鑰和值區分大小寫。



== 物件擁有權

在功能區中StorageGRID 、所有物件均歸庫位擁有者帳戶所有、包括非擁有者帳戶或匿名使用者所建立的物件。



== 支援的要求標頭

支援下列要求標頭：

* 「快取控制」
* 「內容處理」
* 「內容編碼」
+
當您為「Content-Encoding」指定「AWS/chunked」時、「儲存設備GRID」不會驗證下列項目：

+
** 不驗證區塊資料的「區塊簽章」StorageGRID 。
** 不驗證您針對物件提供的「X-amz-解碼內容長度」值。StorageGRID


* 《內容-語言》
* 《內容長度》
* 《Content-MD5》
* 「內容類型」
* 《過期》
* 「傳輸編碼」
+
如果也使用「AWS/chunked」有效負載簽署、則支援chunked傳輸編碼。

* 「x-amz-meta-」、接著是包含使用者定義中繼資料的名稱值配對。
+
為使用者定義的中繼資料指定名稱值配對時、請使用以下一般格式：

+
[listing, subs="specialcharacters,quotes"]
----
x-amz-meta-_name_: _value_
----
+
如果您要使用*使用者定義的建立時間*選項做為ILM規則的參考時間、則必須使用「建立時間」做為建立物件時記錄的中繼資料名稱。例如：

+
[listing]
----
x-amz-meta-creation-time: 1443399726
----
+
自70年1月1日起、「創造時間」的值會以秒計算。

+

NOTE: ILM規則無法同時使用*使用者定義的建立時間*作為參考時間、以及用於擷取行為的平衡或嚴格選項。建立ILM規則時會傳回錯誤。

* 「X-amz-標記」
* S3物件鎖定要求標頭
+
** 「X-amz-object-lock-mode」
** 《X-amz-object-lock-Retain直到日期》
** 「X-amz-object-lock-legal hold」
+
如果提出的要求沒有這些標頭、則會使用儲存庫預設保留設定來計算物件版本的保留日期。

+
xref:using-s3-object-lock.adoc[使用S3物件鎖定]



* SSe要求標頭：
+
** 「X-amz-server端點加密」
** 「X-amz-server端加密- customer-key-md5」
** 「X-amz-server端加密客戶金鑰」
** 「X-amz-server端加密- customer-演算 法」
+
請參閱 <<Request headers for server-side encryption>>







== 不支援的要求標頭

不支援下列要求標頭：

* 不支援「x-amz-acl」要求標頭。
* 不支援「x-amz-website - redirect-location」要求標頭、並傳回「XNotImplemed」。




== 儲存類別選項

支援「x-amz-storage -Class」要求標頭。提交給「x-amz-Storage-Class」的值、會影響StorageGRID 到在擷取期間、如何保護物件資料、以及StorageGRID 不需要將物件的持續複本儲存在包含在ILM系統中的數量。

如果符合擷取物件的ILM規則使用擷取行為的嚴格選項、則「x-amz-Storage-Class」標頭不會有任何影響。

下列值可用於「x-amz-storage類別」：

* 「標準」（預設）
+
** *雙重提交*：如果ILM規則指定「內嵌行為」的「雙重提交」選項、則只要物件擷取到另一個物件複本、就會建立該物件的第二個複本、並將其分散到不同的儲存節點（雙重提交）。評估ILM時、StorageGRID會判斷這些初始過渡複本是否符合規則中的放置指示。如果沒有、可能需要在不同位置建立新的物件複本、而且可能需要刪除初始的過渡複本。
** *平衡*：如果ILM規則指定平衡選項、StorageGRID 且無法立即製作規則中指定的所有複本、StorageGRID 則在不同的儲存節點上製作兩份臨時複本。
+
如果能夠立即建立ILM規則（同步放置）中指定的所有物件複本、「x-amz-Storage-Class」標頭就不會有任何影響。StorageGRID



* "educed_deete"
+
** *雙重提交*：如果ILM規則指定擷取行為的雙重提交選項、StorageGRID 則會在擷取物件時建立單一的過渡複本（單一提交）。
** *平衡*：如果ILM規則指定平衡選項、StorageGRID 則僅當系統無法立即製作規則中指定的所有複本時、才能製作單一的過渡複本。如果能夠執行同步放置、則此標頭不會有任何影響。StorageGRID當符合物件的ILM規則建立單一複寫複本時、最適合使用「已儲存的備援」選項。在這種情況下、使用「reduced_dere通用」可免除每次擷取作業不必要地建立和刪除額外的物件複本。


+
在其他情況下、不建議使用「已儲存的備援」選項。「已導入的備援」會增加擷取期間物件資料遺失的風險。例如、如果單一複本一開始儲存在無法進行ILM評估的儲存節點上、則可能會遺失資料。



*注意*：在任何時間段內只有一個複寫複本、會使資料面臨永久遺失的風險。如果只有一個物件複寫複本存在、則當儲存節點故障或發生重大錯誤時、該物件就會遺失。在升級等維護程序期間、您也會暫時失去物件的存取權。

指定「已儲存的備援」僅會影響第一次擷取物件時所建立的複本數量。它不會影響使用中ILM原則評估物件時所製作的物件複本數量、也不會導致資料儲存在StorageGRID 較低層級的資料冗餘環境中。

*附註*：如果您在啟用S3物件鎖定的情況下、將物件放入儲存區、則會忽略「已傳入的備援」選項。如果您將物件放入符合舊規範的儲存區、則「educed_de隊」選項會傳回錯誤。執行「雙重承諾」的程序時、務必確保符合法規遵循要求。StorageGRID



== 要求伺服器端加密的標頭

您可以使用下列要求標頭、以伺服器端加密來加密物件。「SSE」和「SSE-C」選項互不相關。

* * SSE-*：如果您想使用StorageGRID 由支援的唯一金鑰來加密物件、請使用下列標頭。
+
** 「X-amz-server端點加密」


* * SSE-C*：如果您想使用您提供及管理的唯一金鑰來加密物件、請使用這三個標頭。
+
** 「X-amz-server端加密客戶演算法」：指定「AES256」。
** 「X-amz-server端加密客戶金鑰」：指定新物件的加密金鑰。
** 「X-amz-server端加密- customer-key-md5」：指定新物件加密金鑰的md5摘要。




*注意：*您提供的加密金鑰永遠不會儲存。如果您遺失加密金鑰、就會遺失對應的物件。在使用客戶提供的金鑰來保護物件資料之前、請先檢閱「使用伺服器端加密」中的考量事項。

*附註：*如果物件是以SSE或SSE-C加密、則會忽略任何儲存區層級或網格層級的加密設定。



== 版本管理

如果已針對儲存區啟用版本管理、系統會針對儲存的物件版本自動產生唯一的「版本ID」。此「版本ID」也會在回應中使用「x-amz-version -id」回應標頭傳回。

如果版本控制暫停、則物件版本會以null「VrionId」儲存、如果null版本已經存在、則會覆寫該版本。

xref:../ilm/index.adoc[使用ILM管理物件]

xref:operations-on-buckets.adoc[在貯體上作業]

xref:s3-operations-tracked-in-audit-logs.adoc[在稽核記錄中追蹤S3作業]

xref:using-server-side-encryption.adoc[使用伺服器端加密]

xref:configuring-tenant-accounts-and-connections.adoc[如何設定用戶端連線]
