---
permalink: monitor/using-snmp-monitoring.html 
sidebar: sidebar 
keywords: snmp, monitoring 
summary: 如果您想StorageGRID 要使用簡易網路管理傳輸協定（SNMP）監控效能、您必須設定StorageGRID 包含在更新中的SNMP代理程式。 
---
= 使用SNMP監控
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您想StorageGRID 要使用簡單網路管理傳輸協定（SNMP）監控效能、您必須設定StorageGRID 包含在資訊區中的SNMP代理程式。

* xref:configuring-snmp-agent.adoc[設定SNMP代理程式]
* xref:updating-snmp-agent.adoc[更新SNMP代理程式]




== 功能

每StorageGRID 個支援節點都會執行SNMP代理程式或精靈、以提供管理資訊庫（mib）。此功能包含警示和警示的表格和通知定義。StorageGRID此外、也包含系統說明資訊、例如每個節點的平台和型號。每StorageGRID 個支援MIB-II物件的子集。

一開始、所有節點上的SNMP都會停用。當您設定SNMP代理程式時、所有StorageGRID 的Sing節點都會收到相同的組態。

支援所有三種版本的SNMP傳輸協定的Sof SNMP代理程式。StorageGRID它可為查詢提供唯讀的MIB存取、並可將兩種事件導向通知傳送至管理系統：

* * Trap*是SNMP代理程式傳送的通知、不需要管理系統確認。陷阱可讓管理系統知道StorageGRID 在某些情況下發生、例如觸發警示。
+
SNMP的所有三個版本均支援陷阱。

* *通知*類似於陷阱、但需要管理系統確認。如果SNMP代理程式在一定時間內未收到確認訊息、則會重新傳送通知、直到收到確認訊息或達到最大重試值為止。
+
在SNMPv2c和v3中支援通知。



在下列情況下會傳送陷阱和通知：

* 預設或自訂警示會在任何嚴重性層級觸發。若要隱藏警示的SNMP通知、您必須設定警示的靜音。警示通知是由任何設定為偏好傳送者的管理節點所傳送。
+
每個警示都會根據警示的嚴重性層級、對應到三種陷阱類型中的一種：activeMinorAlert、activeMajorAlert和activeCriticalAlert。如需可觸發這些陷阱的警示說明、請參閱 xref:alerts-reference.adoc[警示參考資料]。

* 某些警示（舊系統）會在指定的嚴重性等級或更高的等級觸發。
+

NOTE: SNMP通知不會針對每個警示或每個警示嚴重性傳送。





== SNMP版本支援

下表提供每個SNMP版本所支援項目的高層摘要。

|===
|  | SNMPv1 | SNMPv2c | v3 


 a| 
查詢
 a| 
唯讀的mib查詢
 a| 
唯讀的mib查詢
 a| 
唯讀的mib查詢



 a| 
查詢驗證
 a| 
社群字串
 a| 
社群字串
 a| 
使用者型安全模式（USM）使用者



 a| 
通知
 a| 
僅設陷
 a| 
擷取並通知
 a| 
擷取並通知



 a| 
通知驗證
 a| 
每個陷阱目的地的預設陷阱社群或自訂社群字串
 a| 
每個陷阱目的地的預設陷阱社群或自訂社群字串
 a| 
每個陷阱目的地的USM使用者

|===


== 限制

* 支援唯讀的mib存取。StorageGRID不支援讀寫存取。
* 網格中的所有節點都會收到相同的組態。
* v3：StorageGRID 不支援傳輸支援模式（TSM）。
* v3：唯一支援的驗證傳輸協定是SHa（HMAC - SHA-96）。
* v3：唯一支援的隱私權傳輸協定是AES。




== 存取MIB

您可以在StorageGRID 任何節點的下列位置存取mib定義檔案：

usr/share/SNMP / MIBs/NetApp-STORAGEGRID-MIB.txt'

.相關資訊
* xref:alerts-reference.adoc[警示參考資料]
* xref:alarms-reference.adoc[警示參考（舊系統）]
* xref:alarms-that-generate-snmp-notifications.adoc[產生SNMP通知的警示（舊系統）]
* xref:silencing-alert-notifications.adoc[靜音警示通知]

