---
permalink: maintain/configuring-ntp-servers.html 
sidebar: sidebar 
keywords: storagegrid, ntp, ntp server, configure ntp, configuring ntp 
summary: 您可以新增、更新或移除網路時間傳輸協定（NTP）伺服器、以確保資料在StorageGRID 您的系統的網格節點之間正確同步。 
---
= 設定NTP伺服器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以新增、更新或移除網路時間傳輸協定（NTP）伺服器、以確保StorageGRID 資料在您的BIOS系統的網格節點之間正確同步。

.您需要的是 #8217 ；需要的是什麼
* 您必須使用登入Grid Manager xref:../admin/web-browser-requirements.adoc[支援的網頁瀏覽器]。
* 您必須具有維護或根存取權限。
* 您必須擁有資源配置通關密碼。
* 您必須擁有要設定的NTP伺服器的IPV4位址。


此系統使用網路時間傳輸協定（NTP）、在網格中的所有網格節點之間同步時間。StorageGRID

在每個站台StorageGRID 、至少有兩個節點被指派主要的NTP角色。它們會同步處理至建議的最少四個外部時間來源、最多六個外部時間來源、並彼此同步。非主要NTP節點的StorageGRID 每個節點都會做為NTP用戶端、並與這些主要NTP節點同步。

外部NTP伺服器會連線至先前指派主要NTP角色的節點。因此、建議至少指定兩個具有主要NTP角色的節點。


IMPORTANT: 請確定每個站台至少有兩個節點可以存取至少四個外部NTP來源。如果站台只有一個節點可以連線至NTP來源、則當該節點當機時、就會發生計時問題。此外、將每個站台的兩個節點指定為主要NTP來源、可確保站台與網格的其他部分隔離時、能確保準確的時間安排。

指定的外部NTP伺服器必須使用NTP傳輸協定。您必須指定階層3或更高層級的NTP伺服器參考資料、以避免時間浪費問題。


NOTE: 指定外部NTP來源進行正式作業層級StorageGRID 的安裝時、請勿在Windows Server 2016之前的Windows版本上使用Windows Time（W32Time）服務。舊版Windows上的時間服務不夠準確、Microsoft不支援在StorageGRID 高準確度環境中使用、例如：

https://support.microsoft.com/en-us/help/939322/support-boundary-to-configure-the-windows-time-service-for-high-accura["支援邊界、可針對高準確度環境設定Windows時間服務"^]

如果您在安裝期間遇到最初指定NTP伺服器的穩定性或可用度問題、您可以StorageGRID 新增其他伺服器、或更新或移除現有伺服器、以更新該系統使用的外部NTP來源清單。

.步驟
. 選擇*維護*>*網路*>* NTP伺服器*。
. 視需要在「伺服器」區段中新增更新或移除NTP伺服器項目。
+
您應至少包含4部NTP伺服器、最多可指定6部伺服器。

. 在* Provisioning Passphrase（*配置密碼）*文字方塊中、輸入StorageGRID 您的供應密碼、然後按一下* Save*。
+
程序狀態會顯示在頁面頂端。頁面會停用、直到組態更新完成為止。

+

IMPORTANT: 如果所有NTP伺服器在您儲存新的NTP伺服器之後都未通過連線測試、請勿繼續。聯絡技術支援。


