---
permalink: maintain/considerations-and-requirements-for-appliance-node-cloning.html 
sidebar: sidebar 
keywords: storagegrid, clone appliance node, cloning appliance node 
summary: 在複製應用裝置節點之前、您必須先瞭解考量事項與需求。 
---
= 應用裝置節點複製的考量與要求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在複製應用裝置節點之前、您必須先瞭解考量事項與需求。



== 更換應用裝置的硬體需求

確保更換設備符合下列條件：

* 來源節點（正在更換的應用裝置）和目標（新）應用裝置必須是相同類型的應用裝置：
+
** 您只能將管理節點應用裝置或閘道節點應用裝置複製到新的服務應用裝置。
** 您只能將儲存節點應用裝置複製到新的儲存應用裝置。


* 對於管理節點或閘道節點應用裝置、來源節點應用裝置和目標應用裝置不需要是相同類型的應用裝置、但是變更應用裝置類型可能需要更換纜線或SFP模組。
+
例如、您可以用SG100來取代SG1000節點應用裝置、或是用SG1000應用裝置來取代SG100應用裝置。

* 對於儲存節點應用裝置、來源節點應用裝置和目標應用裝置不需要是相同類型的應用裝置、但是目標應用裝置的儲存容量必須大於來源應用裝置。
+
例如、您可以將SG5600節點應用裝置更換為SG5700或SG6000應用裝置。



請聯絡StorageGRID 您的銷售代表、以協助您選擇相容的替換設備、以便在StorageGRID 安裝時複製特定的應用裝置節點。



== 準備複製應用裝置節點

在複製應用裝置節點之前、您必須具備下列資訊：

* 從網路管理員處取得網格網路的暫用IP位址、以便在初始安裝期間與目標應用裝置搭配使用。如果來源節點屬於管理網路或用戶端網路、請取得這些網路的暫用IP位址。
+
暫用IP位址通常與要複製的來源節點應用裝置位於同一子網路、複製完成後不再需要。來源和目標應用裝置必須同時連線StorageGRID 至您的支援區的主要管理節點、才能建立複製連線。

* 判斷要用於複製資料傳輸流量的網路、以提供最佳的資料傳輸效能、而不會降低StorageGRID 網路效能或資料可用度。
+

NOTE: 使用1-GbE管理網路進行複製資料傳輸、會導致複製速度變慢。

* 判斷目標應用裝置是否會使用金鑰管理伺服器（KMS）進行節點加密、以便在初始目標應用裝置安裝期間啟用節點加密、然後再進行複製。您可以檢查來源應用裝置節點是否已啟用節點加密、如應用裝置安裝所述。
+
來源節點和目標應用裝置可以有不同的節點加密設定。資料解密與加密會在資料傳輸期間、以及當目標節點重新啟動並加入網格時自動執行。

+
** xref:../sg100-1000/index.adoc[SG100與SG1000服務應用裝置]
** xref:../sg5600/index.adoc[SG5600儲存設備]
** xref:../sg5700/index.adoc[SG5700儲存設備]
** xref:../sg6000/index.adoc[SG6000儲存設備]


* 判斷目標應用裝置上的RAID模式是否應從預設設定變更、以便在複製前於初始目標應用裝置安裝期間指定此資訊。您可以在Grid Manager的「*節點*」頁面上、檢視來源應用裝置節點目前RAID模式的相關資訊。選取應用裝置的「*儲存設備*」索引標籤。
+
來源節點和目標應用裝置可以有不同的RAID設定。

* 規劃足夠的時間來完成節點複製程序。可能需要數天的時間、才能將資料從運作中的儲存節點傳輸到目標應用裝置。排定複製時間、將對貴企業的影響降至最低。
* 一次只能複製一個應用裝置節點。複製可防止您StorageGRID 同時執行其他的還原維護功能。
* 複製應用裝置節點之後、您可以使用返回預先安裝狀態的來源應用裝置做為目標、來複製另一個相容的節點應用裝置。

