---
permalink: maintain/how-appliance-node-cloning-works.html 
sidebar: sidebar 
keywords: storagegrid, appliance node cloning, appliance node clone 
summary: 應用裝置節點複製功能可讓您輕鬆地將網格中現有的應用裝置節點（來源）更換為同一個邏輯StorageGRID 版本的相容應用裝置（目標）。此程序會將所有資料傳輸至新應用裝置、並將其置於服務狀態、以更換舊應用裝置節點、並使舊應用裝置保持預先安裝狀態。 
---
= 應用裝置節點複製的運作方式
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
應用裝置節點複製功能可讓您輕鬆地將網格中現有的應用裝置節點（來源）更換為同StorageGRID 一個邏輯版本的相容應用裝置（目標）。此程序會將所有資料傳輸至新應用裝置、並將其置於服務狀態、以更換舊應用裝置節點、並使舊應用裝置保持預先安裝狀態。



== 為何要複製應用裝置節點？

如果需要：

* 更換即將停產的設備。
* 升級現有節點、以善用改良的應用裝置技術。
* 增加網格儲存容量、而不需變更StorageGRID 您的一套系統中的儲存節點數量。
* 改善儲存效率、例如將RAID模式從DDA-8變更為DDA-16、或變更為RAID-6。
* 有效實作節點加密、以允許使用外部金鑰管理伺服器（KMS）。




== 使用哪StorageGRID 一個呢？

複製可透過StorageGRID 任一項功能、將資料從來源節點直接傳輸至目標應用裝置。網格網路通常會使用、但如果來源應用裝置連線至這些網路、您也可以使用管理網路或用戶端網路。選擇用於複製流量的網路、以提供最佳資料傳輸效能、而不會降低StorageGRID 網路效能或資料可用度。

安裝替換應用裝置時、您必須指定暫時性的IP位址、以便StorageGRID 進行鏈接和資料傳輸。由於更換的應用裝置將與所取代的應用裝置節點屬於同一個網路、因此您必須在更換的應用裝置上、為每個網路指定暫用IP位址。



== 目標應用裝置相容性

更換設備必須與要更換的來源節點類型相同、而且兩者都必須屬於同一個邏輯StorageGRID 版的站台。

* 替換服務應用裝置可能與所取代的管理節點或閘道節點不同。
+
** 您可以將SG100來源節點應用裝置複製到SG1000服務目標應用裝置、讓管理節點或閘道節點擁有更大的功能。
** 您可以將SG1000來源節點應用裝置複製到SG100服務目標應用裝置、以便重新部署SG1000以滿足更嚴苛的應用程式需求。
+
例如、如果SG1000來源節點應用裝置做為管理節點、而您想要將其用作專屬的負載平衡節點。

** 以SG100服務目標應用裝置取代SG1000來源節點應用裝置、可將網路連接埠的最大速度從100-GbE降低至25-GbE。
** SG100和SG1000設備具有不同的網路連接器。變更應用裝置類型可能需要更換纜線或SFP模組。


* 替換儲存設備的容量必須等於或大於其所取代的儲存節點。
+
** 如果目標儲存設備的磁碟機數量與來源節點相同、則目標應用裝置中的磁碟機容量必須更大（以 TB 為單位）。
** 如果您打算在目標節點上使用與來源節點相同的RAID模式、 或是儲存效率較低的RAID模式（例如從RAID6切換至DDP）、目標應用裝置中的磁碟機必須大於來源應用裝置中的磁碟機（以TB為限）。
** 如果目標儲存應用裝置中安裝的標準磁碟機數量低於來源節點中的磁碟機數量、則目標應用裝置中的標準磁碟機總儲存容量（以TB為單位） 必須符合或超過來源儲存節點中所有磁碟機的功能磁碟機總容量。
+
例如、將具有60個磁碟機的SG5660來源儲存節點應用裝置複製到具有58個標準磁碟機的SG6060或SG6060X目標應用裝置時、應先在SG6060或SG60X目標應用裝置中安裝較大的磁碟機、再進行複製以維持儲存容量。（目標應用裝置中包含SSD的兩個磁碟機插槽、並未包含在設備總儲存容量中。）

+
不過、如果60個磁碟機SG5660來源節點應用裝置設定SANtricity 有「動態磁碟集區」DDA-8、則使用DDA-16設定58個磁碟機大小相同的SG6060或SG60X目標應用裝置、可能會使SG6060或SG60X應用裝置成為有效的複製目標、因為其儲存效率提升。

+
您可以在Grid Manager的「*節點*」頁面上、檢視來源應用裝置節點目前RAID模式的相關資訊。選取應用裝置的「*儲存設備*」索引標籤。







== 哪些資訊未複製？

下列應用裝置組態不會在複製期間傳輸至替換應用裝置。您必須在更換應用裝置的初始設定期間進行設定。

* BMC介面
* 網路連結
* 節點加密狀態
* 系統管理程式（適用於儲存節點）SANtricity
* RAID模式（適用於儲存節點）




== 哪些問題會妨礙複製？

如果在複製時遇到下列任何問題、複製程序會停止、並產生錯誤訊息：

* 網路組態錯誤
* 來源設備與目標設備之間缺乏連線能力
* 來源與目標應用裝置不相容
* 儲存節點是容量不足的替換應用裝置


您必須解決複製的每個問題才能繼續。
