---
permalink: maintain/linux-adding-interfaces-to-existing-node.html 
sidebar: sidebar 
keywords: add interfaces, add client network interface, add admin network interface 
summary: 請使用這些步驟、在安裝管理網路或用戶端網路之後、將介面新增至Linux節點。 
---
= Linux：將管理或用戶端介面新增至現有節點
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
請使用這些步驟、在安裝管理網路或用戶端網路之後、將介面新增至Linux節點。

如果您在安裝期間未在Linux主機上的節點組態檔中設定admin_network_target或client_network_target、請使用此程序來新增介面。如需節點組態檔的詳細資訊、請參閱Linux作業系統的相關指示：

* xref:../rhel/index.adoc[安裝Red Hat Enterprise Linux或CentOS]
* xref:../ubuntu/index.adoc[安裝Ubuntu或DEBIAN]


您可以在裝載需要新網路指派之節點的Linux伺服器上執行此程序、而非在節點內部執行。此程序僅會將介面新增至節點；如果您嘗試指定任何其他網路參數、則會發生驗證錯誤。

若要提供定址資訊、您必須使用變更IP工具。請參閱 xref:changing-nodes-network-configuration.adoc[變更節點網路組態]。

.步驟
. 登入裝載節點的Linux伺服器。
. 編輯節點組態檔：「/etc/storagegrid / nodes/_noce-name_.conf」。
+

IMPORTANT: 請勿指定任何其他網路參數、否則將導致驗證錯誤。

+
.. 新增新網路目標的項目。例如：
+
"client_network_target = bond0.3206"

.. 選用：新增MAC位址項目。例如：
+
"client_network_MAC = aa:57:61:07:ea：5c"



. 執行節點驗證命令：
+
「Udo StorageGRID SURITY node-name_」驗證

. 解決所有驗證錯誤。
. 執行節點重新載入命令：
+
「Udo StorageGRID 節點重新載入_norme-name_」


