---
permalink: maintain/restoring-prometheus-metrics-primary-admin-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, restore metrics, restore prometheus, primary admin node 
summary: 或者、您可以將Prometheus維護的歷史數據保留在失敗的主要管理節點上。只有StorageGRID 當您的系統包含另一個管理節點時、才能還原Prometheus指標。 
---
= 恢復主管理節點時、請還原Prometheus指標
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
或者、您可以將Prometheus維護的歷史數據保留在失敗的主要管理節點上。只有StorageGRID 當您的系統包含另一個管理節點時、才能還原Prometheus指標。

* 恢復的管理節點必須安裝並執行。
* 這個系統必須至少包含兩個管理節點。StorageGRID
* 您必須擁有「passwors.txt」檔案。
* 您必須擁有資源配置通關密碼。


如果管理節點故障、管理節點上Prometheus資料庫中所維護的度量將會遺失。當您恢復管理節點時、軟體安裝程序會建立新的Prometheus資料庫。在恢復的管理節點啟動後、它會記錄指標、就像您已執行StorageGRID 全新的作業系統安裝一樣。

如果您還原了主管理節點、StorageGRID 且您的Estring系統有另一個管理節點、您可以將Prometheus資料庫從非主管理節點（_SOURUS管理節點）複製到恢復的主管理節點、以還原歷史指標。如果您的系統只有主要管理節點、則無法還原Prometheus資料庫。


NOTE: 複製Prometheus資料庫可能需要一小時以上的時間。當服務在來源管理節點上停止時、部分Grid Manager功能將無法使用。

. 登入來源管理節點：
+
.. 輸入下列命令：「sh admin@_grid_node_ip_`」
.. 輸入「passwords.txt」檔案中所列的密碼。
.. 輸入下列命令以切換至root：「u -」
.. 輸入「passwords.txt」檔案中所列的密碼。


. 從來源管理節點、停止Prometheus服務：「ervice Prometheus stop」
. 在恢復的管理節點上完成下列步驟：
+
.. 登入恢復的管理節點：
+
... 輸入下列命令：「sh admin@_grid_node_ip_`」
... 輸入「passwords.txt」檔案中所列的密碼。
... 輸入下列命令以切換至root：「u -」
... 輸入「passwords.txt」檔案中所列的密碼。


.. 停止Prometheus服務：「服務Prometheus停止」
.. 將SSH私密金鑰新增至SSH代理程式。輸入：「sh-add」
.. 輸入列在「P密碼」檔案中的SSH存取密碼。
.. 將Prometheus資料庫從來源管理節點複製到恢復的管理節點：「/usr/local/Prometheus/bin/prometheus-clone-db.sh Source_admin_Nod_IP」
.. 出現提示時、按* Enter *確認您要銷毀「恢復的管理節點」上的新Prometheus資料庫。
+
原始的Prometheus資料庫及其歷史資料會複製到恢復的管理節點。複製作業完成後、指令碼會啟動恢復的管理節點。此時會顯示下列狀態：

+
資料庫已複製、正在啟動服務

.. 當您不再需要無密碼存取其他伺服器時、請從SSH代理程式移除私密金鑰。輸入：'sh-add -d'


. 在來源管理節點上重新啟動Prometheus服務

