---
permalink: maintain/shutting-down-grid-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, node shutdown, shut down node, node shut down 
summary: 您可以從節點的命令Shell關閉網格節點。 
---
= 關閉網格節點
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以從節點的命令Shell關閉網格節點。

.您需要的是 #8217 ；需要的是什麼
* 您必須擁有「passwors.txt」檔案。


執行此程序之前、請先檢閱下列考量事項：

* 一般而言、您不應一次關閉多個節點、以免發生中斷。
* 除非文件或技術支援明確指示、否則請勿在維護程序期間關閉節點。
* 關機程序取決於節點的安裝位置、如下所示：
+
** 關閉VMware節點會關閉虛擬機器。
** 關閉Linux節點會關閉容器。
** 關閉StorageGRID 一個不中斷的應用程式節點會關閉運算控制器。


* 如果您打算關閉儲存節點、請注意下列事項：
+
** 如果ILM規則指定「雙重認可」的擷取行為、或規則指定「平衡」、而且無法立即建立所有必要的複本、StorageGRID 則由部門立即將任何新擷取的物件提交至同一站台上的兩個儲存節點、並於稍後評估ILM。如果您想要關閉特定站台上的兩個或多個儲存節點、在關機期間可能無法存取這些物件。
** 為了確保您可以在儲存節點關閉時存取所有物件、請在關閉節點之前、先停止在站台上擷取物件約一小時。




.步驟
. 登入網格節點：
+
.. 輸入下列命令：「sh admin@_grid_node_ip_`」
.. 輸入「passwords.txt」檔案中所列的密碼。
.. 輸入下列命令以切換至root：「u -」
.. 輸入「passwords.txt」檔案中所列的密碼。


+
以root登入時、提示會從「$」變更為「#」。

. 停止所有服務：「服務伺服器管理程式停止」
+
服務關機最多需要15分鐘、您可能想要從遠端登入系統、以監控關機程序。

. 如果節點是在VMware虛擬機器上執行、或是在應用裝置節點上執行、請發出關機命令：「hutdown -h NOW」
+
無論執行「服務伺服器管理程式停止」命令的結果為何、都要執行此步驟。

+

NOTE: 在應用裝置節點上發出「shutdown -h NOW」命令之後、您必須重新啟動應用裝置電源、才能重新啟動節點。

+
對於應用裝置、此命令會關閉控制器、但應用裝置仍會開啟電源。您必須完成下一步。

. 如果您要關閉應用裝置節點的電源：
+
** 適用於SG100或SG1000服務應用裝置
+
... 關閉產品電源。
... 等待藍色電源LED燈關閉。


** 適用於SG6000應用裝置
+
... 等待儲存控制器背面的綠色快取作用中LED關閉。
+
當需要將快取的資料寫入磁碟機時、此LED會亮起。您必須等待此LED燈關閉、才能關閉電源。

... 關閉產品電源、然後等待藍色電源LED燈關閉。


** 適用於SG5700應用裝置
+
... 等待儲存控制器背面的綠色快取作用中LED關閉。
+
當需要將快取的資料寫入磁碟機時、此LED會亮起。您必須等待此LED燈關閉、才能關閉電源。

... 關閉產品電源、並等待所有LED和七段顯示活動停止。






xref:../admin/index.adoc[管理StorageGRID]
