---
permalink: primer/managing-tenants-and-client-connections.html 
sidebar: sidebar 
keywords: tenant, client, connect, connection 
summary: 身為網格管理員、您可以建立及管理S3和Swift用戶端用來儲存及擷取物件的租戶帳戶、並管理可控制用戶端連線StorageGRID 至您的功能的組態選項。 
---
= 管理租戶和用戶端連線
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
身為網格管理員、您可以建立及管理S3和Swift用戶端用來儲存及擷取物件的租戶帳戶、並管理可控制用戶端連線StorageGRID 至您的功能的組態選項。



== 租戶帳戶

租戶帳戶可讓您指定哪些人可以使用StorageGRID 您的一套系統來儲存和擷取物件、以及哪些功能可供他們使用。租戶帳戶可讓支援S3 REST API或Swift REST API的用戶端應用程式、將物件儲存及擷取到StorageGRID 靜態上。每個租戶帳戶都使用S3用戶端傳輸協定或Swift用戶端傳輸協定。

您必須為每個用戶端傳輸協定建立至少一個租戶帳戶、以用於將物件儲存在StorageGRID 您的作業系統上。或者、如果您想要將儲存在系統上的物件依不同實體分隔、您也可以建立其他租戶帳戶。每個租戶帳戶都有自己的聯盟或本機群組和使用者、以及自己的儲存區（Swift的容器）和物件。

您可以使用Grid Manager或Grid Management API來建立租戶帳戶。建立租戶帳戶時、請指定下列資訊：

* 租戶的顯示名稱（租戶的帳戶ID會自動指派、無法變更）。
* 租戶帳戶是否會使用S3或Swift。
* 對於S3租戶帳戶：是否允許租戶帳戶使用平台服務。如果允許使用平台服務、則必須設定網格以支援其使用。
* 或者、租戶帳戶的儲存配額、也就是租戶物件可用的GB、TB或PB上限。租戶的儲存配額代表邏輯容量（物件大小）、而非實體容量（磁碟大小）。
* 如果啟用StorageGRID 身分識別聯盟以供支援整個系統、則哪個聯盟群組具有root存取權限可設定租戶帳戶。
* 如果StorageGRID 不使用單一登入（SSO）進行支援、則租戶帳戶是使用自己的身分識別來源、還是共用網格的身分識別來源、以及租戶本機root使用者的初始密碼。


如果S3租戶帳戶需要遵守法規要求、網格管理員可以針對StorageGRID 整個S3物件鎖定系統啟用全域S3物件鎖定設定。當系統啟用S3物件鎖定時、所有S3租戶帳戶都可以建立啟用S3物件鎖定的儲存區、然後為該儲存區中的物件版本指定保留和合法保留設定。

建立租戶帳戶之後、租戶使用者就能登入租戶管理程式。



== 用戶端連線StorageGRID 至節點

在租戶使用者使用S3或Swift用戶端將資料儲存及擷取到StorageGRID 效益分析系統之前、您必須先決定這些用戶端將如何連線StorageGRID 到效益分析節點。

用戶端應用程式可連線至下列任一項目、以儲存或擷取物件：

* 管理節點或閘道節點上的負載平衡器服務。這是建議的連線。
* 閘道節點上的CLB服務。
+

NOTE: CLB服務已過時。

* 儲存節點、無論是否有外部負載平衡器。


設定StorageGRID 支援用戶端使用負載平衡器服務的功能時、請執行下列步驟：

. 選擇性地設定高可用度（HA）群組。如果您建立HA群組、則多個管理節點和閘道節點的介面會置於主動備份組態中。用戶端連線是使用HA群組的虛擬IP位址進行。
. 設定負載平衡器服務的端點。管理節點或閘道節點上的負載平衡器服務會將傳入的網路連線從用戶端應用程式分散到儲存節點。建立負載平衡器端點時、請指定連接埠編號、端點是否接受HTTP或HTTPS連線、使用端點的用戶端類型（S3或Swift）、以及用於HTTPS連線的憑證（若適用）。
. （可選）指定節點的「用戶端網路」不受信任、以確保節點的「用戶端網路」所有連線都會發生在負載平衡器端點上。


.相關資訊
* xref:../admin/index.adoc[管理StorageGRID]
* xref:../tenant/index.adoc[使用租戶帳戶]
* xref:../s3/index.adoc[使用S3]
* xref:../swift/index.adoc[使用Swift]
* xref:exploring-tenant-manager.adoc[探索租戶管理程式]
* xref:configuring-network-settings.adoc[設定網路設定]

