---
permalink: sg5700/replacing-e5700sg-controller.html 
sidebar: sidebar 
keywords: storagegrid, sg5700, storage node, storage appliance, Replacing, replace, E5700sg, controller, remove, removing, removal, install, installing, installation 
summary: 如果E5700SG控制器無法正常運作或故障、您可能需要更換它。 
---
= 更換E5700SG控制器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果E5700SG控制器無法正常運作或故障、您可能需要更換它。

.您需要的是 #8217 ；需要的是什麼
* 您的更換控制器的零件編號與您要更換的控制器相同。
* 您已下載E系列指示、以更換故障的E5700控制器。
+

IMPORTANT: 只有當您需要更多詳細資料來執行特定步驟時、才可使用E系列說明進行參考。請勿仰賴E系列的指示來更換StorageGRID 產品中的控制器、因為這些程序並不相同。例如、E5700控制器的E系列說明說明如何從故障控制器中取出電池和主機介面卡（HIC）、並將其安裝在更換的控制器中。這些步驟不適用於E5700SG控制器。

* 您可以使用標籤來識別連接至控制器的每條纜線。
* 本產品已經使用過 xref:placing-appliance-into-maintenance-mode.adoc[已設定維護模式]。


當您更換控制器時、將無法存取應用裝置儲存節點。如果E5700SG控制器運作正常、您可以在本程序開始時執行管制關機。


NOTE: 如果您在安裝StorageGRID 完此程序之前更換控制器、可能StorageGRID 無法在完成此程序後立即存取《產品安裝程式（到此程序）」。雖然StorageGRID 您可以從與應用裝置位於同一子網路的其他主機存取《ENetApp應用裝置安裝程式」、但您無法從其他子網路的主機存取。此情況應在15分鐘內自行解決（當原始控制器的任何ARP快取項目逾時時）、或者您可以從本機路由器或閘道手動清除任何舊的ARP快取項目、以立即清除此狀況。

.步驟
. 當設備處於維護模式時、請關閉E5700SG控制器。
+
.. 登入網格節點：
+
... 輸入下列命令：「sh admin@_grid_node_ip_`」
... 輸入「passwords.txt」檔案中所列的密碼。
... 輸入下列命令以切換至root：「u -」
... 輸入「passwords.txt」檔案中所列的密碼。
+
以root登入時、提示會從「$」變更為「#」。



.. 關閉E5700SG控制器：+`* shutc -h now*
.. 等待快取記憶體中的任何資料寫入磁碟機。
+
需要將快取資料寫入磁碟機時、E2800控制器背面的綠色快取作用中LED會亮起。您必須等待此LED燈關閉。



. 關閉電源。
+
.. 從「SView System Manager」首頁SANtricity 選取*「View Operations in progress*」。
.. 確認所有作業均已完成。
.. 關閉產品上的兩個電源開關。
.. 等待所有LED關閉。


. 如果StorageGRID 連接至控制器的整個DHCP網路使用DHCP伺服器：
+
.. 記下更換控制器上連接埠的MAC位址（位於控制器的標籤上）。
.. 請網路管理員更新原始控制器的IP位址設定、以反映更換控制器的MAC位址。
+

IMPORTANT: 您必須先確認原始控制器的IP位址已更新、才能將電源供應給更換的控制器。否則、當控制器開機時、就會取得新的DHCP IP位址、而且可能無法重新連線StorageGRID 到故障。此步驟適用於StorageGRID 連接至控制器的所有環節網路。



. 從應用裝置中取出控制器：
+
.. 放置於防靜電腕帶上或採取其他防靜電預防措施。
.. 標示纜線、然後拔下纜線和SFP。
+

IMPORTANT: 為避免效能降低、請勿扭轉、摺疊、夾緊或踏上纜線。

.. 擠壓CAM握把上的栓鎖直到釋放為止、然後打開右側的CAM握把、即可從產品中釋放控制器。
.. 使用兩隻手和CAM握把、將控制器滑出產品。
+

IMPORTANT: 請務必用兩隻手支撐控制器的重量。



. 將替換控制器安裝到設備中。
+
.. 翻轉控制器、使可拆式護蓋面朝下。
.. 將CAM握把放在開啟位置、將控制器完全滑入產品。
.. 將CAM握把往左移動、將控制器鎖定到位。
.. 更換纜線和SFP。


. 開啟產品電源、並監控控制器LED和七段顯示器。
+
控制器成功開機後、七段顯示器應顯示下列項目：

+
** E2800控制器：
+
最後的狀態是「99」。

** E5700SG控制器：
+
最後的狀態是「HA」。



. 確認應用裝置儲存節點出現在Grid Manager中、且未顯示任何警示。


http://mysupport.netapp.com/info/web/ECMP1658252.html["NetApp E系列系統文件網站"^]
