---
permalink: expand/linux-adding-direct-attached-or-san-volumes-to-storage-node.html 
sidebar: sidebar 
keywords: expansion, Linux, add storage volumes 
summary: 如果儲存節點包含少於16個儲存磁碟區、您可以新增區塊儲存設備、讓Linux主機看到這些儲存設備、並將新的區塊裝置對應新增至StorageGRID 用於儲存節點的更新組態檔、藉此增加容量。 
---
= Linux：將直接附加或SAN磁碟區新增至儲存節點
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果儲存節點包含少於16個儲存磁碟區、您可以新增區塊儲存設備、讓Linux主機看到這些儲存設備、並將新的區塊裝置對應新增至StorageGRID 用於儲存節點的更新組態檔、藉此增加容量。

.您需要的是 #8217 ；需要的是什麼
* 您可以取得安裝StorageGRID 適用於Linux平台的功能介紹。
+
** xref:../rhel/index.adoc[安裝Red Hat Enterprise Linux或CentOS]
** xref:../ubuntu/index.adoc[安裝Ubuntu或DEBIAN]


* 您有「pes密碼」檔案。
* 您擁有特定的存取權限。



IMPORTANT: 當軟體升級、還原程序或其他擴充程序處於作用中狀態時、請勿嘗試將儲存磁碟區新增至儲存節點。

當您新增儲存磁碟區時、儲存節點會暫時無法使用。您應一次在一個儲存節點上執行此程序、以避免影響面向用戶端的網格服務。

.步驟
. 安裝新的儲存硬體。
+
如需詳細資訊、請參閱硬體廠商提供的文件。

. 建立所需大小的新區塊儲存磁碟區。
+
** 連接新的磁碟機並視需要更新RAID控制器組態、或在共享儲存陣列上配置新的SAN LUN、並允許Linux主機存取。
** 使用與現有儲存節點上儲存磁碟區相同的持續命名方案。
** 如果您使用StorageGRID 「物件節點移轉」功能、請將新的磁碟區顯示給其他Linux主機、這些主機是此儲存節點的移轉目標。如需更多資訊、請參閱Linux StorageGRID 平台的安裝資訊。


. 以root身分或具有Sudo權限的帳戶登入支援儲存節點的Linux主機。
. 確認新的儲存磁碟區可在Linux主機上看到。
+
您可能必須重新掃描裝置。

. 執行下列命令、暫時停用儲存節點：
+
「Udo StorageGRID 現象節點停止<node-name>」

. 使用vim或pico等文字編輯器、編輯儲存節點的節點組態檔、可在「/etc/storagegrid / nodes/<node-name>.conf」中找到。
. 找出節點組態檔中包含現有物件儲存區塊裝置對應的區段。
+
在範例中、「block_device_RANGEDB_00」到「block_device_RANGEDB_03」是現有的物件儲存區塊裝置對應。

+
[listing, subs="specialcharacters,quotes"]
----
NODE_TYPE = VM_Storage_Node
ADMIN_IP = 10.1.0.2
BLOCK_DEVICE_VAR_LOCAL = /dev/mapper/sgws-sn1-var-local
*BLOCK_DEVICE_RANGEDB_00 = /dev/mapper/sgws-sn1-rangedb-0*
*BLOCK_DEVICE_RANGEDB_01 = /dev/mapper/sgws-sn1-rangedb-1*
*BLOCK_DEVICE_RANGEDB_02 = /dev/mapper/sgws-sn1-rangedb-2*
*BLOCK_DEVICE_RANGEDB_03 = /dev/mapper/sgws-sn1-rangedb-3*
GRID_NETWORK_TARGET = bond0.1001
ADMIN_NETWORK_TARGET = bond0.1002
CLIENT_NETWORK_TARGET = bond0.1003
GRID_NETWORK_IP = 10.1.0.3
GRID_NETWORK_MASK = 255.255.255.0
GRID_NETWORK_GATEWAY = 10.1.0.1
----
. 新增對應於您為此儲存節點新增之區塊儲存磁碟區的物件儲存區塊裝置對應。
+
請務必從下一個「block_device_RANGEDB_NN」開始。請勿留下落差。

+
** 根據上述範例、從「block_device_RANGEDB_04」開始。
** 在以下範例中、節點新增了四個新的區塊儲存磁碟區：「block_device_RANGEDB_04」至「block_device_RANGEDB_07」。


+
[listing, subs="specialcharacters,quotes"]
----
NODE_TYPE = VM_Storage_Node
ADMIN_IP = 10.1.0.2
BLOCK_DEVICE_VAR_LOCAL = /dev/mapper/sgws-sn1-var-local
BLOCK_DEVICE_RANGEDB_00 = /dev/mapper/sgws-sn1-rangedb-0
BLOCK_DEVICE_RANGEDB_01 = /dev/mapper/sgws-sn1-rangedb-1
BLOCK_DEVICE_RANGEDB_02 = /dev/mapper/sgws-sn1-rangedb-2
BLOCK_DEVICE_RANGEDB_03 = /dev/mapper/sgws-sn1-rangedb-3
*BLOCK_DEVICE_RANGEDB_04 = /dev/mapper/sgws-sn1-rangedb-4*
*BLOCK_DEVICE_RANGEDB_05 = /dev/mapper/sgws-sn1-rangedb-5*
*BLOCK_DEVICE_RANGEDB_06 = /dev/mapper/sgws-sn1-rangedb-6*
*BLOCK_DEVICE_RANGEDB_07 = /dev/mapper/sgws-sn1-rangedb-7*
GRID_NETWORK_TARGET = bond0.1001
ADMIN_NETWORK_TARGET = bond0.1002
CLIENT_NETWORK_TARGET = bond0.1003
GRID_NETWORK_IP = 10.1.0.3
GRID_NETWORK_MASK = 255.255.255.0
GRID_NETWORK_GATEWAY = 10.1.0.1
----
. 執行下列命令、以驗證您對儲存節點節點組態檔所做的變更：
+
「Udo StorageGRID 現象節點驗證<節點名稱>」

+
在繼續下一步之前、請先解決任何錯誤或警告。

+
[NOTE]
====
如果您發現類似下列的錯誤、表示節點組態檔嘗試將「<節點名稱>」用於「<用途>」的區塊裝置對應至Linux檔案系統中的指定「<路徑名稱>」、 但該位置沒有有效的區塊裝置特殊檔案（或區塊裝置特殊檔案的軟體連結）。

[listing]
----
Checking configuration file for node <node-name>…
ERROR: BLOCK_DEVICE_<PURPOSE> = <path-name>
<path-name> is not a valid block device
----
請確認您輸入的「<路徑名稱>」正確無誤。

====
. 執行下列命令、以新的區塊裝置對應重新啟動節點：
+
「Udo StorageGRID 節點start <節點名稱>」

. 以admin身分登入儲存節點、並使用「passwords.txt」檔案中所列的密碼。
. 檢查服務是否正確啟動：
+
.. 查看服務器上所有服務的狀態列表：+"show storagegrid STATUS"
+
狀態會自動更新。

.. 請等到所有服務都在執行或已驗證為止。
.. 結束狀態畫面：
+
「Ctrl+C」



. 設定儲存節點使用的新儲存設備：
+
.. 設定新的儲存磁碟區：
+
「Udo add_rangedbs.rb」

+
此指令碼會尋找任何新的儲存磁碟區、並提示您進行格式化。

.. 輸入* y*格式化儲存磁碟區。
.. 如果任何磁碟區先前已格式化、請決定是否要重新格式化。
+
*** 輸入* y*重新格式化。
*** 輸入* n*跳過重新格式化。


.. 當系統詢問時、輸入* y*停止儲存服務。
+
儲存服務會停止、而「setup_rangedbs.sh」指令碼會自動執行。當磁碟區準備好用作rangedbs之後、服務就會重新啟動。



. 檢查服務是否正確啟動：
+
.. 檢視伺服器上所有服務的狀態清單：
+
「Udo storagegrid狀態」

+
狀態會自動更新。

.. 請等到所有服務都在執行或已驗證為止。
.. 結束狀態畫面：
+
「Ctrl+C」



. 確認儲存節點已上線：
+
.. 使用登入Grid Manager xref:../admin/web-browser-requirements.adoc[支援的網頁瀏覽器]。
.. 選取*支援*>*工具*>*網格拓撲*。
.. 選擇「*站台_*>*儲存節點_*>* LdR*>*儲存設備*」。
.. 選取*組態*索引標籤、然後選取*主要*索引標籤。
.. 如果*儲存狀態-所需*下拉式清單設定為唯讀或離線、請選取*線上*。
.. 按一下*套用變更*。


. 若要查看新的物件存放區：
+
.. 選擇*節點*>*站台*>*儲存節點*>*儲存設備*。
.. 在*物件存放區*表格中檢視詳細資料。




您現在可以使用儲存節點的擴充容量來儲存物件資料。
