---
permalink: expand/rebalancing-erasure-coded-data-after-adding-storage-nodes.html 
sidebar: sidebar 
keywords: erasure coding, EC, rebalancing, site rebalance procedure 
summary: 在某些情況下、您可能需要在新增儲存節點之後、重新平衡以銷毀編碼的資料。 
---
= 新增儲存節點後、重新平衡以銷毀編碼的資料
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在某些情況下、您可能需要在新增儲存節點之後、重新平衡以銷毀編碼的資料。

.您需要的產品
* 您已完成新增儲存節點的擴充步驟。
* 您已檢閱 xref:considerations-for-rebalancing-erasure-coded-data.adoc[重新平衡銷毀編碼資料的考量事項]。
+

IMPORTANT: 只有在站台的一個或多個儲存節點觸發*低物件儲存*警示、且您無法新增建議的新儲存節點數時、才執行此程序。

* 您瞭解複寫的物件資料將不會透過此程序移動、而且在決定移除編碼資料的位置時、EC重新平衡程序不會考慮每個儲存節點上的複寫資料使用量。
* 您有「pes密碼」檔案。


.關於這項工作
執行EC重新平衡程序時、ILM作業和S3和Swift用戶端作業的效能可能會受到影響。因此、您只能在有限的情況下執行此程序。


NOTE: EC重新平衡程序會暫時保留大量的儲存空間。儲存警示可能會觸發、但會在重新平衡完成時解決。如果保留空間不足、EC重新平衡程序將會失敗。無論程序失敗或成功、在EC重新平衡程序完成時、都會釋出儲存保留。

[NOTE]
====
若要上傳物件（或物件零件）、S3和Swift API作業可能會在EC重新平衡程序期間失敗、但需要24小時以上才能完成。如果適用的ILM規則在擷取時使用嚴格或平衡的位置、則長時間投入作業將會失敗。將報告下列錯誤：

「500內部伺服器錯誤」

====
.步驟
. [[ree_object_storage ]檢閱您計畫重新平衡之站台的目前物件儲存詳細資料。
+
.. 選擇*節點*。
.. 選取站台的第一個儲存節點。
.. 選擇* Storage*（儲存設備）選項卡。
.. 將游標停留在「已使用的儲存設備-物件資料」圖表上、即可查看儲存節點上目前的複寫資料量和銷毀編碼資料。
.. 重複這些步驟、即可檢視站台上的其他儲存節點。


. 登入主要管理節點：
+
.. 輸入下列命令：「sh admin@_primary管理節點IP」
.. 輸入「passwords.txt」檔案中所列的密碼。
.. 輸入下列命令以切換至root：「u -」
.. 輸入「passwords.txt」檔案中所列的密碼。
+
以root登入時、提示會從「$」變更為「#」。



. 輸入下列命令：
+
「重新平衡資料開始-站台「站台名稱」

+
對於"_sipe-name_"、請指定您新增儲存節點的第一個站台。在引號中加上「ite名稱」。

+
EC重新平衡程序隨即開始、並傳回工作ID。

. 複製工作ID。
. 監控EC重新平衡程序的狀態。
+
** 若要檢視單一EC重新平衡程序的狀態：
+
「資料平衡狀態：job-id _job-id_」

+
對於「_job-id_」、請指定開始程序時傳回的ID。

** 若要檢視目前EC重新平衡程序的狀態、以及任何先前完成的程序：
+
「資料平衡狀態」

+
[NOTE]
====
若要取得有關reBalance-data命令的說明：

「資料平衡-說明」

====
** 若要檢視目前工作的預估完成時間和完成百分比、請選取* support*>* Tools *>* Metrics *。然後在Grafana區段中選取* EC Overview *。請參閱* Grid EC工作預估完成時間*和* Grid EC工作百分比已完成*儀表板。


. 根據傳回的狀態執行其他步驟：
+
** 如果狀態為「進行中」、表示EC重新平衡作業仍在執行中。您應該定期監控程序、直到程序完成為止。
** 如果狀態為「失敗」、請執行 <<rebalance_fail,故障步驟>>。
** 如果狀態為「成功」、請執行 <<rebalance_succeed,成功步驟>>。


. 如果EC重新平衡程序產生過多負載（例如、擷取作業會受到影響）、請暫停程序。
+
「資料平衡暫停-工作ID _job-id_」

. 如果您需要終止EC重新平衡程序（例如、您可以執行StorageGRID 更新版的程式碼）、請輸入下列命令：
+
"REBalance-data終止--job-id _job-id_"

+

NOTE: 當您終止EC重新平衡程序時、任何已移動的資料片段都會保留在新位置。資料不會移回原始位置。

. [[reBalance_fail]如果EC重新平衡程序的狀態為「失敗」、請遵循下列步驟：
+
.. 確認站台上的所有儲存節點均已連線至網格。
.. 檢查並解決可能影響這些儲存節點的任何警示。
+
如需特定警示的相關資訊、請參閱監控與疑難排解指示。

.. 重新啟動EC重新平衡程序：+「重新平衡資料啟動–-job-id _job-id_」
.. 如果EC重新平衡程序的狀態仍為「失敗」、請聯絡技術支援部門。


. [[reBalance_fucion]如果EC重新平衡程序的狀態為「成功」（選擇性） <<review_object_storage,檢閱物件儲存>> 以查看網站的更新詳細資料。
+
在站台的儲存節點之間、銷毀編碼的資料現在應該更為平衡。

. 如果您在多個站台使用銷毀編碼、請針對所有其他受影響的站台執行此程序。

