---
permalink: ilm/guidelines-for-creating-storage-pools.html 
sidebar: sidebar 
keywords: storage pool guidelines 
summary: 設定及使用儲存資源池時、請遵循下列準則。 
---
= 建立儲存資源池的準則
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
設定及使用儲存資源池時、請遵循下列準則。



== 所有儲存資源池的準則

* 包含預設儲存資源池「All Storage Node」、使用預設站台、All站台、以及預設儲存等級「All Storage Node」StorageGRID 。每當您新增資料中心站台時、所有儲存節點儲存池都會自動更新。
+

NOTE: 不建議使用「所有儲存節點」儲存資源池或「所有站台」站台、因為這些項目會自動更新、以納入您新增到擴充中的任何新站台、這可能不是您想要的行為。在使用All Storage Node儲存資源池或預設站台之前、請仔細檢閱複寫和銷毀編碼複本的準則。

* 盡量簡化儲存資源池組態。請勿建立比必要更多的儲存資源池。
* 建立盡可能多節點的儲存資源池。每個儲存資源池應包含兩個以上的節點。如果節點無法使用、節點不足的儲存資源池可能會導致ILM待處理記錄。
* 避免建立或使用重疊的儲存資源池（包含一或多個相同節點）。如果儲存資源池重疊、可能會在同一個節點上儲存多個物件資料複本。




== 複寫複本所使用的儲存資源池準則

* 為每個站台建立不同的儲存資源池。然後、在每個規則的放置指示中、指定一或多個站台專屬的儲存資源池。針對每個站台使用儲存資源池、可確保複寫的物件複本完全符合您的期望（例如、每個站台的每個物件都有一個複本、以保護站台損失）。
* 如果您在擴充中新增站台、請為新站台建立新的儲存資源池。然後更新ILM規則、以控制新站台上儲存的物件。
* 一般而言、請勿使用預設的儲存資源池、所有儲存節點或任何包含預設站台「所有站台」的儲存資源池。




== 用於銷毀編碼複本的儲存資源池準則

* 您無法將歸檔節點用於銷毀編碼資料。
* 儲存資源池中包含的儲存節點和站台數量、決定可用的銷毀編碼方案。
* 如果儲存資源池僅包含兩個站台、您就無法使用該儲存資源池來進行銷毀編碼。對於有兩個站台的儲存資源池、沒有可用的銷毀編碼方案。
* 一般而言、請勿使用預設儲存資源池、所有儲存節點或任何包含預設站台的儲存資源池、任何「刪除編碼」設定檔中的「所有站台」。
+

NOTE: 如果您的網格僅包含一個站台、就無法在「刪除編碼」設定檔中使用「所有儲存節點」儲存資源池或「所有站台」預設站台。如果新增第二個站台、此行為可防止「刪除編碼」設定檔變成無效。

* 如果您的處理量需求很高、如果站台之間的網路延遲超過100毫秒、則不建議建立包含多個站台的儲存資源池。隨著延遲時間增加、StorageGRID 由於TCP網路處理量減少、導致導致導致無法建立、放置及擷取物件片段的速度大幅降低。處理量減少會影響物件擷取和擷取的最大可達成速率（選取「嚴格」或「平衡」作為擷取行為）、或可能導致ILM佇列待處理記錄（選取「雙重提交」作為擷取行為時）。
* 如果可能、儲存資源池應包含超過您所選銷毀編碼方案所需的最小儲存節點數。例如、如果您使用6+3銷毀編碼方案、則至少必須有九個儲存節點。不過、建議每個站台至少有一個額外的儲存節點。
* 將儲存節點分散至各個站台、盡量平均。例如、若要支援6+3銷毀編碼方案、請在三個站台設定至少包含三個儲存節點的儲存資源池。




== 用於歸檔複本的儲存資源池準則

* 您無法建立同時包含儲存節點和歸檔節點的儲存資源池。歸檔複本需要僅包含歸檔節點的儲存資源池。
* 使用包含歸檔節點的儲存資源池時、您也應該在包含儲存節點的儲存資源池上、維護至少一個複寫或銷毀編碼的複本。
* 如果已啟用全域S3物件鎖定設定、且您正在建立相容的ILM規則、則無法使用包含歸檔節點的儲存資源池。請參閱「使用S3物件鎖定來管理物件」的指示。
* 如果歸檔節點的目標類型是「雲端分層-簡易儲存服務（S3）」、則歸檔節點必須位於自己的儲存資源池中。請參閱 xref:../admin/index.adoc[管理StorageGRID]。


.相關資訊
* xref:what-replication-is.adoc[什麼是複寫]
* xref:what-erasure-coding-is.adoc[什麼是銷毀編碼]
* xref:what-erasure-coding-schemes-are.adoc[什麼是銷毀編碼方案]
* xref:using-multiple-storage-pools-for-cross-site-replication.adoc[使用多個儲存資源池進行跨站台複寫]

