---
permalink: ilm/using-last-access-time-in-ilm-rules.html 
sidebar: sidebar 
keywords: last access time, ilm rule reference time 
summary: 您可以在ILM規則中使用「上次存取時間」做為參考時間。例如、您可能想要保留過去三個月在本機儲存節點上檢視過的物件、同時將最近未檢視過的物件移至異地位置。如果您希望ILM規則僅套用至上次在特定日期存取的物件、也可以使用「上次存取時間」做為進階篩選器。 
---
= 在ILM規則中使用上次存取時間
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在ILM規則中使用「上次存取時間」做為參考時間。例如、您可能想要保留過去三個月在本機儲存節點上檢視過的物件、同時將最近未檢視過的物件移至異地位置。如果您希望ILM規則僅套用至上次在特定日期存取的物件、也可以使用「上次存取時間」做為進階篩選器。

.關於這項工作
在ILM規則中使用上次存取時間之前、請先檢閱下列考量事項：

* 使用「上次存取時間」做為參考時間時、請注意、變更物件的上次存取時間並不會觸發即時的ILM評估。而是評估物件的放置位置、並在背景ILM評估物件時視需要移動物件。存取物件之後、可能需要兩週或更久的時間。
+
根據「上次存取時間」建立ILM規則時、請將此延遲列入考量、並避免使用短時間（少於一個月）的放置位置。

* 使用「上次存取時間」作為進階篩選器或參考時間時、您必須針對S3儲存區啟用上次存取時間更新。您可以使用租戶管理程式或租戶管理API。
+

NOTE: Swift容器一律會啟用上次存取時間更新、但S3儲存區預設會停用。

+

IMPORTANT: 請注意、啟用上次存取時間更新可能會降低效能、尤其是在使用小型物件的系統中。效能影響的發生、是因為StorageGRID 每次擷取物件時、都必須使用新的時間戳記來更新物件。



下表摘要說明是否針對不同類型的要求、更新儲存區中所有物件的上次存取時間。

[cols="1a,1a,1a"]
|===
| 申請類型 | 上次存取時間更新停用時、是否更新上次存取時間 | 上次存取時間是否在上次存取時間更新啟用時更新 


 a| 
要求擷取物件、其存取控制清單或其中繼資料
 a| 
否
 a| 
是的



 a| 
要求更新物件的中繼資料
 a| 
是的
 a| 
是的



 a| 
要求將物件從一個儲存區複製到另一個儲存區
 a| 
* 否、來源複本
* 是、適用於目的地複本

 a| 
* 是、來源複本
* 是、適用於目的地複本




 a| 
要求完成多部分上傳
 a| 
是的、適用於組裝好的物件
 a| 
是的、適用於組裝好的物件

|===
.相關資訊
* xref:../s3/index.adoc[使用S3]
* xref:../tenant/index.adoc[使用租戶帳戶]

