---
permalink: ilm/what-erasure-coding-schemes-are.html 
sidebar: sidebar 
keywords: erasure coding scheme 
summary: 當您為ILM規則設定「刪除編碼」設定檔時、會根據您計畫使用的儲存資源池中有多少個儲存節點和站台、選取可用的銷毀編碼配置。銷毀編碼方案可控制每個物件所建立的資料片段數量、以及同位元檢查片段數量。 
---
= 什麼是銷毀編碼方案
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當您為ILM規則設定「刪除編碼」設定檔時、會根據您計畫使用的儲存資源池中有多少個儲存節點和站台、選取可用的銷毀編碼配置。銷毀編碼方案可控制每個物件所建立的資料片段數量、以及同位元檢查片段數量。

此系統使用Reed-Solomon銷毀編碼演算法。StorageGRID演算法會將物件分割成k個資料片段、並計算m同位元檢查片段。k + m = n個片段分佈在n個儲存節點上、以提供資料保護。物件最多可維持遺失或毀損的片段。擷取或修復物件需要K個片段。

設定「刪除編碼」設定檔時、請針對儲存資源池使用下列準則：

* 儲存資源池必須包含三個或多個站台、或只包含一個站台。
+

NOTE: 如果儲存資源池包含兩個站台、則無法設定「刪除編碼」設定檔。

+
** <<包含三個以上站台之儲存資源池的銷毀編碼配置,包含三個以上站台之儲存資源池的銷毀編碼配置>>
** <<單一站台儲存資源池的銷毀編碼配置,單一站台儲存資源池的銷毀編碼配置>>


* 請勿使用預設的儲存資源池、所有儲存節點或包含預設站台All站台的儲存資源池。
* 儲存資源池應至少包含_k+m_+1個儲存節點。
+
所需的最小儲存節點數為_k+m_。不過、如果所需的儲存節點暫時無法使用、則至少要有一個額外的儲存節點、有助於防止擷取失敗或ILM待處理項目。



銷毀編碼方案的儲存負荷是以同位元檢查片段數（_m_）除以資料片段數（_k_）來計算。您可以使用儲存負荷來計算每個銷毀編碼物件所需的磁碟空間：

「_disk space_=_object Size_+（_object Size_*_storage happe_）」

例如、如果您使用4+2配置儲存10 MB物件（儲存負荷為50%）、則物件會耗用15 MB的網格儲存空間。如果您使用6+2方案儲存相同的10 MB物件（其儲存負荷高達33%）、則物件會耗用約13.3MB的空間。

選取最小總值為_k+m_的銷毀編碼方案、以符合您的需求。整體而言、使用較少片段的銷毀編碼配置、運算效率較高、因為每個物件所建立及分散（或擷取）的片段較少、因此由於片段大小較大、因此效能較佳、而且需要更多儲存設備時、擴充所需的節點較少。（如StorageGRID 需規劃儲存擴充的相關資訊、請參閱《擴充指令》。）



== 包含三個以上站台之儲存資源池的銷毀編碼配置

下表說明StorageGRID 目前由支援的銷毀編碼方案、適用於包含三個以上站台的儲存資源池。所有這些方案都提供站台損失保護。一個站台可能會遺失、而且物件仍可存取。

對於提供站台遺失保護的銷毀編碼方案、儲存資源池中建議的儲存節點數量超過_k+m_+1、因為每個站台至少需要三個儲存節點。

[cols="1a,1a,1a,1a,1a,1a"]
|===
| 銷毀編碼方案（_k+m_） | 已部署站台的最小數量 | 每個站台的建議儲存節點數 | 建議的儲存節點總數 | 站台遺失保護？ | 儲存負荷 


 a| 
4+2
 a| 
3.
 a| 
3.
 a| 
9.
 a| 
是的
 a| 
50%



 a| 
6+2
 a| 
4.
 a| 
3.
 a| 
12.
 a| 
是的
 a| 
33%



 a| 
8+2
 a| 
5.
 a| 
3.
 a| 
15
 a| 
是的
 a| 
25%



 a| 
6+3.
 a| 
3.
 a| 
4.
 a| 
12.
 a| 
是的
 a| 
50%



 a| 
9+3.
 a| 
4.
 a| 
4.
 a| 
16
 a| 
是的
 a| 
33%



 a| 
2+1
 a| 
3.
 a| 
3.
 a| 
9.
 a| 
是的
 a| 
50%



 a| 
4+1
 a| 
5.
 a| 
3.
 a| 
15
 a| 
是的
 a| 
25%



 a| 
6+1
 a| 
7.
 a| 
3.
 a| 
21
 a| 
是的
 a| 
17%



 a| 
7+5.
 a| 
3.
 a| 
5.
 a| 
15
 a| 
是的
 a| 
71%

|===

NOTE: 每個站台至少需要三個儲存節點。StorageGRID若要使用7+5方案、每個站台至少需要四個儲存節點。建議每個站台使用五個儲存節點。

選取提供站台保護的銷毀編碼方案時、請平衡下列因素的相對重要性：

* *片段數量*：當片段總數較少時、效能和擴充彈性通常會較佳。
* *容錯能力*：容錯能力會增加多個同位元檢查區段（也就是當_m_的值較高時）。
* *網路流量*：當從故障中恢復時、使用含有更多片段的配置（亦即、_k+m_的總計較高）會產生更多網路流量。
* *儲存負荷*：成本較高的配置需要更多的每個物件儲存空間。


例如、在4+2方案和6+3方案（兩者都有50%的儲存負荷）之間做出決定時、如果需要額外的容錯能力、請選取6+3方案。如果網路資源受到限制、請選取4+2方案。如果所有其他因素都相同、請選取4+2、因為它的片段總數較少。


NOTE: 如果您不確定要使用哪種方案、請選取4+2或6+3、或聯絡技術支援部門。



== 單一站台儲存資源池的銷毀編碼配置

只要站台有足夠的儲存節點、單一站台儲存池即可支援針對三個以上站台所定義的所有銷毀編碼方案。

所需的儲存節點數量下限為_k+m_、但建議使用具有_k+m_+1儲存節點的儲存資源池。例如、2+1銷毀編碼方案需要至少三個儲存節點的儲存資源池、但建議使用四個儲存節點。

[cols="1a,1a,1a,1a"]
|===
| 銷毀編碼方案（_k+m_） | 最小儲存節點數 | 建議的儲存節點數 | 儲存負荷 


 a| 
4+2
 a| 
6.
 a| 
7.
 a| 
50%



 a| 
6+2
 a| 
8.
 a| 
9.
 a| 
33%



 a| 
8+2
 a| 
10.
 a| 
11.
 a| 
25%



 a| 
6+3.
 a| 
9.
 a| 
10.
 a| 
50%



 a| 
9+3.
 a| 
12.
 a| 
13.
 a| 
33%



 a| 
2+1
 a| 
3.
 a| 
4.
 a| 
50%



 a| 
4+1
 a| 
5.
 a| 
6.
 a| 
25%



 a| 
6+1
 a| 
7.
 a| 
8.
 a| 
17%



 a| 
7+5.
 a| 
12.
 a| 
13.
 a| 
71%

|===
.相關資訊
xref:../expand/index.adoc[擴充網格]
