---
permalink: fabricpool/using-storagegrid-ilm-with-fabricpool-data.html 
sidebar: sidebar 
keywords: FabricPool, requirements, ILM, information lifecycle management, ILM rule, ILM rules, ILM policy, erasure-coding, replication, cloud storage pool, glacier 
summary: 如果您使用FabricPool 支援資料的功能來將資料分層StorageGRID 以供參考、則必須瞭解建立StorageGRID 資訊生命週期管理（ILM）規則的需求、以及管理FabricPool 資料的ILM原則。您必須確保適用於FabricPool 不中斷營運的ILM規則。 
---
= 利用支援資料的功能來進行資訊生命週期管理StorageGRID FabricPool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您使用FabricPool 支援資料的功能來將資料分層StorageGRID 以供參考、則必須瞭解建立StorageGRID 資訊生命週期管理（ILM）規則的需求、以及管理FabricPool 資訊的ILM原則。您必須確保適用於FabricPool 不中斷營運的ILM規則。


IMPORTANT: 不知道什麼是無法理解的ILM規則或原則。FabricPool StorageGRID如果無法設定不正確的ILM原則、就可能發生資料遺失StorageGRID 。請參閱 xref:../ilm/index.adoc[使用ILM管理物件] 以取得詳細的ILM指示。

請檢閱這些準則、確保您的ILM規則和ILM原則適用於FabricPool 各種資料和業務需求。如果您已經在使用StorageGRID 無法修復的ILM、您可能需要更新使用中的ILM原則、以符合這些準則。

* 您可以使用複寫和銷毀編碼規則的任何組合來保護雲端層資料。
+
建議的最佳實務做法是在站台內使用2+1銷毀編碼、以達到具成本效益的資料保護。銷毀編碼使用的CPU較多、但儲存容量卻遠低於複寫。4+1和6+1方案使用的容量比2+1方案少。不過、如果您需要在網格擴充期間新增儲存節點、4+1和6+1配置的彈性會較低。如需詳細資訊、請參閱 xref:../expand/adding-storage-capacity-for-erasure-coded-objects.adoc[新增銷毀編碼物件的儲存容量]。

* 套用至FabricPool 資料的每個規則都必須使用銷毀編碼、否則必須至少建立兩個複製複本。
+

IMPORTANT: ILM規則只會在任何時間段建立一個複寫複本、使資料有永久遺失的風險。如果只有一個物件複寫複本存在、則當儲存節點故障或發生重大錯誤時、該物件就會遺失。在升級等維護程序期間、您也會暫時失去物件的存取權。

* 請勿使用將過期或刪除FabricPool 的ILM規則。將每個ILM規則中的保留期間設為「Forever（永久）」、以確保FabricPool 不會由StorageGRID ILM刪除任何物件。
* 請勿建立規則、將FabricPool 不再需要的雲端層資料移出儲存庫、移至其他位置。您無法使用ILM規則FabricPool 、使用歸檔節點將資料歸檔至磁帶、或使用雲端儲存資源池、將FabricPool 不實資料移至其他物件存放區。
+

NOTE: 由於從雲端儲存資源池目標擷取物件的延遲增加、因此不支援使用FabricPool 含有支援功能的雲端儲存資源池。

* 從功能完善的9.8開始ONTAP 、您可以選擇性地建立物件標記、以協助分類及排序階層式資料、以便更輕鬆地進行管理。例如、您只能在FabricPool 附加StorageGRID 到該功能的不含資料的地方設定標籤。然後、當您在StorageGRID 物件標籤進階篩選器中建立ILM規則時、可以使用物件標籤進階篩選器來選取及放置此資料。




== ILM原則範例FabricPool ：資料不整

使用這個簡單的原則範例做為您自己ILM規則和原則的起點。

本範例假設您正在為StorageGRID 位於科羅拉多州丹佛的單一資料中心、擁有四個儲存節點的一套系統設計ILM規則和ILM原則。本範例中的資料使用名為「fabricpool桶」的儲存區。FabricPool


CAUTION: 下列ILM規則和原則僅為範例。有許多方法可以設定ILM規則。在啟動新原則之前、請先模擬建議的原則、確認其運作方式符合保護內容免於遺失的目的。若要深入瞭解、請參閱 xref:../ilm/index.adoc[使用ILM管理物件]。

.步驟
. 建立名為*登*的儲存資源池。選取丹佛網站。
. 建立名為* 2加1*的銷毀編碼設定檔。選取2+1銷毀編碼方案和*登*儲存資源池。
. 建立僅適用於「fabricPool-Bucket」資料的ILM規則。此範例規則會建立以銷毀編碼的複本。
+
[cols="1a,2a"]
|===
| 規則定義 | 範例值 


 a| 
規則名稱
 a| 
2加上1個FabricPool 用於資料的銷毀編碼



 a| 
儲存區名稱
 a| 
《fabricpool桶》

您也可以篩選FabricPool 出這個帳戶。



 a| 
進階篩選
 a| 
物件大小（MB）大於0.2 MB。

*附註：* FabricPool 僅供參考寫入4 MB物件、但您必須新增物件大小篩選器、因為此規則使用銷毀編碼。



 a| 
參考時間
 a| 
擷取時間



 a| 
放置
 a| 
從第0天開始、永遠儲存



 a| 
類型
 a| 
銷毀編碼



 a| 
位置
 a| 
登（2加1）



 a| 
擷取行為
 a| 
平衡

|===
. 建立ILM規則、為第一個規則不相符的任何物件建立兩個複寫複本。請勿選取基本篩選器（租戶帳戶或庫位名稱）或任何進階篩選器。
+
[cols="1a,2a"]
|===
| 規則定義 | 範例值 


 a| 
規則名稱
 a| 
兩個複寫複本



 a| 
儲存區名稱
 a| 
_無_



 a| 
進階篩選
 a| 
_無_



 a| 
參考時間
 a| 
擷取時間



 a| 
放置
 a| 
從第0天開始、永遠儲存



 a| 
類型
 a| 
複寫



 a| 
位置
 a| 
Den



 a| 
複本
 a| 
2.



 a| 
擷取行為
 a| 
平衡

|===
. 建立建議的ILM原則、然後選取這兩個規則。由於複寫規則不使用任何篩選器、因此它可以是原則的預設（最後）規則。
. 將測試物件擷取至網格。
. 使用測試物件模擬原則、以驗證行為。
. 啟動原則。


啟用此原則StorageGRID 時、將物件資料放置如下：

* 從FabricPool 「fabricPool-Bucket」中分層的資料、將會使用2+1銷毀編碼方案進行銷毀編碼。兩個資料片段和一個同位元檢查片段將放置在三個不同的儲存節點上。
* 所有其他儲存區中的所有物件都會複寫。將會建立兩個複本、並放置在兩個不同的儲存節點上。
* 在StorageGRID S3用戶端刪除之前、銷毀編碼和複製的複本都會保留在整個過程中。ILM永遠不會刪除這些項目。StorageGRID

